apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: create-subtraction
  labels:
    app.kubernetes.io/name: create-subtraction
    app.kubernetes.io/component: workflow
    app.kubernetes.io/part-of: virtool
    app.virtool.ca/workflow-name: create-subtraction
    app.virtool.ca/workflow-size: small
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app.kubernetes.io/name: create-subtraction
          app.kubernetes.io/component: workflow
          app.kubernetes.io/part-of: virtool
      spec:
        containers:
          - name: workflow-create-subtraction
            image: ghcr.io/virtool/ts-create-subtraction:latest
            env:
              - name: VT_PROC
                value: "2"
              - name: VT_MEM
                value: "2"
              - name: VT_WORKFLOW
                value: create_subtraction
            resources:
              limits:
                cpu: 2000m
                memory: 3Gi
              requests:
                cpu: 1000m
                memory: 2Gi
  triggers:
    - type: metrics-api
      metadata:
        url: "http://virtool-jobs-api-service.default.svc.cluster.local/jobs/counts"
        valueLocation: "pending.create_subtraction"
        targetValue: "1"
        activationTargetValue: "0"
