import { describe, expect, it } from "vitest";
import { CacheParamError } from "../errors";
import {
	type CacheParams,
	canonicalizeCacheParams,
	deriveCacheKey,
	float,
} from "./key";

/**
 * Generated by running Python's own serialiser — the exact expression
 * `virtool/caches/utils.py` uses:
 *
 * ```python
 * json.dumps(params, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
 * hashlib.sha256(canonical.encode("utf-8")).hexdigest()
 * ```
 *
 * These are the contract with Python, not a snapshot of our own output. Never
 * "fix" one by pasting in what this implementation currently produces — that
 * converts a caught divergence into a permanent one.
 */
const GOLDENS: ReadonlyArray<{
	name: string;
	params: CacheParams;
	canonical: string;
	key: string;
}> = [
	{
		name: "an empty object",
		params: {},
		canonical: "{}",
		key: "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
	},
	{
		name: "ascii strings",
		params: { kind: "trimmed_reads", workflow: "nuvs" },
		canonical: '{"kind":"trimmed_reads","workflow":"nuvs"}',
		key: "48a155757e3923e4f42eb4fc49b87eb2c51c2241c24e706c15010a9d2c5c8156",
	},
	{
		name: "integers, including zero and a negative",
		params: { min_length: 20, negative: -3, parent_id: 7, zero: 0 },
		canonical: '{"min_length":20,"negative":-3,"parent_id":7,"zero":0}',
		key: "432c9210d6ca9dc525494cafdd945b6bb0538ec270ad55e89ba780ea5f28e810",
	},
	{
		name: "integral floats, which keep their trailing .0",
		params: { floor: float(0.0), max_error_rate: float(1.0) },
		canonical: '{"floor":0.0,"max_error_rate":1.0}',
		key: "1b9b5cd19f11f6c5ff6a52452afe5e2917e94efe12cf999ca8fe07f7d1a71776",
	},
	{
		name: "negative zero, whose sign Python keeps",
		params: { value: float(-0) },
		canonical: '{"value":-0.0}',
		key: "c848a4efa987f46ba3bfd46242333afcb1c68c3240e0f35ae9d269b1c980648b",
	},
	{
		name: "a negative integral float",
		params: { value: float(-1.0) },
		canonical: '{"value":-1.0}',
		key: "25b0cd67ad547ad0a368b2337cae534414de1bdeae750e3274f241021d73a7ff",
	},
	{
		name: "negative and positive zero side by side",
		params: { a: float(-0), b: float(0) },
		canonical: '{"a":-0.0,"b":0.0}',
		key: "090e793f6c71f1cb8b6bfec4af997131680663892a43c60839cfd7b579cfc56d",
	},
	{
		name: "fractional floats",
		params: { max_error_rate: float(0.1), max_indel_rate: float(0.03) },
		canonical: '{"max_error_rate":0.1,"max_indel_rate":0.03}',
		key: "3711606187a6294532a12b824399fd74d65f0ac8e49da3465f6673b80c627d99",
	},
	{
		name: "booleans",
		params: { paired: true, srna: false },
		canonical: '{"paired":true,"srna":false}',
		key: "19ae437da75d346456d1eae578627072d52f0599bc7119e625218dc940494238",
	},
	{
		name: "null",
		params: { subtraction: null },
		canonical: '{"subtraction":null}',
		key: "4d4a58a71ffdc46857a17e645628cee55b8c7c809326b19cc81e6e496179d90f",
	},
	{
		name: "nested objects and arrays",
		params: { list: [1, "two", float(3.5)], outer: { b: 2, a: 1 } },
		canonical: '{"list":[1,"two",3.5],"outer":{"a":1,"b":2}}',
		key: "48dbcb67b46f0e816c9a9bf59afbd0b69613ca06a8ca76f9c196941f5c0a04af",
	},
	{
		name: "keys sorted by code point",
		params: { z: 1, a: 2, M: 3, _: 4, "0": 5 },
		canonical: '{"0":5,"M":3,"_":4,"a":2,"z":1}',
		key: "05759393af8880500bb81705123efddb9a2fb4d29463cde2f6b917b1de572b55",
	},
	{
		name: "a non-ascii value, escaped as lowercase \\uXXXX",
		params: { name: "café naïve" },
		canonical: '{"name":"caf\\u00e9 na\\u00efve"}',
		key: "ea7131f7fa8c5eac6a5c629308dd6aa11ffb103c2c7d6b45c3ac60d8e902c4ea",
	},
	{
		name: "an astral value, escaped as a surrogate pair",
		params: { name: "genome 🧬" },
		canonical: '{"name":"genome \\ud83e\\uddec"}',
		key: "b907c6d88a86d62568e730e01aaf02711dfb4eb52252645eb9de7235d655c706",
	},
	{
		name: "DEL and a control character, both escaped",
		params: { name: "a\u007fb\u0001c" },
		canonical: '{"name":"a\\u007fb\\u0001c"}',
		key: "65547ce6f25cfc392a391991c4e360a323821645b73cb6bcdd22a5236e702e59",
	},
	{
		name: "quote, backslash, newline and tab shortcuts",
		params: { name: 'quote " backslash \\ newline \n tab \t' },
		canonical: '{"name":"quote \\" backslash \\\\ newline \\n tab \\t"}',
		key: "abca123dfb338ce500de731f01cff2e0d6dfd563bee38cdefa874cf5af5b5264",
	},
	{
		name: "a full trimmed-reads param set",
		params: {
			kind: "trimmed_reads",
			workflow: "nuvs",
			workflow_version: "3.2.1",
			parent_id: 42,
			tool_name: "skewer",
			tool_version: "0.2.2",
			min_length: 20,
			mode: "pe",
			end_quality: 20,
			max_error_rate: float(0.1),
			max_indel_rate: float(0.03),
			mean_quality: 25,
		},
		canonical:
			'{"end_quality":20,"kind":"trimmed_reads","max_error_rate":0.1,"max_indel_rate":0.03,"mean_quality":25,"min_length":20,"mode":"pe","parent_id":42,"tool_name":"skewer","tool_version":"0.2.2","workflow":"nuvs","workflow_version":"3.2.1"}',
		key: "281c27841041d174ac635364d404ad98001339aa7732a954798a329eaf47503e",
	},
];

describe("canonicalizeCacheParams", () => {
	it.each(GOLDENS)("matches Python for $name", ({ params, canonical }) => {
		expect(canonicalizeCacheParams(params)).toBe(canonical);
	});
});

describe("deriveCacheKey", () => {
	it.each(GOLDENS)("matches Python for $name", ({ params, key }) => {
		expect(deriveCacheKey(params)).toBe(key);
	});

	it("is insensitive to the order keys were written in", () => {
		expect(deriveCacheKey({ a: 1, b: 2 })).toBe(deriveCacheKey({ b: 2, a: 1 }));
	});

	it("distinguishes an integral float from the same integer", () => {
		expect(deriveCacheKey({ rate: float(1.0) })).not.toBe(
			deriveCacheKey({ rate: 1 }),
		);
	});
});

describe("rejections", () => {
	it("rejects a non-ascii key rather than guessing at Python's ordering", () => {
		expect(() => canonicalizeCacheParams({ café: 1 })).toThrow(CacheParamError);
	});

	it("rejects an unmarked fractional number, pointing at float()", () => {
		expect(() => canonicalizeCacheParams({ rate: 0.1 })).toThrow(
			/must be wrapped in float\(\)/,
		);
	});

	it("rejects an integer beyond exact representation", () => {
		expect(() =>
			canonicalizeCacheParams({ count: Number.MAX_SAFE_INTEGER + 2 }),
		).toThrow(CacheParamError);
	});

	it.each<[string, number]>([
		["too large", 1e16],
		["too small", 1e-5],
	])("rejects a float Python would format differently (%s)", (_name, value) => {
		expect(() => canonicalizeCacheParams({ value: float(value) })).toThrow(
			/format numbers of this magnitude differently/,
		);
	});

	it.each<[string, number]>([
		["NaN", Number.NaN],
		["Infinity", Number.POSITIVE_INFINITY],
	])("rejects the non-finite number %s", (_name, value) => {
		expect(() => canonicalizeCacheParams({ value: float(value) })).toThrow(
			CacheParamError,
		);
	});

	it("accepts zero as a float, which is inside the exact band", () => {
		expect(canonicalizeCacheParams({ value: float(0) })).toBe('{"value":0.0}');
	});

	it("derives a different key for negative and positive zero", () => {
		expect(deriveCacheKey({ value: float(-0) })).not.toBe(
			deriveCacheKey({ value: float(0) }),
		);
	});
});
