version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pytest:
        patterns:
          - "pytest*"
      sentry:
        patterns:
          - "sentry-sdk"
          - "structlog-sentry"
      postgres:
        patterns:
          - "sqlalchemy"
          - "alembic"
          - "asyncpg"
      aiohttp:
        patterns:
          - "aiohttp"
          - "aiohttp-pydantic"
    ignore:
      - dependency-name: "pydantic"
        versions: [">=2.0.0"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
