name: Setup
description: Install pnpm and Node.js, and install dependencies.

runs:
    using: composite
    steps:
        - name: Setup pnpm
          uses: pnpm/action-setup@v6
        - name: Setup NodeJS
          uses: actions/setup-node@v6
          with:
              node-version-file: .nvmrc
              cache: pnpm
        - name: Install
          shell: bash
          run: pnpm install --frozen-lockfile
