kind: pipeline
name: server

steps:
  - name: install
    image: python:3.6-stretch
    commands:
      - wget -q https://github.com/relipmoc/skewer/archive/0.2.2.tar.gz
      - tar -xvf 0.2.2.tar.gz
      - cd skewer-0.2.2
      - make
      - mv skewer /usr/local/bin
      - cd ..
      - rm -r skewer-0.2.2
      - wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.5.zip
      - unzip fastqc_v0.11.5.zip
      - cp -rv FastQC /opt
      - chmod ugo+x /opt/FastQC/fastqc
      - cd /usr/local/bin
      - ln -s /opt/FastQC/fastqc
      - cd ~
  - name: test
    image: python:3.6-stretch
    commands:
      - pip install -r requirements.txt
      - pytest --aiohttp-loop uvloop --cov --cov-report xml

services:
  - name: db
    image: mongodb-3.6

---
kind: pipeline
name: client

steps:
  - name: test
    image: node:10-alpine
    commands:
      - cd client
      - npm i
      - npx jest --coverage

---
kind: pipeline
name: build

steps:
  - name: client
    image: node:10-alpine
    commands:
      - cd client
      - npm i
      - npx weback --config webpack.production.config.babel.js

  - name: server
  - image: python:3.6-alpine
      - mkdir gh_build
      - mkdir gh_build/virtool
      - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
      - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); print(flags&os.O_NONBLOCK);'
      - python setup.py build
      - cp -rv build/exe.linux-x86_64-3.6/* gh_build/virtool
      - cd gh_build
      - tar -cvzf virtool.tar.gz virtool
      - tar -tvf virtool.tar.gz

depends_on:
  - server
  - client
