kind: pipeline
name: server

steps:
  - name: install
    image: python:3.6-stretch
    commands:
      - apt-get update
      - apt-get install unzip
      - wget -q https://github.com/relipmoc/skewer/archive/0.2.2.tar.gz
      - tar -xvf 0.2.2.tar.gz
      - cd skewer-0.2.2
      - make
      - mv skewer /usr/local/bin
      - cd ..
      - rm -r skewer-0.2.2
      - wget -q https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.5.zip
      - unzip -o fastqc_v0.11.5.zip
      - cp -rv FastQC /opt
      - chmod ugo+x /opt/FastQC/fastqc
      - cd /usr/local/bin
      - ln -s /opt/FastQC/fastqc
      - cd ~
      - wget -q https://github.com/BenLangmead/bowtie2/releases/download/v2.3.2/bowtie2-2.3.2-legacy-linux-x86_64.zip
      - unzip -o bowtie2-2.3.2-legacy-linux-x86_64.zip
      - cp -r bowtie2-2.3.2-legacy /opt/bowtie2
      - cd /usr/local/bin
      - for FILE in /opt/bowtie2/bowtie*; do ln -s $FILE; done
      - cd ~
      - wget -q http://spades.bioinf.spbau.ru/release3.11.1/SPAdes-3.11.1-Linux.tar.gz
      - tar -xf SPAdes-3.11.1-Linux.tar.gz
      - cp -r SPAdes-3.11.1-Linux /opt/spades
      - cd /usr/local/bin
      - ln -s /opt/spades/bin/spades.py
      - cd ~
      - wget -q http://eddylab.org/software/hmmer3/3.1b2/hmmer-3.1b2-linux-intel-x86_64.tar.gz
      - tar -xf hmmer-3.1b2-linux-intel-x86_64.tar.gz
      - cp -r hmmer-3.1b2-linux-intel-x86_64 /opt/hmmer
      - cd /usr/local/bin
      - for FILE in /opt/hmmer/binaries/*; do ln -s $FILE; done

  - name: test
    image: python:3.6-stretch
    commands:
      - pip install -r requirements.txt
      - ls
      - pytest --aiohttp-loop uvloop --cov --cov-report xml

services:
  - name: db
    image: mongo:3.6-stretch

---
kind: pipeline
name: client

steps:
  - name: test
    image: node:10-alpine
    commands:
      - cd client
      - npm i
      - npx jest --coverage

---
kind: pipeline
name: build

steps:
  - name: client
    image: node:10-alpine
    commands:
      - cd client
      - npm i
      - npx weback --config webpack.production.config.babel.js

  - name: server
    image: python:3.6-stretch
    commands:
      - pip install -r requirements.txt
      - mkdir gh_build
      - mkdir gh_build/virtool
      - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
      - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); print(flags&os.O_NONBLOCK);'
      - python setup.py build
      - cp -rv build/exe.linux-x86_64-3.6/* gh_build/virtool
      - cd gh_build
      - tar -cvzf virtool.tar.gz virtool
      - tar -tvf virtool.tar.gz

depends_on:
  - server
  - client
