//! `round_half_even` against a table generated by Python's built-in `round`.
//!
//! The expectations in `fixtures/rounding.jsonl` came out of CPython's
//! built-in `round`. **Never edit a case to match this implementation's
//! output.** That converts a caught divergence into a permanent one, and the
//! whole point of the fixture is that the two agree on every value the stored
//! blob can hold.

use std::fs::read_to_string;

use quality_core::round_half_even;
use serde::Deserialize;

#[derive(Deserialize)]
struct Case {
    value: f64,
    digits: u32,
    expected: f64,
}

#[test]
fn matches_python_round_on_every_case() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/rounding.jsonl");
    let text = read_to_string(path).expect("rounding fixture is readable");

    let cases: Vec<Case> = text
        .lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| serde_json::from_str(line).expect("case parses"))
        .collect();

    assert!(cases.len() > 2000, "fixture is suspiciously small");

    for case in &cases {
        let actual = round_half_even(case.value, case.digits);

        /* Compared by bits rather than by `==`, which would let a sign
         * disagreement on zero through: Python's `round(-0.0001, 2)` is `-0.0`
         * and `0.0 == -0.0`. */
        assert_eq!(
            actual.to_bits(),
            case.expected.to_bits(),
            "round({}, {}) is {}, Python says {}",
            case.value,
            case.digits,
            actual,
            case.expected
        );
    }
}
