async def test_get(spawn_client):
    client = await spawn_client(authorize=True)

    resp = await client.get("/api/genbank/NC_016574.1")

    assert resp.status == 200

    assert await resp.json() == {
        "accession": "NC_016574.1",
        "host": "Sida rhomboidea",
        "definition": "Abutilon mosaic Brazil virus DNA-A, complete genome.",
        "sequence": "ACCGGATGGCCGCGCGATTTTCCCCCCCCCACGTGGCGCTCTCGTATCCGCGCGATCTCCTTTCGCTTCCCCCCCCGCGCGCGTCTATCTCCTTTAAT"
                    "TTGAATTAAAGGAATTAACTTTCGTTCCGACCAATGATAATGCGCCTGACTAGCTTAGATAACTGTGAAAGACTTGGTCCCTAAGTTGTTGATTAACG"
                    "GCTATAAATTAAAGGAAGACCGGGTAGGGTCTTCAATTCAAGATGCCTAAGCGGGATGCCCCGTGGCGCCTGATGGCGGGAACTTCCAAGGTTGGCCG"
                    "TTTATCCAACACCGCTCCTCGTGGAGGTTCTGGGCCTAGGTCCAACAAGGCCAATGAGTGGGTCAACAGACCCATGTACAGGAAGCCCAGGATATACC"
                    "GGGCCTTCAGAACTCCAGATGTCCCTCGAGGGTGTGAAGGGCCATGCAAGGTCCAGTCCTATGAACAGCGACATGATATCTCTCATGTCGGTAAGGTT"
                    "ATGTGTATATCTGATGTCACCCGAGGTAATGGTATTACTCACCGTGTCGGTAAGCGTTTCTGCGTTAAGTCTGTGTATATTTTAGGGAAGATATGGAT"
                    "GGACGAGAATATCAAGCTCAAGAACCACACGAACAGTGTTATGTTCTGGTTGGTCAGGGACCGTAGACCGTATGGCACACCAATGGACTTTGGCCAGG"
                    "TCTTCAACATGTTTGACAACGAGCCCAGCACTGCTACGGTTAAGAACGATCTACGCGATCGTTATCAGGTCATGCACAAGTTCTATGCCAAGGTCACT"
                    "GGCGGTCAGTATGCCAGCAATGAACAGGCTCTGGTCAAGAGGTTCTGGAAGGTCAACAATCATGTGGTGTATAATCACCAGGAGGCTGGGAAGTACGA"
                    "GAATCACACGGAGAACGCACTCCTATTGTACATGGCATGTACTCATGCCTCTAACCCTGTGTATGCAACGCTTAAGATTCGGATCTACTTTTACGATT"
                    "CGATCATGAATTAATAAAATTTGAATTTTATTACGTGGTTTTCAAGTACATAGCTGACATAAGATTTGTCTGTTGCGAAACGCACAGCTCTGATTACA"
                    "TTGTTAAGCGTAATTACTCCTAATCGGTCTAAGTAAAGCATGACTAAGTGTCTAAACCTAGTCAAATAAGTTGACCCAGAAGCTGTCAGAGAAGTCGT"
                    "CCAGACTTGGAAGTTCAGGAATGCCTTGTGGAGACCCAATGCTCTCCTGAGGTTGTGGTTGAACCTTATCTGGATGTGGTACACTCTTGTCCGAGTGT"
                    "ACGGTGGATCCTCTACCCTGATTATCTTGAAATACAGGGGATTTGTTATCTCCCAGATATAGACGCCATTCTCTGCCTGACGTGCAGTGATGAGTTCC"
                    "CCTGTGCGTGAATCCATGGCCCGTGCAGTTGAGATGCTGGTAAATGGAGCAGCCGCAGTCCAGATCAATTCGTCGTCGCCTGATTGCTCTCTTCTTCG"
                    "CAATCCTGTGTCGTGGTTTGATAGAGGGGGGAGTTGAGGAAGATGAATTTAGCATTGTTGATTGTCCAGGCTTTAAGTGATGAGTTTTCCTGCTTCTC"
                    "CAGGAAATCTTTATAGCTGGCCCCCTCTCCAGGATTGCATAGCACGATTGATGGGATACCCCCTTTAATTTGAACAGGCTTGCCGTACTTGCAATTGG"
                    "ACTGCCAATCTTTTTGAGCACCAATCAATTCCTTCCAGTGCTTTAGCTTTAGGTATTGCGGGCTGACATCATCGATGACGTTATACTCAACTTGATTT"
                    "GAGTAGACCCGGGAATTGAAATCTAAATGGCCACTCAAGTAATTATGTGGGCCTAATGCTCTAGCCCACATCGTCTTACCAGTTCGAGAATCACCTTC"
                    "AACTATTATACTTATGGGCCTAACAGGCCGCGCAGCGGAACTTCTTCCAAAATAATCATCCGCCCACTCTTGCATCTCTTCAGGAACGTTAGTGAACG"
                    "ATGAGAGGGGAAACGGAGGAGCCCATGGTTCCGGAGCCCTCTTAAAGATCAATTCCAGGTTGGAGCGGATGTTATGGTGTTGGACGATGAAGGTCTTT"
                    "GGATCTCCGGCTCTGATAATTTCAAGAGCCTCTGAAACACCTCCTGCATTGACGGCGTTGTGGAAGACATCGTCCTTGTTGGCCTTGGTACCCCCAGA"
                    "CACCTTGTATTGTCCGGATTCACAATAGTCACCATCTTTGGTGATGTAGTTCCTGACGGCAACGGTGTCTTTGGCAGCTTGCACGTTCGGGTGAAAAC"
                    "TGGCTGACCGTCTGGGGTGAGTAAGGTCGAAAAATCTTGCATCCCTGATGTTGGACTTTCCTGATAATTGTATGAGACAGTGTAGATGGGGGTGTCCA"
                    "TCGGAGTGTTCCTCACGTGCGACTCTGATATAGGTAGGTTGGACGACTGTCCATGAAAGGGCTTGAAGCATTTGAAGAGCTTCATCTTTGGGTATGTC"
                    "GCAACGGGGATATGTGAGGAATATGTTTCTGGCTTGTAATCTAAAAGAATGGGAAAGTCGGGGCATTTTTGTAAATTTCTGTTAGTGGCTCCAGGGGA"
                    "GCTCTCAACTTCTGTGCTATTTGCTGGAGTCTTGGAGCCTCATTTATACTAGAAGTCTCTAATGCTCCTAGGGGGCACGTGGCGGCCATCCGTATAAT"
                    "ATT"
        }
