/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as EventsRouteImport } from './routes/events'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdministrationRouteRouteImport } from './routes/_authenticated/administration/route'
import { Route as AuthenticatedHmmsRouteImport } from './routes/_authenticated/hmms'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedRefsRouteRouteImport } from './routes/_authenticated/refs/route'
import { Route as AuthenticatedSamplesRouteImport } from './routes/_authenticated/samples'
import { Route as AuthenticatedSubtractionsRouteImport } from './routes/_authenticated/subtractions'
import { Route as HealthLiveRouteImport } from './routes/health/live'
import { Route as HealthReadyRouteImport } from './routes/health/ready'
import { Route as UploadsUploadIdRouteImport } from './routes/uploads_.$uploadId'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedAccountApiRouteImport } from './routes/_authenticated/account/api'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account/profile'
import { Route as AuthenticatedAdministrationIndexRouteImport } from './routes/_authenticated/administration/index'
import { Route as AuthenticatedAdministrationGroupsRouteImport } from './routes/_authenticated/administration/groups'
import { Route as AuthenticatedAdministrationSettingsRouteImport } from './routes/_authenticated/administration/settings'
import { Route as AuthenticatedHmmsIndexRouteImport } from './routes/_authenticated/hmms/index'
import { Route as AuthenticatedHmmsHmmIdRouteImport } from './routes/_authenticated/hmms/$hmmId'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs/index'
import { Route as AuthenticatedJobsJobIdRouteImport } from './routes/_authenticated/jobs/$jobId'
import { Route as AuthenticatedRefsIndexRouteImport } from './routes/_authenticated/refs/index'
import { Route as AuthenticatedRefsRefIdRouteRouteImport } from './routes/_authenticated/refs/$refId/route'
import { Route as AuthenticatedRefsSettingsRouteImport } from './routes/_authenticated/refs/settings'
import { Route as AuthenticatedSamplesIndexRouteImport } from './routes/_authenticated/samples/index'
import { Route as AuthenticatedSamplesSampleIdRouteImport } from './routes/_authenticated/samples/$sampleId'
import { Route as AuthenticatedSamplesCreateRouteImport } from './routes/_authenticated/samples/create'
import { Route as AuthenticatedSamplesFilesRouteImport } from './routes/_authenticated/samples/files'
import { Route as AuthenticatedSamplesLabelsRouteImport } from './routes/_authenticated/samples/labels'
import { Route as AuthenticatedSamplesSettingsRouteImport } from './routes/_authenticated/samples/settings'
import { Route as AuthenticatedSubtractionsIndexRouteImport } from './routes/_authenticated/subtractions/index'
import { Route as AuthenticatedSubtractionsSubtractionIdRouteImport } from './routes/_authenticated/subtractions/$subtractionId'
import { Route as AuthenticatedSubtractionsFilesRouteImport } from './routes/_authenticated/subtractions/files'
import { Route as AnalysesDocumentsDocumentRouteImport } from './routes/analyses.documents.$document'
import { Route as OtusOtuIdFastaRouteImport } from './routes/otus.$otuId.fasta'
import { Route as AuthenticatedAdministrationUsersIndexRouteImport } from './routes/_authenticated/administration/users/index'
import { Route as AuthenticatedAdministrationUsersUserIdRouteImport } from './routes/_authenticated/administration/users/$userId'
import { Route as AuthenticatedRefsRefIdIndexRouteImport } from './routes/_authenticated/refs/$refId/index'
import { Route as AuthenticatedRefsRefIdManageRouteImport } from './routes/_authenticated/refs/$refId/manage'
import { Route as AuthenticatedRefsRefIdSettingsRouteImport } from './routes/_authenticated/refs/$refId/settings'
import { Route as AuthenticatedSamplesSampleIdIndexRouteImport } from './routes/_authenticated/samples/$sampleId/index'
import { Route as AuthenticatedSamplesSampleIdAnalysesRouteImport } from './routes/_authenticated/samples/$sampleId/analyses'
import { Route as AuthenticatedSamplesSampleIdFilesRouteImport } from './routes/_authenticated/samples/$sampleId/files'
import { Route as AuthenticatedSamplesSampleIdGeneralRouteImport } from './routes/_authenticated/samples/$sampleId/general'
import { Route as AuthenticatedSamplesSampleIdQualityRouteImport } from './routes/_authenticated/samples/$sampleId/quality'
import { Route as AuthenticatedSamplesSampleIdRightsRouteImport } from './routes/_authenticated/samples/$sampleId/rights'
import { Route as IndexesIndexIdFilesFilenameRouteImport } from './routes/indexes.$indexId.files.$filename'
import { Route as SamplesSampleIdReadsFilenameRouteImport } from './routes/samples.$sampleId.reads.$filename'
import { Route as SubtractionsSubtractionIdFilesFilenameRouteImport } from './routes/subtractions.$subtractionId.files.$filename'
import { Route as AuthenticatedRefsRefIdIndexesIndexRouteImport } from './routes/_authenticated/refs/$refId/indexes/index'
import { Route as AuthenticatedRefsRefIdIndexesIndexIdRouteImport } from './routes/_authenticated/refs/$refId/indexes/$indexId'
import { Route as AuthenticatedRefsRefIdOtusIndexRouteImport } from './routes/_authenticated/refs/$refId/otus/index'
import { Route as AuthenticatedRefsRefIdOtusOtuIdRouteRouteImport } from './routes/_authenticated/refs/$refId/otus/$otuId/route'
import { Route as AuthenticatedSamplesSampleIdAnalysesIndexRouteImport } from './routes/_authenticated/samples/$sampleId/analyses/index'
import { Route as AuthenticatedSamplesSampleIdAnalysesAnalysisIdRouteImport } from './routes/_authenticated/samples/$sampleId/analyses/$analysisId'
import { Route as OtusOtuIdIsolatesIsolateIdFastaRouteImport } from './routes/otus.$otuId.isolates.$isolateId.fasta'
import { Route as AuthenticatedRefsRefIdOtusOtuIdIndexRouteImport } from './routes/_authenticated/refs/$refId/otus/$otuId/index'
import { Route as AuthenticatedRefsRefIdOtusOtuIdHistoryRouteImport } from './routes/_authenticated/refs/$refId/otus/$otuId/history'
import { Route as AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRouteImport } from './routes/_authenticated/refs/$refId/otus/$otuId/isolates/route'
import { Route as AuthenticatedRefsRefIdOtusOtuIdSegmentsRouteImport } from './routes/_authenticated/refs/$refId/otus/$otuId/segments'
import { Route as AuthenticatedRefsRefIdOtusOtuIdIsolatesIndexRouteImport } from './routes/_authenticated/refs/$refId/otus/$otuId/isolates/index'
import { Route as AuthenticatedRefsRefIdOtusOtuIdIsolatesIsolateIdRouteImport } from './routes/_authenticated/refs/$refId/otus/$otuId/isolates/$isolateId'
import { Route as OtusOtuIdIsolatesIsolateIdSequencesSequenceIdFastaRouteImport } from './routes/otus.$otuId.isolates.$isolateId.sequences.$sequenceId.fasta'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdministrationRouteRoute =
  AuthenticatedAdministrationRouteRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHmmsRoute = AuthenticatedHmmsRouteImport.update({
  id: '/hmms',
  path: '/hmms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRefsRouteRoute = AuthenticatedRefsRouteRouteImport.update({
  id: '/refs',
  path: '/refs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSamplesRoute = AuthenticatedSamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSubtractionsRoute =
  AuthenticatedSubtractionsRouteImport.update({
    id: '/subtractions',
    path: '/subtractions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const HealthLiveRoute = HealthLiveRouteImport.update({
  id: '/health/live',
  path: '/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthReadyRoute = HealthReadyRouteImport.update({
  id: '/health/ready',
  path: '/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsUploadIdRoute = UploadsUploadIdRouteImport.update({
  id: '/uploads_/$uploadId',
  path: '/uploads/$uploadId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountApiRoute = AuthenticatedAccountApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthenticatedAccountRoute,
} as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdministrationIndexRoute =
  AuthenticatedAdministrationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdministrationRouteRoute,
  } as any)
const AuthenticatedAdministrationGroupsRoute =
  AuthenticatedAdministrationGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthenticatedAdministrationRouteRoute,
  } as any)
const AuthenticatedAdministrationSettingsRoute =
  AuthenticatedAdministrationSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdministrationRouteRoute,
  } as any)
const AuthenticatedHmmsIndexRoute = AuthenticatedHmmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedHmmsRoute,
} as any)
const AuthenticatedHmmsHmmIdRoute = AuthenticatedHmmsHmmIdRouteImport.update({
  id: '/$hmmId',
  path: '/$hmmId',
  getParentRoute: () => AuthenticatedHmmsRoute,
} as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedJobsRoute,
} as any)
const AuthenticatedJobsJobIdRoute = AuthenticatedJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AuthenticatedJobsRoute,
} as any)
const AuthenticatedRefsIndexRoute = AuthenticatedRefsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRefsRouteRoute,
} as any)
const AuthenticatedRefsRefIdRouteRoute =
  AuthenticatedRefsRefIdRouteRouteImport.update({
    id: '/$refId',
    path: '/$refId',
    getParentRoute: () => AuthenticatedRefsRouteRoute,
  } as any)
const AuthenticatedRefsSettingsRoute =
  AuthenticatedRefsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRefsRouteRoute,
  } as any)
const AuthenticatedSamplesIndexRoute =
  AuthenticatedSamplesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSamplesRoute,
  } as any)
const AuthenticatedSamplesSampleIdRoute =
  AuthenticatedSamplesSampleIdRouteImport.update({
    id: '/$sampleId',
    path: '/$sampleId',
    getParentRoute: () => AuthenticatedSamplesRoute,
  } as any)
const AuthenticatedSamplesCreateRoute =
  AuthenticatedSamplesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedSamplesRoute,
  } as any)
const AuthenticatedSamplesFilesRoute =
  AuthenticatedSamplesFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthenticatedSamplesRoute,
  } as any)
const AuthenticatedSamplesLabelsRoute =
  AuthenticatedSamplesLabelsRouteImport.update({
    id: '/labels',
    path: '/labels',
    getParentRoute: () => AuthenticatedSamplesRoute,
  } as any)
const AuthenticatedSamplesSettingsRoute =
  AuthenticatedSamplesSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSamplesRoute,
  } as any)
const AuthenticatedSubtractionsIndexRoute =
  AuthenticatedSubtractionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSubtractionsRoute,
  } as any)
const AuthenticatedSubtractionsSubtractionIdRoute =
  AuthenticatedSubtractionsSubtractionIdRouteImport.update({
    id: '/$subtractionId',
    path: '/$subtractionId',
    getParentRoute: () => AuthenticatedSubtractionsRoute,
  } as any)
const AuthenticatedSubtractionsFilesRoute =
  AuthenticatedSubtractionsFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthenticatedSubtractionsRoute,
  } as any)
const AnalysesDocumentsDocumentRoute =
  AnalysesDocumentsDocumentRouteImport.update({
    id: '/analyses/documents/$document',
    path: '/analyses/documents/$document',
    getParentRoute: () => rootRouteImport,
  } as any)
const OtusOtuIdFastaRoute = OtusOtuIdFastaRouteImport.update({
  id: '/otus/$otuId/fasta',
  path: '/otus/$otuId/fasta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdministrationUsersIndexRoute =
  AuthenticatedAdministrationUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdministrationRouteRoute,
  } as any)
const AuthenticatedAdministrationUsersUserIdRoute =
  AuthenticatedAdministrationUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdministrationRouteRoute,
  } as any)
const AuthenticatedRefsRefIdIndexRoute =
  AuthenticatedRefsRefIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRefsRefIdRouteRoute,
  } as any)
const AuthenticatedRefsRefIdManageRoute =
  AuthenticatedRefsRefIdManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => AuthenticatedRefsRefIdRouteRoute,
  } as any)
const AuthenticatedRefsRefIdSettingsRoute =
  AuthenticatedRefsRefIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRefsRefIdRouteRoute,
  } as any)
const AuthenticatedSamplesSampleIdIndexRoute =
  AuthenticatedSamplesSampleIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSamplesSampleIdRoute,
  } as any)
const AuthenticatedSamplesSampleIdAnalysesRoute =
  AuthenticatedSamplesSampleIdAnalysesRouteImport.update({
    id: '/analyses',
    path: '/analyses',
    getParentRoute: () => AuthenticatedSamplesSampleIdRoute,
  } as any)
const AuthenticatedSamplesSampleIdFilesRoute =
  AuthenticatedSamplesSampleIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthenticatedSamplesSampleIdRoute,
  } as any)
const AuthenticatedSamplesSampleIdGeneralRoute =
  AuthenticatedSamplesSampleIdGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSamplesSampleIdRoute,
  } as any)
const AuthenticatedSamplesSampleIdQualityRoute =
  AuthenticatedSamplesSampleIdQualityRouteImport.update({
    id: '/quality',
    path: '/quality',
    getParentRoute: () => AuthenticatedSamplesSampleIdRoute,
  } as any)
const AuthenticatedSamplesSampleIdRightsRoute =
  AuthenticatedSamplesSampleIdRightsRouteImport.update({
    id: '/rights',
    path: '/rights',
    getParentRoute: () => AuthenticatedSamplesSampleIdRoute,
  } as any)
const IndexesIndexIdFilesFilenameRoute =
  IndexesIndexIdFilesFilenameRouteImport.update({
    id: '/indexes/$indexId/files/$filename',
    path: '/indexes/$indexId/files/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)
const SamplesSampleIdReadsFilenameRoute =
  SamplesSampleIdReadsFilenameRouteImport.update({
    id: '/samples/$sampleId/reads/$filename',
    path: '/samples/$sampleId/reads/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)
const SubtractionsSubtractionIdFilesFilenameRoute =
  SubtractionsSubtractionIdFilesFilenameRouteImport.update({
    id: '/subtractions/$subtractionId/files/$filename',
    path: '/subtractions/$subtractionId/files/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRefsRefIdIndexesIndexRoute =
  AuthenticatedRefsRefIdIndexesIndexRouteImport.update({
    id: '/indexes/',
    path: '/indexes/',
    getParentRoute: () => AuthenticatedRefsRefIdRouteRoute,
  } as any)
const AuthenticatedRefsRefIdIndexesIndexIdRoute =
  AuthenticatedRefsRefIdIndexesIndexIdRouteImport.update({
    id: '/indexes/$indexId',
    path: '/indexes/$indexId',
    getParentRoute: () => AuthenticatedRefsRefIdRouteRoute,
  } as any)
const AuthenticatedRefsRefIdOtusIndexRoute =
  AuthenticatedRefsRefIdOtusIndexRouteImport.update({
    id: '/otus/',
    path: '/otus/',
    getParentRoute: () => AuthenticatedRefsRefIdRouteRoute,
  } as any)
const AuthenticatedRefsRefIdOtusOtuIdRouteRoute =
  AuthenticatedRefsRefIdOtusOtuIdRouteRouteImport.update({
    id: '/otus/$otuId',
    path: '/otus/$otuId',
    getParentRoute: () => AuthenticatedRefsRefIdRouteRoute,
  } as any)
const AuthenticatedSamplesSampleIdAnalysesIndexRoute =
  AuthenticatedSamplesSampleIdAnalysesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSamplesSampleIdAnalysesRoute,
  } as any)
const AuthenticatedSamplesSampleIdAnalysesAnalysisIdRoute =
  AuthenticatedSamplesSampleIdAnalysesAnalysisIdRouteImport.update({
    id: '/$analysisId',
    path: '/$analysisId',
    getParentRoute: () => AuthenticatedSamplesSampleIdAnalysesRoute,
  } as any)
const OtusOtuIdIsolatesIsolateIdFastaRoute =
  OtusOtuIdIsolatesIsolateIdFastaRouteImport.update({
    id: '/otus/$otuId/isolates/$isolateId/fasta',
    path: '/otus/$otuId/isolates/$isolateId/fasta',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRefsRefIdOtusOtuIdIndexRoute =
  AuthenticatedRefsRefIdOtusOtuIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRefsRefIdOtusOtuIdRouteRoute,
  } as any)
const AuthenticatedRefsRefIdOtusOtuIdHistoryRoute =
  AuthenticatedRefsRefIdOtusOtuIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedRefsRefIdOtusOtuIdRouteRoute,
  } as any)
const AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRoute =
  AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRouteImport.update({
    id: '/isolates',
    path: '/isolates',
    getParentRoute: () => AuthenticatedRefsRefIdOtusOtuIdRouteRoute,
  } as any)
const AuthenticatedRefsRefIdOtusOtuIdSegmentsRoute =
  AuthenticatedRefsRefIdOtusOtuIdSegmentsRouteImport.update({
    id: '/segments',
    path: '/segments',
    getParentRoute: () => AuthenticatedRefsRefIdOtusOtuIdRouteRoute,
  } as any)
const AuthenticatedRefsRefIdOtusOtuIdIsolatesIndexRoute =
  AuthenticatedRefsRefIdOtusOtuIdIsolatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRoute,
  } as any)
const AuthenticatedRefsRefIdOtusOtuIdIsolatesIsolateIdRoute =
  AuthenticatedRefsRefIdOtusOtuIdIsolatesIsolateIdRouteImport.update({
    id: '/$isolateId',
    path: '/$isolateId',
    getParentRoute: () => AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRoute,
  } as any)
const OtusOtuIdIsolatesIsolateIdSequencesSequenceIdFastaRoute =
  OtusOtuIdIsolatesIsolateIdSequencesSequenceIdFastaRouteImport.update({
    id: '/otus/$otuId/isolates/$isolateId/sequences/$sequenceId/fasta',
    path: '/otus/$otuId/isolates/$isolateId/sequences/$sequenceId/fasta',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/monitoring': typeof MonitoringRoute
  '/setup': typeof SetupRoute
  '/uploads': typeof UploadsRoute
  '/administration': typeof AuthenticatedAdministrationRouteRouteWithChildren
  '/refs': typeof AuthenticatedRefsRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/hmms': typeof AuthenticatedHmmsRouteWithChildren
  '/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/samples': typeof AuthenticatedSamplesRouteWithChildren
  '/subtractions': typeof AuthenticatedSubtractionsRouteWithChildren
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/uploads/$uploadId': typeof UploadsUploadIdRoute
  '/refs/$refId': typeof AuthenticatedRefsRefIdRouteRouteWithChildren
  '/account/api': typeof AuthenticatedAccountApiRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/administration/groups': typeof AuthenticatedAdministrationGroupsRoute
  '/administration/settings': typeof AuthenticatedAdministrationSettingsRoute
  '/hmms/$hmmId': typeof AuthenticatedHmmsHmmIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/refs/settings': typeof AuthenticatedRefsSettingsRoute
  '/samples/$sampleId': typeof AuthenticatedSamplesSampleIdRouteWithChildren
  '/samples/create': typeof AuthenticatedSamplesCreateRoute
  '/samples/files': typeof AuthenticatedSamplesFilesRoute
  '/samples/labels': typeof AuthenticatedSamplesLabelsRoute
  '/samples/settings': typeof AuthenticatedSamplesSettingsRoute
  '/subtractions/$subtractionId': typeof AuthenticatedSubtractionsSubtractionIdRoute
  '/subtractions/files': typeof AuthenticatedSubtractionsFilesRoute
  '/analyses/documents/$document': typeof AnalysesDocumentsDocumentRoute
  '/otus/$otuId/fasta': typeof OtusOtuIdFastaRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/administration/': typeof AuthenticatedAdministrationIndexRoute
  '/hmms/': typeof AuthenticatedHmmsIndexRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/refs/': typeof AuthenticatedRefsIndexRoute
  '/samples/': typeof AuthenticatedSamplesIndexRoute
  '/subtractions/': typeof AuthenticatedSubtractionsIndexRoute
  '/administration/users/$userId': typeof AuthenticatedAdministrationUsersUserIdRoute
  '/refs/$refId/manage': typeof AuthenticatedRefsRefIdManageRoute
  '/refs/$refId/settings': typeof AuthenticatedRefsRefIdSettingsRoute
  '/samples/$sampleId/analyses': typeof AuthenticatedSamplesSampleIdAnalysesRouteWithChildren
  '/samples/$sampleId/files': typeof AuthenticatedSamplesSampleIdFilesRoute
  '/samples/$sampleId/general': typeof AuthenticatedSamplesSampleIdGeneralRoute
  '/samples/$sampleId/quality': typeof AuthenticatedSamplesSampleIdQualityRoute
  '/samples/$sampleId/rights': typeof AuthenticatedSamplesSampleIdRightsRoute
  '/indexes/$indexId/files/$filename': typeof IndexesIndexIdFilesFilenameRoute
  '/samples/$sampleId/reads/$filename': typeof SamplesSampleIdReadsFilenameRoute
  '/subtractions/$subtractionId/files/$filename': typeof SubtractionsSubtractionIdFilesFilenameRoute
  '/administration/users/': typeof AuthenticatedAdministrationUsersIndexRoute
  '/refs/$refId/': typeof AuthenticatedRefsRefIdIndexRoute
  '/samples/$sampleId/': typeof AuthenticatedSamplesSampleIdIndexRoute
  '/refs/$refId/otus/$otuId': typeof AuthenticatedRefsRefIdOtusOtuIdRouteRouteWithChildren
  '/refs/$refId/indexes/$indexId': typeof AuthenticatedRefsRefIdIndexesIndexIdRoute
  '/samples/$sampleId/analyses/$analysisId': typeof AuthenticatedSamplesSampleIdAnalysesAnalysisIdRoute
  '/otus/$otuId/isolates/$isolateId/fasta': typeof OtusOtuIdIsolatesIsolateIdFastaRoute
  '/refs/$refId/indexes/': typeof AuthenticatedRefsRefIdIndexesIndexRoute
  '/refs/$refId/otus/': typeof AuthenticatedRefsRefIdOtusIndexRoute
  '/samples/$sampleId/analyses/': typeof AuthenticatedSamplesSampleIdAnalysesIndexRoute
  '/refs/$refId/otus/$otuId/isolates': typeof AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRouteWithChildren
  '/refs/$refId/otus/$otuId/history': typeof AuthenticatedRefsRefIdOtusOtuIdHistoryRoute
  '/refs/$refId/otus/$otuId/segments': typeof AuthenticatedRefsRefIdOtusOtuIdSegmentsRoute
  '/refs/$refId/otus/$otuId/': typeof AuthenticatedRefsRefIdOtusOtuIdIndexRoute
  '/refs/$refId/otus/$otuId/isolates/$isolateId': typeof AuthenticatedRefsRefIdOtusOtuIdIsolatesIsolateIdRoute
  '/otus/$otuId/isolates/$isolateId/sequences/$sequenceId/fasta': typeof OtusOtuIdIsolatesIsolateIdSequencesSequenceIdFastaRoute
  '/refs/$refId/otus/$otuId/isolates/': typeof AuthenticatedRefsRefIdOtusOtuIdIsolatesIndexRoute
}
export interface FileRoutesByTo {
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/monitoring': typeof MonitoringRoute
  '/setup': typeof SetupRoute
  '/uploads': typeof UploadsRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/uploads/$uploadId': typeof UploadsUploadIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/account/api': typeof AuthenticatedAccountApiRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/administration/groups': typeof AuthenticatedAdministrationGroupsRoute
  '/administration/settings': typeof AuthenticatedAdministrationSettingsRoute
  '/hmms/$hmmId': typeof AuthenticatedHmmsHmmIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/refs/settings': typeof AuthenticatedRefsSettingsRoute
  '/samples/create': typeof AuthenticatedSamplesCreateRoute
  '/samples/files': typeof AuthenticatedSamplesFilesRoute
  '/samples/labels': typeof AuthenticatedSamplesLabelsRoute
  '/samples/settings': typeof AuthenticatedSamplesSettingsRoute
  '/subtractions/$subtractionId': typeof AuthenticatedSubtractionsSubtractionIdRoute
  '/subtractions/files': typeof AuthenticatedSubtractionsFilesRoute
  '/analyses/documents/$document': typeof AnalysesDocumentsDocumentRoute
  '/otus/$otuId/fasta': typeof OtusOtuIdFastaRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/administration': typeof AuthenticatedAdministrationIndexRoute
  '/hmms': typeof AuthenticatedHmmsIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/refs': typeof AuthenticatedRefsIndexRoute
  '/samples': typeof AuthenticatedSamplesIndexRoute
  '/subtractions': typeof AuthenticatedSubtractionsIndexRoute
  '/administration/users/$userId': typeof AuthenticatedAdministrationUsersUserIdRoute
  '/refs/$refId/manage': typeof AuthenticatedRefsRefIdManageRoute
  '/refs/$refId/settings': typeof AuthenticatedRefsRefIdSettingsRoute
  '/samples/$sampleId/files': typeof AuthenticatedSamplesSampleIdFilesRoute
  '/samples/$sampleId/general': typeof AuthenticatedSamplesSampleIdGeneralRoute
  '/samples/$sampleId/quality': typeof AuthenticatedSamplesSampleIdQualityRoute
  '/samples/$sampleId/rights': typeof AuthenticatedSamplesSampleIdRightsRoute
  '/indexes/$indexId/files/$filename': typeof IndexesIndexIdFilesFilenameRoute
  '/samples/$sampleId/reads/$filename': typeof SamplesSampleIdReadsFilenameRoute
  '/subtractions/$subtractionId/files/$filename': typeof SubtractionsSubtractionIdFilesFilenameRoute
  '/administration/users': typeof AuthenticatedAdministrationUsersIndexRoute
  '/refs/$refId': typeof AuthenticatedRefsRefIdIndexRoute
  '/samples/$sampleId': typeof AuthenticatedSamplesSampleIdIndexRoute
  '/refs/$refId/indexes/$indexId': typeof AuthenticatedRefsRefIdIndexesIndexIdRoute
  '/samples/$sampleId/analyses/$analysisId': typeof AuthenticatedSamplesSampleIdAnalysesAnalysisIdRoute
  '/otus/$otuId/isolates/$isolateId/fasta': typeof OtusOtuIdIsolatesIsolateIdFastaRoute
  '/refs/$refId/indexes': typeof AuthenticatedRefsRefIdIndexesIndexRoute
  '/refs/$refId/otus': typeof AuthenticatedRefsRefIdOtusIndexRoute
  '/samples/$sampleId/analyses': typeof AuthenticatedSamplesSampleIdAnalysesIndexRoute
  '/refs/$refId/otus/$otuId/history': typeof AuthenticatedRefsRefIdOtusOtuIdHistoryRoute
  '/refs/$refId/otus/$otuId/segments': typeof AuthenticatedRefsRefIdOtusOtuIdSegmentsRoute
  '/refs/$refId/otus/$otuId': typeof AuthenticatedRefsRefIdOtusOtuIdIndexRoute
  '/refs/$refId/otus/$otuId/isolates/$isolateId': typeof AuthenticatedRefsRefIdOtusOtuIdIsolatesIsolateIdRoute
  '/otus/$otuId/isolates/$isolateId/sequences/$sequenceId/fasta': typeof OtusOtuIdIsolatesIsolateIdSequencesSequenceIdFastaRoute
  '/refs/$refId/otus/$otuId/isolates': typeof AuthenticatedRefsRefIdOtusOtuIdIsolatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/monitoring': typeof MonitoringRoute
  '/setup': typeof SetupRoute
  '/uploads': typeof UploadsRoute
  '/_authenticated/administration': typeof AuthenticatedAdministrationRouteRouteWithChildren
  '/_authenticated/refs': typeof AuthenticatedRefsRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/hmms': typeof AuthenticatedHmmsRouteWithChildren
  '/_authenticated/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/_authenticated/samples': typeof AuthenticatedSamplesRouteWithChildren
  '/_authenticated/subtractions': typeof AuthenticatedSubtractionsRouteWithChildren
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/uploads_/$uploadId': typeof UploadsUploadIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/refs/$refId': typeof AuthenticatedRefsRefIdRouteRouteWithChildren
  '/_authenticated/account/api': typeof AuthenticatedAccountApiRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/administration/groups': typeof AuthenticatedAdministrationGroupsRoute
  '/_authenticated/administration/settings': typeof AuthenticatedAdministrationSettingsRoute
  '/_authenticated/hmms/$hmmId': typeof AuthenticatedHmmsHmmIdRoute
  '/_authenticated/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/_authenticated/refs/settings': typeof AuthenticatedRefsSettingsRoute
  '/_authenticated/samples/$sampleId': typeof AuthenticatedSamplesSampleIdRouteWithChildren
  '/_authenticated/samples/create': typeof AuthenticatedSamplesCreateRoute
  '/_authenticated/samples/files': typeof AuthenticatedSamplesFilesRoute
  '/_authenticated/samples/labels': typeof AuthenticatedSamplesLabelsRoute
  '/_authenticated/samples/settings': typeof AuthenticatedSamplesSettingsRoute
  '/_authenticated/subtractions/$subtractionId': typeof AuthenticatedSubtractionsSubtractionIdRoute
  '/_authenticated/subtractions/files': typeof AuthenticatedSubtractionsFilesRoute
  '/analyses/documents/$document': typeof AnalysesDocumentsDocumentRoute
  '/otus/$otuId/fasta': typeof OtusOtuIdFastaRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/administration/': typeof AuthenticatedAdministrationIndexRoute
  '/_authenticated/hmms/': typeof AuthenticatedHmmsIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/refs/': typeof AuthenticatedRefsIndexRoute
  '/_authenticated/samples/': typeof AuthenticatedSamplesIndexRoute
  '/_authenticated/subtractions/': typeof AuthenticatedSubtractionsIndexRoute
  '/_authenticated/administration/users/$userId': typeof AuthenticatedAdministrationUsersUserIdRoute
  '/_authenticated/refs/$refId/manage': typeof AuthenticatedRefsRefIdManageRoute
  '/_authenticated/refs/$refId/settings': typeof AuthenticatedRefsRefIdSettingsRoute
  '/_authenticated/samples/$sampleId/analyses': typeof AuthenticatedSamplesSampleIdAnalysesRouteWithChildren
  '/_authenticated/samples/$sampleId/files': typeof AuthenticatedSamplesSampleIdFilesRoute
  '/_authenticated/samples/$sampleId/general': typeof AuthenticatedSamplesSampleIdGeneralRoute
  '/_authenticated/samples/$sampleId/quality': typeof AuthenticatedSamplesSampleIdQualityRoute
  '/_authenticated/samples/$sampleId/rights': typeof AuthenticatedSamplesSampleIdRightsRoute
  '/indexes/$indexId/files/$filename': typeof IndexesIndexIdFilesFilenameRoute
  '/samples/$sampleId/reads/$filename': typeof SamplesSampleIdReadsFilenameRoute
  '/subtractions/$subtractionId/files/$filename': typeof SubtractionsSubtractionIdFilesFilenameRoute
  '/_authenticated/administration/users/': typeof AuthenticatedAdministrationUsersIndexRoute
  '/_authenticated/refs/$refId/': typeof AuthenticatedRefsRefIdIndexRoute
  '/_authenticated/samples/$sampleId/': typeof AuthenticatedSamplesSampleIdIndexRoute
  '/_authenticated/refs/$refId/otus/$otuId': typeof AuthenticatedRefsRefIdOtusOtuIdRouteRouteWithChildren
  '/_authenticated/refs/$refId/indexes/$indexId': typeof AuthenticatedRefsRefIdIndexesIndexIdRoute
  '/_authenticated/samples/$sampleId/analyses/$analysisId': typeof AuthenticatedSamplesSampleIdAnalysesAnalysisIdRoute
  '/otus/$otuId/isolates/$isolateId/fasta': typeof OtusOtuIdIsolatesIsolateIdFastaRoute
  '/_authenticated/refs/$refId/indexes/': typeof AuthenticatedRefsRefIdIndexesIndexRoute
  '/_authenticated/refs/$refId/otus/': typeof AuthenticatedRefsRefIdOtusIndexRoute
  '/_authenticated/samples/$sampleId/analyses/': typeof AuthenticatedSamplesSampleIdAnalysesIndexRoute
  '/_authenticated/refs/$refId/otus/$otuId/isolates': typeof AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRouteWithChildren
  '/_authenticated/refs/$refId/otus/$otuId/history': typeof AuthenticatedRefsRefIdOtusOtuIdHistoryRoute
  '/_authenticated/refs/$refId/otus/$otuId/segments': typeof AuthenticatedRefsRefIdOtusOtuIdSegmentsRoute
  '/_authenticated/refs/$refId/otus/$otuId/': typeof AuthenticatedRefsRefIdOtusOtuIdIndexRoute
  '/_authenticated/refs/$refId/otus/$otuId/isolates/$isolateId': typeof AuthenticatedRefsRefIdOtusOtuIdIsolatesIsolateIdRoute
  '/otus/$otuId/isolates/$isolateId/sequences/$sequenceId/fasta': typeof OtusOtuIdIsolatesIsolateIdSequencesSequenceIdFastaRoute
  '/_authenticated/refs/$refId/otus/$otuId/isolates/': typeof AuthenticatedRefsRefIdOtusOtuIdIsolatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/login'
    | '/metrics'
    | '/monitoring'
    | '/setup'
    | '/uploads'
    | '/administration'
    | '/refs'
    | '/account'
    | '/hmms'
    | '/jobs'
    | '/samples'
    | '/subtractions'
    | '/health/live'
    | '/health/ready'
    | '/uploads/$uploadId'
    | '/refs/$refId'
    | '/account/api'
    | '/account/profile'
    | '/administration/groups'
    | '/administration/settings'
    | '/hmms/$hmmId'
    | '/jobs/$jobId'
    | '/refs/settings'
    | '/samples/$sampleId'
    | '/samples/create'
    | '/samples/files'
    | '/samples/labels'
    | '/samples/settings'
    | '/subtractions/$subtractionId'
    | '/subtractions/files'
    | '/analyses/documents/$document'
    | '/otus/$otuId/fasta'
    | '/account/'
    | '/administration/'
    | '/hmms/'
    | '/jobs/'
    | '/refs/'
    | '/samples/'
    | '/subtractions/'
    | '/administration/users/$userId'
    | '/refs/$refId/manage'
    | '/refs/$refId/settings'
    | '/samples/$sampleId/analyses'
    | '/samples/$sampleId/files'
    | '/samples/$sampleId/general'
    | '/samples/$sampleId/quality'
    | '/samples/$sampleId/rights'
    | '/indexes/$indexId/files/$filename'
    | '/samples/$sampleId/reads/$filename'
    | '/subtractions/$subtractionId/files/$filename'
    | '/administration/users/'
    | '/refs/$refId/'
    | '/samples/$sampleId/'
    | '/refs/$refId/otus/$otuId'
    | '/refs/$refId/indexes/$indexId'
    | '/samples/$sampleId/analyses/$analysisId'
    | '/otus/$otuId/isolates/$isolateId/fasta'
    | '/refs/$refId/indexes/'
    | '/refs/$refId/otus/'
    | '/samples/$sampleId/analyses/'
    | '/refs/$refId/otus/$otuId/isolates'
    | '/refs/$refId/otus/$otuId/history'
    | '/refs/$refId/otus/$otuId/segments'
    | '/refs/$refId/otus/$otuId/'
    | '/refs/$refId/otus/$otuId/isolates/$isolateId'
    | '/otus/$otuId/isolates/$isolateId/sequences/$sequenceId/fasta'
    | '/refs/$refId/otus/$otuId/isolates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/events'
    | '/login'
    | '/metrics'
    | '/monitoring'
    | '/setup'
    | '/uploads'
    | '/health/live'
    | '/health/ready'
    | '/uploads/$uploadId'
    | '/'
    | '/account/api'
    | '/account/profile'
    | '/administration/groups'
    | '/administration/settings'
    | '/hmms/$hmmId'
    | '/jobs/$jobId'
    | '/refs/settings'
    | '/samples/create'
    | '/samples/files'
    | '/samples/labels'
    | '/samples/settings'
    | '/subtractions/$subtractionId'
    | '/subtractions/files'
    | '/analyses/documents/$document'
    | '/otus/$otuId/fasta'
    | '/account'
    | '/administration'
    | '/hmms'
    | '/jobs'
    | '/refs'
    | '/samples'
    | '/subtractions'
    | '/administration/users/$userId'
    | '/refs/$refId/manage'
    | '/refs/$refId/settings'
    | '/samples/$sampleId/files'
    | '/samples/$sampleId/general'
    | '/samples/$sampleId/quality'
    | '/samples/$sampleId/rights'
    | '/indexes/$indexId/files/$filename'
    | '/samples/$sampleId/reads/$filename'
    | '/subtractions/$subtractionId/files/$filename'
    | '/administration/users'
    | '/refs/$refId'
    | '/samples/$sampleId'
    | '/refs/$refId/indexes/$indexId'
    | '/samples/$sampleId/analyses/$analysisId'
    | '/otus/$otuId/isolates/$isolateId/fasta'
    | '/refs/$refId/indexes'
    | '/refs/$refId/otus'
    | '/samples/$sampleId/analyses'
    | '/refs/$refId/otus/$otuId/history'
    | '/refs/$refId/otus/$otuId/segments'
    | '/refs/$refId/otus/$otuId'
    | '/refs/$refId/otus/$otuId/isolates/$isolateId'
    | '/otus/$otuId/isolates/$isolateId/sequences/$sequenceId/fasta'
    | '/refs/$refId/otus/$otuId/isolates'
  id:
    | '__root__'
    | '/_authenticated'
    | '/events'
    | '/login'
    | '/metrics'
    | '/monitoring'
    | '/setup'
    | '/uploads'
    | '/_authenticated/administration'
    | '/_authenticated/refs'
    | '/_authenticated/account'
    | '/_authenticated/hmms'
    | '/_authenticated/jobs'
    | '/_authenticated/samples'
    | '/_authenticated/subtractions'
    | '/health/live'
    | '/health/ready'
    | '/uploads_/$uploadId'
    | '/_authenticated/'
    | '/_authenticated/refs/$refId'
    | '/_authenticated/account/api'
    | '/_authenticated/account/profile'
    | '/_authenticated/administration/groups'
    | '/_authenticated/administration/settings'
    | '/_authenticated/hmms/$hmmId'
    | '/_authenticated/jobs/$jobId'
    | '/_authenticated/refs/settings'
    | '/_authenticated/samples/$sampleId'
    | '/_authenticated/samples/create'
    | '/_authenticated/samples/files'
    | '/_authenticated/samples/labels'
    | '/_authenticated/samples/settings'
    | '/_authenticated/subtractions/$subtractionId'
    | '/_authenticated/subtractions/files'
    | '/analyses/documents/$document'
    | '/otus/$otuId/fasta'
    | '/_authenticated/account/'
    | '/_authenticated/administration/'
    | '/_authenticated/hmms/'
    | '/_authenticated/jobs/'
    | '/_authenticated/refs/'
    | '/_authenticated/samples/'
    | '/_authenticated/subtractions/'
    | '/_authenticated/administration/users/$userId'
    | '/_authenticated/refs/$refId/manage'
    | '/_authenticated/refs/$refId/settings'
    | '/_authenticated/samples/$sampleId/analyses'
    | '/_authenticated/samples/$sampleId/files'
    | '/_authenticated/samples/$sampleId/general'
    | '/_authenticated/samples/$sampleId/quality'
    | '/_authenticated/samples/$sampleId/rights'
    | '/indexes/$indexId/files/$filename'
    | '/samples/$sampleId/reads/$filename'
    | '/subtractions/$subtractionId/files/$filename'
    | '/_authenticated/administration/users/'
    | '/_authenticated/refs/$refId/'
    | '/_authenticated/samples/$sampleId/'
    | '/_authenticated/refs/$refId/otus/$otuId'
    | '/_authenticated/refs/$refId/indexes/$indexId'
    | '/_authenticated/samples/$sampleId/analyses/$analysisId'
    | '/otus/$otuId/isolates/$isolateId/fasta'
    | '/_authenticated/refs/$refId/indexes/'
    | '/_authenticated/refs/$refId/otus/'
    | '/_authenticated/samples/$sampleId/analyses/'
    | '/_authenticated/refs/$refId/otus/$otuId/isolates'
    | '/_authenticated/refs/$refId/otus/$otuId/history'
    | '/_authenticated/refs/$refId/otus/$otuId/segments'
    | '/_authenticated/refs/$refId/otus/$otuId/'
    | '/_authenticated/refs/$refId/otus/$otuId/isolates/$isolateId'
    | '/otus/$otuId/isolates/$isolateId/sequences/$sequenceId/fasta'
    | '/_authenticated/refs/$refId/otus/$otuId/isolates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  MetricsRoute: typeof MetricsRoute
  MonitoringRoute: typeof MonitoringRoute
  SetupRoute: typeof SetupRoute
  UploadsRoute: typeof UploadsRoute
  HealthLiveRoute: typeof HealthLiveRoute
  HealthReadyRoute: typeof HealthReadyRoute
  UploadsUploadIdRoute: typeof UploadsUploadIdRoute
  AnalysesDocumentsDocumentRoute: typeof AnalysesDocumentsDocumentRoute
  OtusOtuIdFastaRoute: typeof OtusOtuIdFastaRoute
  IndexesIndexIdFilesFilenameRoute: typeof IndexesIndexIdFilesFilenameRoute
  SamplesSampleIdReadsFilenameRoute: typeof SamplesSampleIdReadsFilenameRoute
  SubtractionsSubtractionIdFilesFilenameRoute: typeof SubtractionsSubtractionIdFilesFilenameRoute
  OtusOtuIdIsolatesIsolateIdFastaRoute: typeof OtusOtuIdIsolatesIsolateIdFastaRoute
  OtusOtuIdIsolatesIsolateIdSequencesSequenceIdFastaRoute: typeof OtusOtuIdIsolatesIsolateIdSequencesSequenceIdFastaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administration': {
      id: '/_authenticated/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AuthenticatedAdministrationRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hmms': {
      id: '/_authenticated/hmms'
      path: '/hmms'
      fullPath: '/hmms'
      preLoaderRoute: typeof AuthenticatedHmmsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/refs': {
      id: '/_authenticated/refs'
      path: '/refs'
      fullPath: '/refs'
      preLoaderRoute: typeof AuthenticatedRefsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/samples': {
      id: '/_authenticated/samples'
      path: '/samples'
      fullPath: '/samples'
      preLoaderRoute: typeof AuthenticatedSamplesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subtractions': {
      id: '/_authenticated/subtractions'
      path: '/subtractions'
      fullPath: '/subtractions'
      preLoaderRoute: typeof AuthenticatedSubtractionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/health/live': {
      id: '/health/live'
      path: '/health/live'
      fullPath: '/health/live'
      preLoaderRoute: typeof HealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/ready': {
      id: '/health/ready'
      path: '/health/ready'
      fullPath: '/health/ready'
      preLoaderRoute: typeof HealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads_/$uploadId': {
      id: '/uploads_/$uploadId'
      path: '/uploads/$uploadId'
      fullPath: '/uploads/$uploadId'
      preLoaderRoute: typeof UploadsUploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/api': {
      id: '/_authenticated/account/api'
      path: '/api'
      fullPath: '/account/api'
      preLoaderRoute: typeof AuthenticatedAccountApiRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/administration/': {
      id: '/_authenticated/administration/'
      path: '/'
      fullPath: '/administration/'
      preLoaderRoute: typeof AuthenticatedAdministrationIndexRouteImport
      parentRoute: typeof AuthenticatedAdministrationRouteRoute
    }
    '/_authenticated/administration/groups': {
      id: '/_authenticated/administration/groups'
      path: '/groups'
      fullPath: '/administration/groups'
      preLoaderRoute: typeof AuthenticatedAdministrationGroupsRouteImport
      parentRoute: typeof AuthenticatedAdministrationRouteRoute
    }
    '/_authenticated/administration/settings': {
      id: '/_authenticated/administration/settings'
      path: '/settings'
      fullPath: '/administration/settings'
      preLoaderRoute: typeof AuthenticatedAdministrationSettingsRouteImport
      parentRoute: typeof AuthenticatedAdministrationRouteRoute
    }
    '/_authenticated/hmms/': {
      id: '/_authenticated/hmms/'
      path: '/'
      fullPath: '/hmms/'
      preLoaderRoute: typeof AuthenticatedHmmsIndexRouteImport
      parentRoute: typeof AuthenticatedHmmsRoute
    }
    '/_authenticated/hmms/$hmmId': {
      id: '/_authenticated/hmms/$hmmId'
      path: '/$hmmId'
      fullPath: '/hmms/$hmmId'
      preLoaderRoute: typeof AuthenticatedHmmsHmmIdRouteImport
      parentRoute: typeof AuthenticatedHmmsRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedJobsRoute
    }
    '/_authenticated/jobs/$jobId': {
      id: '/_authenticated/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedJobsRoute
    }
    '/_authenticated/refs/': {
      id: '/_authenticated/refs/'
      path: '/'
      fullPath: '/refs/'
      preLoaderRoute: typeof AuthenticatedRefsIndexRouteImport
      parentRoute: typeof AuthenticatedRefsRouteRoute
    }
    '/_authenticated/refs/$refId': {
      id: '/_authenticated/refs/$refId'
      path: '/$refId'
      fullPath: '/refs/$refId'
      preLoaderRoute: typeof AuthenticatedRefsRefIdRouteRouteImport
      parentRoute: typeof AuthenticatedRefsRouteRoute
    }
    '/_authenticated/refs/settings': {
      id: '/_authenticated/refs/settings'
      path: '/settings'
      fullPath: '/refs/settings'
      preLoaderRoute: typeof AuthenticatedRefsSettingsRouteImport
      parentRoute: typeof AuthenticatedRefsRouteRoute
    }
    '/_authenticated/samples/': {
      id: '/_authenticated/samples/'
      path: '/'
      fullPath: '/samples/'
      preLoaderRoute: typeof AuthenticatedSamplesIndexRouteImport
      parentRoute: typeof AuthenticatedSamplesRoute
    }
    '/_authenticated/samples/$sampleId': {
      id: '/_authenticated/samples/$sampleId'
      path: '/$sampleId'
      fullPath: '/samples/$sampleId'
      preLoaderRoute: typeof AuthenticatedSamplesSampleIdRouteImport
      parentRoute: typeof AuthenticatedSamplesRoute
    }
    '/_authenticated/samples/create': {
      id: '/_authenticated/samples/create'
      path: '/create'
      fullPath: '/samples/create'
      preLoaderRoute: typeof AuthenticatedSamplesCreateRouteImport
      parentRoute: typeof AuthenticatedSamplesRoute
    }
    '/_authenticated/samples/files': {
      id: '/_authenticated/samples/files'
      path: '/files'
      fullPath: '/samples/files'
      preLoaderRoute: typeof AuthenticatedSamplesFilesRouteImport
      parentRoute: typeof AuthenticatedSamplesRoute
    }
    '/_authenticated/samples/labels': {
      id: '/_authenticated/samples/labels'
      path: '/labels'
      fullPath: '/samples/labels'
      preLoaderRoute: typeof AuthenticatedSamplesLabelsRouteImport
      parentRoute: typeof AuthenticatedSamplesRoute
    }
    '/_authenticated/samples/settings': {
      id: '/_authenticated/samples/settings'
      path: '/settings'
      fullPath: '/samples/settings'
      preLoaderRoute: typeof AuthenticatedSamplesSettingsRouteImport
      parentRoute: typeof AuthenticatedSamplesRoute
    }
    '/_authenticated/subtractions/': {
      id: '/_authenticated/subtractions/'
      path: '/'
      fullPath: '/subtractions/'
      preLoaderRoute: typeof AuthenticatedSubtractionsIndexRouteImport
      parentRoute: typeof AuthenticatedSubtractionsRoute
    }
    '/_authenticated/subtractions/$subtractionId': {
      id: '/_authenticated/subtractions/$subtractionId'
      path: '/$subtractionId'
      fullPath: '/subtractions/$subtractionId'
      preLoaderRoute: typeof AuthenticatedSubtractionsSubtractionIdRouteImport
      parentRoute: typeof AuthenticatedSubtractionsRoute
    }
    '/_authenticated/subtractions/files': {
      id: '/_authenticated/subtractions/files'
      path: '/files'
      fullPath: '/subtractions/files'
      preLoaderRoute: typeof AuthenticatedSubtractionsFilesRouteImport
      parentRoute: typeof AuthenticatedSubtractionsRoute
    }
    '/analyses/documents/$document': {
      id: '/analyses/documents/$document'
      path: '/analyses/documents/$document'
      fullPath: '/analyses/documents/$document'
      preLoaderRoute: typeof AnalysesDocumentsDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otus/$otuId/fasta': {
      id: '/otus/$otuId/fasta'
      path: '/otus/$otuId/fasta'
      fullPath: '/otus/$otuId/fasta'
      preLoaderRoute: typeof OtusOtuIdFastaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/administration/users/': {
      id: '/_authenticated/administration/users/'
      path: '/users'
      fullPath: '/administration/users/'
      preLoaderRoute: typeof AuthenticatedAdministrationUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdministrationRouteRoute
    }
    '/_authenticated/administration/users/$userId': {
      id: '/_authenticated/administration/users/$userId'
      path: '/users/$userId'
      fullPath: '/administration/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdministrationUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdministrationRouteRoute
    }
    '/_authenticated/refs/$refId/': {
      id: '/_authenticated/refs/$refId/'
      path: '/'
      fullPath: '/refs/$refId/'
      preLoaderRoute: typeof AuthenticatedRefsRefIdIndexRouteImport
      parentRoute: typeof AuthenticatedRefsRefIdRouteRoute
    }
    '/_authenticated/refs/$refId/manage': {
      id: '/_authenticated/refs/$refId/manage'
      path: '/manage'
      fullPath: '/refs/$refId/manage'
      preLoaderRoute: typeof AuthenticatedRefsRefIdManageRouteImport
      parentRoute: typeof AuthenticatedRefsRefIdRouteRoute
    }
    '/_authenticated/refs/$refId/settings': {
      id: '/_authenticated/refs/$refId/settings'
      path: '/settings'
      fullPath: '/refs/$refId/settings'
      preLoaderRoute: typeof AuthenticatedRefsRefIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRefsRefIdRouteRoute
    }
    '/_authenticated/samples/$sampleId/': {
      id: '/_authenticated/samples/$sampleId/'
      path: '/'
      fullPath: '/samples/$sampleId/'
      preLoaderRoute: typeof AuthenticatedSamplesSampleIdIndexRouteImport
      parentRoute: typeof AuthenticatedSamplesSampleIdRoute
    }
    '/_authenticated/samples/$sampleId/analyses': {
      id: '/_authenticated/samples/$sampleId/analyses'
      path: '/analyses'
      fullPath: '/samples/$sampleId/analyses'
      preLoaderRoute: typeof AuthenticatedSamplesSampleIdAnalysesRouteImport
      parentRoute: typeof AuthenticatedSamplesSampleIdRoute
    }
    '/_authenticated/samples/$sampleId/files': {
      id: '/_authenticated/samples/$sampleId/files'
      path: '/files'
      fullPath: '/samples/$sampleId/files'
      preLoaderRoute: typeof AuthenticatedSamplesSampleIdFilesRouteImport
      parentRoute: typeof AuthenticatedSamplesSampleIdRoute
    }
    '/_authenticated/samples/$sampleId/general': {
      id: '/_authenticated/samples/$sampleId/general'
      path: '/general'
      fullPath: '/samples/$sampleId/general'
      preLoaderRoute: typeof AuthenticatedSamplesSampleIdGeneralRouteImport
      parentRoute: typeof AuthenticatedSamplesSampleIdRoute
    }
    '/_authenticated/samples/$sampleId/quality': {
      id: '/_authenticated/samples/$sampleId/quality'
      path: '/quality'
      fullPath: '/samples/$sampleId/quality'
      preLoaderRoute: typeof AuthenticatedSamplesSampleIdQualityRouteImport
      parentRoute: typeof AuthenticatedSamplesSampleIdRoute
    }
    '/_authenticated/samples/$sampleId/rights': {
      id: '/_authenticated/samples/$sampleId/rights'
      path: '/rights'
      fullPath: '/samples/$sampleId/rights'
      preLoaderRoute: typeof AuthenticatedSamplesSampleIdRightsRouteImport
      parentRoute: typeof AuthenticatedSamplesSampleIdRoute
    }
    '/indexes/$indexId/files/$filename': {
      id: '/indexes/$indexId/files/$filename'
      path: '/indexes/$indexId/files/$filename'
      fullPath: '/indexes/$indexId/files/$filename'
      preLoaderRoute: typeof IndexesIndexIdFilesFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/$sampleId/reads/$filename': {
      id: '/samples/$sampleId/reads/$filename'
      path: '/samples/$sampleId/reads/$filename'
      fullPath: '/samples/$sampleId/reads/$filename'
      preLoaderRoute: typeof SamplesSampleIdReadsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subtractions/$subtractionId/files/$filename': {
      id: '/subtractions/$subtractionId/files/$filename'
      path: '/subtractions/$subtractionId/files/$filename'
      fullPath: '/subtractions/$subtractionId/files/$filename'
      preLoaderRoute: typeof SubtractionsSubtractionIdFilesFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/refs/$refId/indexes/': {
      id: '/_authenticated/refs/$refId/indexes/'
      path: '/indexes'
      fullPath: '/refs/$refId/indexes/'
      preLoaderRoute: typeof AuthenticatedRefsRefIdIndexesIndexRouteImport
      parentRoute: typeof AuthenticatedRefsRefIdRouteRoute
    }
    '/_authenticated/refs/$refId/indexes/$indexId': {
      id: '/_authenticated/refs/$refId/indexes/$indexId'
      path: '/indexes/$indexId'
      fullPath: '/refs/$refId/indexes/$indexId'
      preLoaderRoute: typeof AuthenticatedRefsRefIdIndexesIndexIdRouteImport
      parentRoute: typeof AuthenticatedRefsRefIdRouteRoute
    }
    '/_authenticated/refs/$refId/otus/': {
      id: '/_authenticated/refs/$refId/otus/'
      path: '/otus'
      fullPath: '/refs/$refId/otus/'
      preLoaderRoute: typeof AuthenticatedRefsRefIdOtusIndexRouteImport
      parentRoute: typeof AuthenticatedRefsRefIdRouteRoute
    }
    '/_authenticated/refs/$refId/otus/$otuId': {
      id: '/_authenticated/refs/$refId/otus/$otuId'
      path: '/otus/$otuId'
      fullPath: '/refs/$refId/otus/$otuId'
      preLoaderRoute: typeof AuthenticatedRefsRefIdOtusOtuIdRouteRouteImport
      parentRoute: typeof AuthenticatedRefsRefIdRouteRoute
    }
    '/_authenticated/samples/$sampleId/analyses/': {
      id: '/_authenticated/samples/$sampleId/analyses/'
      path: '/'
      fullPath: '/samples/$sampleId/analyses/'
      preLoaderRoute: typeof AuthenticatedSamplesSampleIdAnalysesIndexRouteImport
      parentRoute: typeof AuthenticatedSamplesSampleIdAnalysesRoute
    }
    '/_authenticated/samples/$sampleId/analyses/$analysisId': {
      id: '/_authenticated/samples/$sampleId/analyses/$analysisId'
      path: '/$analysisId'
      fullPath: '/samples/$sampleId/analyses/$analysisId'
      preLoaderRoute: typeof AuthenticatedSamplesSampleIdAnalysesAnalysisIdRouteImport
      parentRoute: typeof AuthenticatedSamplesSampleIdAnalysesRoute
    }
    '/otus/$otuId/isolates/$isolateId/fasta': {
      id: '/otus/$otuId/isolates/$isolateId/fasta'
      path: '/otus/$otuId/isolates/$isolateId/fasta'
      fullPath: '/otus/$otuId/isolates/$isolateId/fasta'
      preLoaderRoute: typeof OtusOtuIdIsolatesIsolateIdFastaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/refs/$refId/otus/$otuId/': {
      id: '/_authenticated/refs/$refId/otus/$otuId/'
      path: '/'
      fullPath: '/refs/$refId/otus/$otuId/'
      preLoaderRoute: typeof AuthenticatedRefsRefIdOtusOtuIdIndexRouteImport
      parentRoute: typeof AuthenticatedRefsRefIdOtusOtuIdRouteRoute
    }
    '/_authenticated/refs/$refId/otus/$otuId/history': {
      id: '/_authenticated/refs/$refId/otus/$otuId/history'
      path: '/history'
      fullPath: '/refs/$refId/otus/$otuId/history'
      preLoaderRoute: typeof AuthenticatedRefsRefIdOtusOtuIdHistoryRouteImport
      parentRoute: typeof AuthenticatedRefsRefIdOtusOtuIdRouteRoute
    }
    '/_authenticated/refs/$refId/otus/$otuId/isolates': {
      id: '/_authenticated/refs/$refId/otus/$otuId/isolates'
      path: '/isolates'
      fullPath: '/refs/$refId/otus/$otuId/isolates'
      preLoaderRoute: typeof AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRouteImport
      parentRoute: typeof AuthenticatedRefsRefIdOtusOtuIdRouteRoute
    }
    '/_authenticated/refs/$refId/otus/$otuId/segments': {
      id: '/_authenticated/refs/$refId/otus/$otuId/segments'
      path: '/segments'
      fullPath: '/refs/$refId/otus/$otuId/segments'
      preLoaderRoute: typeof AuthenticatedRefsRefIdOtusOtuIdSegmentsRouteImport
      parentRoute: typeof AuthenticatedRefsRefIdOtusOtuIdRouteRoute
    }
    '/_authenticated/refs/$refId/otus/$otuId/isolates/': {
      id: '/_authenticated/refs/$refId/otus/$otuId/isolates/'
      path: '/'
      fullPath: '/refs/$refId/otus/$otuId/isolates/'
      preLoaderRoute: typeof AuthenticatedRefsRefIdOtusOtuIdIsolatesIndexRouteImport
      parentRoute: typeof AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRoute
    }
    '/_authenticated/refs/$refId/otus/$otuId/isolates/$isolateId': {
      id: '/_authenticated/refs/$refId/otus/$otuId/isolates/$isolateId'
      path: '/$isolateId'
      fullPath: '/refs/$refId/otus/$otuId/isolates/$isolateId'
      preLoaderRoute: typeof AuthenticatedRefsRefIdOtusOtuIdIsolatesIsolateIdRouteImport
      parentRoute: typeof AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRoute
    }
    '/otus/$otuId/isolates/$isolateId/sequences/$sequenceId/fasta': {
      id: '/otus/$otuId/isolates/$isolateId/sequences/$sequenceId/fasta'
      path: '/otus/$otuId/isolates/$isolateId/sequences/$sequenceId/fasta'
      fullPath: '/otus/$otuId/isolates/$isolateId/sequences/$sequenceId/fasta'
      preLoaderRoute: typeof OtusOtuIdIsolatesIsolateIdSequencesSequenceIdFastaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdministrationRouteRouteChildren {
  AuthenticatedAdministrationGroupsRoute: typeof AuthenticatedAdministrationGroupsRoute
  AuthenticatedAdministrationSettingsRoute: typeof AuthenticatedAdministrationSettingsRoute
  AuthenticatedAdministrationIndexRoute: typeof AuthenticatedAdministrationIndexRoute
  AuthenticatedAdministrationUsersUserIdRoute: typeof AuthenticatedAdministrationUsersUserIdRoute
  AuthenticatedAdministrationUsersIndexRoute: typeof AuthenticatedAdministrationUsersIndexRoute
}

const AuthenticatedAdministrationRouteRouteChildren: AuthenticatedAdministrationRouteRouteChildren =
  {
    AuthenticatedAdministrationGroupsRoute:
      AuthenticatedAdministrationGroupsRoute,
    AuthenticatedAdministrationSettingsRoute:
      AuthenticatedAdministrationSettingsRoute,
    AuthenticatedAdministrationIndexRoute:
      AuthenticatedAdministrationIndexRoute,
    AuthenticatedAdministrationUsersUserIdRoute:
      AuthenticatedAdministrationUsersUserIdRoute,
    AuthenticatedAdministrationUsersIndexRoute:
      AuthenticatedAdministrationUsersIndexRoute,
  }

const AuthenticatedAdministrationRouteRouteWithChildren =
  AuthenticatedAdministrationRouteRoute._addFileChildren(
    AuthenticatedAdministrationRouteRouteChildren,
  )

interface AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRouteChildren {
  AuthenticatedRefsRefIdOtusOtuIdIsolatesIsolateIdRoute: typeof AuthenticatedRefsRefIdOtusOtuIdIsolatesIsolateIdRoute
  AuthenticatedRefsRefIdOtusOtuIdIsolatesIndexRoute: typeof AuthenticatedRefsRefIdOtusOtuIdIsolatesIndexRoute
}

const AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRouteChildren: AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRouteChildren =
  {
    AuthenticatedRefsRefIdOtusOtuIdIsolatesIsolateIdRoute:
      AuthenticatedRefsRefIdOtusOtuIdIsolatesIsolateIdRoute,
    AuthenticatedRefsRefIdOtusOtuIdIsolatesIndexRoute:
      AuthenticatedRefsRefIdOtusOtuIdIsolatesIndexRoute,
  }

const AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRouteWithChildren =
  AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRoute._addFileChildren(
    AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRouteChildren,
  )

interface AuthenticatedRefsRefIdOtusOtuIdRouteRouteChildren {
  AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRoute: typeof AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRouteWithChildren
  AuthenticatedRefsRefIdOtusOtuIdHistoryRoute: typeof AuthenticatedRefsRefIdOtusOtuIdHistoryRoute
  AuthenticatedRefsRefIdOtusOtuIdSegmentsRoute: typeof AuthenticatedRefsRefIdOtusOtuIdSegmentsRoute
  AuthenticatedRefsRefIdOtusOtuIdIndexRoute: typeof AuthenticatedRefsRefIdOtusOtuIdIndexRoute
}

const AuthenticatedRefsRefIdOtusOtuIdRouteRouteChildren: AuthenticatedRefsRefIdOtusOtuIdRouteRouteChildren =
  {
    AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRoute:
      AuthenticatedRefsRefIdOtusOtuIdIsolatesRouteRouteWithChildren,
    AuthenticatedRefsRefIdOtusOtuIdHistoryRoute:
      AuthenticatedRefsRefIdOtusOtuIdHistoryRoute,
    AuthenticatedRefsRefIdOtusOtuIdSegmentsRoute:
      AuthenticatedRefsRefIdOtusOtuIdSegmentsRoute,
    AuthenticatedRefsRefIdOtusOtuIdIndexRoute:
      AuthenticatedRefsRefIdOtusOtuIdIndexRoute,
  }

const AuthenticatedRefsRefIdOtusOtuIdRouteRouteWithChildren =
  AuthenticatedRefsRefIdOtusOtuIdRouteRoute._addFileChildren(
    AuthenticatedRefsRefIdOtusOtuIdRouteRouteChildren,
  )

interface AuthenticatedRefsRefIdRouteRouteChildren {
  AuthenticatedRefsRefIdManageRoute: typeof AuthenticatedRefsRefIdManageRoute
  AuthenticatedRefsRefIdSettingsRoute: typeof AuthenticatedRefsRefIdSettingsRoute
  AuthenticatedRefsRefIdIndexRoute: typeof AuthenticatedRefsRefIdIndexRoute
  AuthenticatedRefsRefIdOtusOtuIdRouteRoute: typeof AuthenticatedRefsRefIdOtusOtuIdRouteRouteWithChildren
  AuthenticatedRefsRefIdIndexesIndexIdRoute: typeof AuthenticatedRefsRefIdIndexesIndexIdRoute
  AuthenticatedRefsRefIdIndexesIndexRoute: typeof AuthenticatedRefsRefIdIndexesIndexRoute
  AuthenticatedRefsRefIdOtusIndexRoute: typeof AuthenticatedRefsRefIdOtusIndexRoute
}

const AuthenticatedRefsRefIdRouteRouteChildren: AuthenticatedRefsRefIdRouteRouteChildren =
  {
    AuthenticatedRefsRefIdManageRoute: AuthenticatedRefsRefIdManageRoute,
    AuthenticatedRefsRefIdSettingsRoute: AuthenticatedRefsRefIdSettingsRoute,
    AuthenticatedRefsRefIdIndexRoute: AuthenticatedRefsRefIdIndexRoute,
    AuthenticatedRefsRefIdOtusOtuIdRouteRoute:
      AuthenticatedRefsRefIdOtusOtuIdRouteRouteWithChildren,
    AuthenticatedRefsRefIdIndexesIndexIdRoute:
      AuthenticatedRefsRefIdIndexesIndexIdRoute,
    AuthenticatedRefsRefIdIndexesIndexRoute:
      AuthenticatedRefsRefIdIndexesIndexRoute,
    AuthenticatedRefsRefIdOtusIndexRoute: AuthenticatedRefsRefIdOtusIndexRoute,
  }

const AuthenticatedRefsRefIdRouteRouteWithChildren =
  AuthenticatedRefsRefIdRouteRoute._addFileChildren(
    AuthenticatedRefsRefIdRouteRouteChildren,
  )

interface AuthenticatedRefsRouteRouteChildren {
  AuthenticatedRefsRefIdRouteRoute: typeof AuthenticatedRefsRefIdRouteRouteWithChildren
  AuthenticatedRefsSettingsRoute: typeof AuthenticatedRefsSettingsRoute
  AuthenticatedRefsIndexRoute: typeof AuthenticatedRefsIndexRoute
}

const AuthenticatedRefsRouteRouteChildren: AuthenticatedRefsRouteRouteChildren =
  {
    AuthenticatedRefsRefIdRouteRoute:
      AuthenticatedRefsRefIdRouteRouteWithChildren,
    AuthenticatedRefsSettingsRoute: AuthenticatedRefsSettingsRoute,
    AuthenticatedRefsIndexRoute: AuthenticatedRefsIndexRoute,
  }

const AuthenticatedRefsRouteRouteWithChildren =
  AuthenticatedRefsRouteRoute._addFileChildren(
    AuthenticatedRefsRouteRouteChildren,
  )

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountApiRoute: typeof AuthenticatedAccountApiRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountApiRoute: AuthenticatedAccountApiRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedHmmsRouteChildren {
  AuthenticatedHmmsHmmIdRoute: typeof AuthenticatedHmmsHmmIdRoute
  AuthenticatedHmmsIndexRoute: typeof AuthenticatedHmmsIndexRoute
}

const AuthenticatedHmmsRouteChildren: AuthenticatedHmmsRouteChildren = {
  AuthenticatedHmmsHmmIdRoute: AuthenticatedHmmsHmmIdRoute,
  AuthenticatedHmmsIndexRoute: AuthenticatedHmmsIndexRoute,
}

const AuthenticatedHmmsRouteWithChildren =
  AuthenticatedHmmsRoute._addFileChildren(AuthenticatedHmmsRouteChildren)

interface AuthenticatedJobsRouteChildren {
  AuthenticatedJobsJobIdRoute: typeof AuthenticatedJobsJobIdRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
}

const AuthenticatedJobsRouteChildren: AuthenticatedJobsRouteChildren = {
  AuthenticatedJobsJobIdRoute: AuthenticatedJobsJobIdRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
}

const AuthenticatedJobsRouteWithChildren =
  AuthenticatedJobsRoute._addFileChildren(AuthenticatedJobsRouteChildren)

interface AuthenticatedSamplesSampleIdAnalysesRouteChildren {
  AuthenticatedSamplesSampleIdAnalysesAnalysisIdRoute: typeof AuthenticatedSamplesSampleIdAnalysesAnalysisIdRoute
  AuthenticatedSamplesSampleIdAnalysesIndexRoute: typeof AuthenticatedSamplesSampleIdAnalysesIndexRoute
}

const AuthenticatedSamplesSampleIdAnalysesRouteChildren: AuthenticatedSamplesSampleIdAnalysesRouteChildren =
  {
    AuthenticatedSamplesSampleIdAnalysesAnalysisIdRoute:
      AuthenticatedSamplesSampleIdAnalysesAnalysisIdRoute,
    AuthenticatedSamplesSampleIdAnalysesIndexRoute:
      AuthenticatedSamplesSampleIdAnalysesIndexRoute,
  }

const AuthenticatedSamplesSampleIdAnalysesRouteWithChildren =
  AuthenticatedSamplesSampleIdAnalysesRoute._addFileChildren(
    AuthenticatedSamplesSampleIdAnalysesRouteChildren,
  )

interface AuthenticatedSamplesSampleIdRouteChildren {
  AuthenticatedSamplesSampleIdAnalysesRoute: typeof AuthenticatedSamplesSampleIdAnalysesRouteWithChildren
  AuthenticatedSamplesSampleIdFilesRoute: typeof AuthenticatedSamplesSampleIdFilesRoute
  AuthenticatedSamplesSampleIdGeneralRoute: typeof AuthenticatedSamplesSampleIdGeneralRoute
  AuthenticatedSamplesSampleIdQualityRoute: typeof AuthenticatedSamplesSampleIdQualityRoute
  AuthenticatedSamplesSampleIdRightsRoute: typeof AuthenticatedSamplesSampleIdRightsRoute
  AuthenticatedSamplesSampleIdIndexRoute: typeof AuthenticatedSamplesSampleIdIndexRoute
}

const AuthenticatedSamplesSampleIdRouteChildren: AuthenticatedSamplesSampleIdRouteChildren =
  {
    AuthenticatedSamplesSampleIdAnalysesRoute:
      AuthenticatedSamplesSampleIdAnalysesRouteWithChildren,
    AuthenticatedSamplesSampleIdFilesRoute:
      AuthenticatedSamplesSampleIdFilesRoute,
    AuthenticatedSamplesSampleIdGeneralRoute:
      AuthenticatedSamplesSampleIdGeneralRoute,
    AuthenticatedSamplesSampleIdQualityRoute:
      AuthenticatedSamplesSampleIdQualityRoute,
    AuthenticatedSamplesSampleIdRightsRoute:
      AuthenticatedSamplesSampleIdRightsRoute,
    AuthenticatedSamplesSampleIdIndexRoute:
      AuthenticatedSamplesSampleIdIndexRoute,
  }

const AuthenticatedSamplesSampleIdRouteWithChildren =
  AuthenticatedSamplesSampleIdRoute._addFileChildren(
    AuthenticatedSamplesSampleIdRouteChildren,
  )

interface AuthenticatedSamplesRouteChildren {
  AuthenticatedSamplesSampleIdRoute: typeof AuthenticatedSamplesSampleIdRouteWithChildren
  AuthenticatedSamplesCreateRoute: typeof AuthenticatedSamplesCreateRoute
  AuthenticatedSamplesFilesRoute: typeof AuthenticatedSamplesFilesRoute
  AuthenticatedSamplesLabelsRoute: typeof AuthenticatedSamplesLabelsRoute
  AuthenticatedSamplesSettingsRoute: typeof AuthenticatedSamplesSettingsRoute
  AuthenticatedSamplesIndexRoute: typeof AuthenticatedSamplesIndexRoute
}

const AuthenticatedSamplesRouteChildren: AuthenticatedSamplesRouteChildren = {
  AuthenticatedSamplesSampleIdRoute:
    AuthenticatedSamplesSampleIdRouteWithChildren,
  AuthenticatedSamplesCreateRoute: AuthenticatedSamplesCreateRoute,
  AuthenticatedSamplesFilesRoute: AuthenticatedSamplesFilesRoute,
  AuthenticatedSamplesLabelsRoute: AuthenticatedSamplesLabelsRoute,
  AuthenticatedSamplesSettingsRoute: AuthenticatedSamplesSettingsRoute,
  AuthenticatedSamplesIndexRoute: AuthenticatedSamplesIndexRoute,
}

const AuthenticatedSamplesRouteWithChildren =
  AuthenticatedSamplesRoute._addFileChildren(AuthenticatedSamplesRouteChildren)

interface AuthenticatedSubtractionsRouteChildren {
  AuthenticatedSubtractionsSubtractionIdRoute: typeof AuthenticatedSubtractionsSubtractionIdRoute
  AuthenticatedSubtractionsFilesRoute: typeof AuthenticatedSubtractionsFilesRoute
  AuthenticatedSubtractionsIndexRoute: typeof AuthenticatedSubtractionsIndexRoute
}

const AuthenticatedSubtractionsRouteChildren: AuthenticatedSubtractionsRouteChildren =
  {
    AuthenticatedSubtractionsSubtractionIdRoute:
      AuthenticatedSubtractionsSubtractionIdRoute,
    AuthenticatedSubtractionsFilesRoute: AuthenticatedSubtractionsFilesRoute,
    AuthenticatedSubtractionsIndexRoute: AuthenticatedSubtractionsIndexRoute,
  }

const AuthenticatedSubtractionsRouteWithChildren =
  AuthenticatedSubtractionsRoute._addFileChildren(
    AuthenticatedSubtractionsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdministrationRouteRoute: typeof AuthenticatedAdministrationRouteRouteWithChildren
  AuthenticatedRefsRouteRoute: typeof AuthenticatedRefsRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedHmmsRoute: typeof AuthenticatedHmmsRouteWithChildren
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRouteWithChildren
  AuthenticatedSamplesRoute: typeof AuthenticatedSamplesRouteWithChildren
  AuthenticatedSubtractionsRoute: typeof AuthenticatedSubtractionsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdministrationRouteRoute:
    AuthenticatedAdministrationRouteRouteWithChildren,
  AuthenticatedRefsRouteRoute: AuthenticatedRefsRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedHmmsRoute: AuthenticatedHmmsRouteWithChildren,
  AuthenticatedJobsRoute: AuthenticatedJobsRouteWithChildren,
  AuthenticatedSamplesRoute: AuthenticatedSamplesRouteWithChildren,
  AuthenticatedSubtractionsRoute: AuthenticatedSubtractionsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  MetricsRoute: MetricsRoute,
  MonitoringRoute: MonitoringRoute,
  SetupRoute: SetupRoute,
  UploadsRoute: UploadsRoute,
  HealthLiveRoute: HealthLiveRoute,
  HealthReadyRoute: HealthReadyRoute,
  UploadsUploadIdRoute: UploadsUploadIdRoute,
  AnalysesDocumentsDocumentRoute: AnalysesDocumentsDocumentRoute,
  OtusOtuIdFastaRoute: OtusOtuIdFastaRoute,
  IndexesIndexIdFilesFilenameRoute: IndexesIndexIdFilesFilenameRoute,
  SamplesSampleIdReadsFilenameRoute: SamplesSampleIdReadsFilenameRoute,
  SubtractionsSubtractionIdFilesFilenameRoute:
    SubtractionsSubtractionIdFilesFilenameRoute,
  OtusOtuIdIsolatesIsolateIdFastaRoute: OtusOtuIdIsolatesIsolateIdFastaRoute,
  OtusOtuIdIsolatesIsolateIdSequencesSequenceIdFastaRoute:
    OtusOtuIdIsolatesIsolateIdSequencesSequenceIdFastaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
