apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks
  labels:
    app.kubernetes.io/name: tasks
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: virtool
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tasks
      app.kubernetes.io/part-of: virtool
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tasks
        app.kubernetes.io/component: worker
        app.kubernetes.io/part-of: virtool
    spec:
      containers:
        - name: tasks
          image: ghcr.io/virtool/tasks:latest
          envFrom:
            - configMapRef:
                name: virtool-env
          ports:
            - containerPort: 9900
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 600m
              memory: 1Gi
