# HMMER
FROM alpine:latest as hmmer
WORKDIR /build
RUN apk update && apk add build-base linux-headers
RUN wget http://eddylab.org/software/hmmer/hmmer-3.2.1.tar.gz && \
    tar -xf hmmer-3.2.1.tar.gz && \
    cd hmmer-3.2.1 && \
    ./configure --prefix /build/hmmer && \
    make && \
    make install

# Bowtie2
FROM alpine:latest as bowtie
WORKDIR /build
RUN wget https://github.com/BenLangmead/bowtie2/releases/download/v2.3.2/bowtie2-2.3.2-legacy-linux-x86_64.zip && \
    unzip bowtie2-2.3.2-legacy-linux-x86_64.zip && \
    mkdir bowtie2 && \
    cp bowtie2-2.3.2-legacy/bowtie2* bowtie2

# SPAdes
FROM alpine:latest as spades
WORKDIR /build
RUN wget https://github.com/ablab/spades/releases/download/v3.11.0/SPAdes-3.11.0-Linux.tar.gz && \
    tar -xvf SPAdes-3.11.0-Linux.tar.gz && \
    mv SPAdes-3.11.0-Linux.tar.gz spades

# Install Python packages
FROM python:3.6 as pip
WORKDIR /build
ADD ./requirements.txt ./
RUN pip install -r requirements.txt

FROM python:3.6-alpine
WORKDIR /app
COPY ./virtool /app/virtool
COPY ./LICENSE /app/
COPY ./README.md /app/
COPY --from=hmmer /build/hmmer /opt/hmmer
COPY --from=bowtie /build/bowtie2/* /usr/local/bin/
COPY --from=spades /build/spades /opt/
COPY --from=pip /root/.cache /root/.cache
COPY --from=pip /build/requirements.txt ./
RUN apk add perl && \
    pip install -r requirements.txt && \
    cd /usr/local/bin && \
    ln -f -s /opt/spades/bin/spades.py && \
    for file in `ls /opt/hmmer/bin`; do ln -f -s /opt/hmmer/bin/$file; done
EXPOSE 9950
CMD ["python", "run.py"]
