version: "3.1"
services:
  jobs-api:
    image: virtool/virtool:5.11.2
    depends_on:
      - mongo
      - redis
      - postgres
    environment:
      VT_DATA_PATH: /data
      VT_DB_CONNECTION_STRING: mongodb://mongo:27017
      VT_POSTGRES_CONNECTION_STRING: postgresql+asyncpg://virtool:virtool@postgres/virtool
      VT_REDIS_CONNECTION_STRING: redis://redis:6379
    command: jobsAPI --host=0.0.0.0 --port=9990
    ports:
      - "9990:9990"
    volumes:
      - vt_data:/data​

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - vt_mongo_data:/data/db

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - vt_redis_data:/data

  postgres:
    image: postgres:13.1
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: virtool
      POSTGRES_PASSWORD: virtool
    volumes:
      - vt_postgres_data:/var/lib/postgresql/data

  #  nuvs:
  #    image: virtool/nuvs:debug
  #    entrypoint: workflow
  #    restart: always
  #    command: >
  #      run-from-redis --redis-url="redis://redis:6379"
  #      --jobs-api-url="http://jobs-api:9990" --dev-mode
  #      --is-analysis-workflow jobs_nuvs

  create-sample:
    image: virtool/create-sample:2.0.1
    entrypoint: workflow
    restart: always
    command: >
      run-from-redis --redis-url="redis://redis:6379"
      --jobs-api-url="http://jobs-api:9990" --dev-mode
      --is-analysis-workflow jobs_create_sample​

  create-subtraction:
    image: virtool/create-subtraction:2.0.1
    restart: always
    entrypoint: workflow
    command: >
      run-from-redis --redis-url="redis://redis:6379"
      --jobs-api-url="http://jobs-api:9990" --dev-mode
      --is-analysis-workflow jobs_create_subtraction​

  build-index:
    image: virtool/build-index:2.0.1
    restart: always
    entrypoint: workflow
    command: >
      run-from-redis --redis-url="redis://redis:6379"
      --jobs-api-url="http://jobs-api:9990" --dev-mode
      --is-analysis-workflow jobs_build_index

volumes:
  vt_data: null
  vt_mongo_data: null
  vt_redis_data: null
  vt_postgres_data: null
