import { describe, expect, it } from "vitest";

import { hashPassword, verifyPassword } from "./password";

// Generated by `python3 -c "import bcrypt; print(bcrypt.hashpw(b'hunter2', bcrypt.gensalt(12)).decode())"`.
// Pinning a Python-side hash ensures the bytea utf-8 round-trip stays
// compatible with passlib/bcrypt-stored values from the existing prod data.
const PYTHON_FIXTURE_PLAINTEXT = "hunter2";
const PYTHON_FIXTURE_HASH =
	"$2b$12$anheU95QO4gI0RzsA4CYRO66Uyk0v4OlEc6Z6tJ5z/cLDfIsg4jbS";

describe("hashPassword", () => {
	it("returns a Buffer that decodes to a $2b$12$ bcrypt string", async () => {
		const hash = await hashPassword("correct horse battery staple");
		expect(hash).toBeInstanceOf(Buffer);
		expect(hash.toString("utf8").startsWith("$2b$12$")).toBe(true);
	});
});

describe("verifyPassword", () => {
	it("verifies a freshly-hashed password", async () => {
		const hash = await hashPassword("hunter2");
		expect(await verifyPassword("hunter2", hash)).toBe(true);
	});

	it("rejects a wrong password", async () => {
		const hash = await hashPassword("hunter2");
		expect(await verifyPassword("wrong", hash)).toBe(false);
	});

	it("verifies a Python-generated bcrypt hash via bytea round-trip", async () => {
		const stored = Buffer.from(PYTHON_FIXTURE_HASH, "utf8");
		expect(await verifyPassword(PYTHON_FIXTURE_PLAINTEXT, stored)).toBe(true);
		expect(await verifyPassword("wrong", stored)).toBe(false);
	});
});
