/*
 Hand-written rather than kit-generated. Kit emits a bare
 `ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "<t>_id_seq" ... START WITH 1)`
 per table, which fails on a populated database three ways: the column still
 carries its `nextval` default, the sequence name it asks for is already taken
 by the serial's own sequence, and a fresh sequence starting at 1 would collide
 with every row already there.

 So each table drops the default, drops the serial's sequence, and attaches an
 identity sequence positioned past both the old sequence and the largest id in
 the table. `nextval` on the old sequence — not `last_value` — is what the
 serial would have handed out next, so an id already claimed by an in-flight or
 rolled-back insert is never reused.

 Reversible with `ALTER COLUMN "id" SET GENERATED BY DEFAULT` per table; that
 keeps the identity sequence and only relaxes the rejection of explicit ids.
*/
DO $$
DECLARE
	tbl text;
	seq text;
	next_id bigint;
BEGIN
	FOREACH tbl IN ARRAY ARRAY[
		'analysis_files',
		'api_keys',
		'caches',
		'groups',
		'index_files',
		'instance_messages',
		'jobs',
		'labels',
		'legacy_history_diff',
		'nuvs_blast',
		'sample_reads',
		'sessions',
		'subtraction_files',
		'tasks',
		'uploads',
		'users'
	] LOOP
		seq := pg_get_serial_sequence(quote_ident(tbl), 'id');

		IF seq IS NULL THEN
			RAISE EXCEPTION 'table % has no sequence on id', tbl;
		END IF;

		EXECUTE format(
			'SELECT GREATEST(nextval(%L), COALESCE(max(id), 0) + 1) FROM %I',
			seq,
			tbl
		) INTO next_id;

		EXECUTE format('ALTER TABLE %I ALTER COLUMN id DROP DEFAULT', tbl);
		EXECUTE format('DROP SEQUENCE %s', seq);
		EXECUTE format(
			'ALTER TABLE %I ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME %I INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH %s CACHE 1)',
			tbl,
			tbl || '_id_seq',
			next_id
		);
	END LOOP;
END $$;
