/**
 * Every read a workflow makes against a reference index artifact.
 *
 * These are the port of Python's `WFIndex`, and the shapes they return are
 * Python's verbatim — `snake_case`, `default` rather than `isDefault`, a nested
 * OTU document straight out of the legacy Mongo shape. They are not renamed on
 * the way through. A ported workflow copies these rows into a FASTA header, a
 * cache key and an analysis `results` blob that Python still writes the other
 * half of, so a field renamed here is a divergence somewhere downstream that
 * nothing in this package would catch.
 *
 * ## Ordering is the output
 *
 * The order sequences come back in decides the order of the FASTA records, and
 * so the order of the Bowtie2 index and every SAM line mapped against it. It
 * has to match Python exactly or the analysis is not reproducible, which is why
 * every query below carries an explicit `ORDER BY` copied from `indexes.py` and
 * why `fixtures/golden.json` — generated by running Python — pins the result.
 *
 * ## Nothing here materialises the index
 *
 * An artifact runs to 200–500 MB. Every iterating query streams through
 * `StatementSync.iterate()` and hands the event loop a turn every batch, so the
 * ping loop keeps the job alive while a long scan runs. Reaching for `.all()`
 * on any of these puts the whole index in the heap.
 */

import { createWriteStream } from "node:fs";
import type { DatabaseSync, SQLInputValue, SQLOutputValue } from "node:sqlite";
import { pipeline } from "node:stream/promises";
import { setImmediate } from "node:timers/promises";
import {
	IndexOtuIntegrityError,
	IndexReferenceNotFoundError,
	IndexSequenceNotFoundError,
} from "./errors";
import { type IndexArtifactSource, openIndexArtifact } from "./schema";

/**
 * Rows scanned between turns of the event loop.
 *
 * Python's `_SQLITE_SEQUENCE_BATCH_SIZE`. There it sizes a cursor partition
 * fetched on a worker thread; here `node:sqlite` is synchronous and there is no
 * thread to move the scan to, so it sizes how long the loop is blocked instead.
 */
const SEQUENCE_BATCH_SIZE = 500;

/**
 * OTU documents scanned between turns of the event loop.
 *
 * Python's `_SQLITE_OTU_BATCH_SIZE`. One, because a single OTU document carries
 * every sequence of every isolate and is large on its own.
 */
const OTU_BATCH_SIZE = 1;

/** Reference metadata, without the OTUs. */
export type IndexReference = {
	/** ISO-8601 timestamp of when the reference was created */
	created_at: string;

	/** Either `genome` or `barcode` */
	data_type: string;

	/** The unique identifier */
	id: string;

	/** The display name */
	name: string;

	/** The organism the reference covers, possibly empty */
	organism: string;
};

/** A sequence, flattened against the isolate and OTU that own it. */
export type IndexSequence = {
	/** The Genbank accession number */
	accession: string;

	/** A description of the sequence */
	definition: string;

	/** The host organism, or null if unrecorded */
	host: string | null;

	/** The unique identifier */
	id: string;

	/** The id of the owning isolate — the isolate's `virtool_id`, not its rowid */
	isolate_id: string;

	/** The id of the owning OTU */
	otu_id: string;

	/** The segment the sequence fills, or null if unplaced */
	segment: string | null;

	/** The nucleotide sequence */
	sequence: string;
};

/** A sequence as it appears nested inside an {@link IndexOtu}. */
export type IndexOtuSequence = {
	/** The Genbank accession number */
	accession: string;

	/** A description of the sequence */
	definition: string;

	/** The host organism, or null if unrecorded */
	host: string | null;

	/** The unique identifier */
	id: string;

	/** The segment the sequence fills, or null if unplaced */
	segment: string | null;

	/** The nucleotide sequence */
	sequence: string;
};

/** An isolate as it appears nested inside an {@link IndexOtu}. */
export type IndexOtuIsolate = {
	/** Whether this is the OTU's default isolate */
	default: boolean;

	/** The unique identifier */
	id: string;

	/** The isolate's sequences */
	sequences: IndexOtuSequence[];

	/** The source name, eg. `Q767` */
	source_name: string;

	/** The source type, eg. `isolate` */
	source_type: string;
};

/** A schema item describing a segment the OTU's isolates may carry. */
export type IndexOtuSchemaItem = {
	/** The molecule type, eg. `dsDNA`, or null if unset */
	molecule: string | null;

	/** The segment name */
	name: string;

	/** Whether every isolate must carry this segment */
	required: boolean;
};

/** A complete OTU document, isolates and sequences nested inside it. */
export type IndexOtu = {
	/** The short form of the name, possibly empty */
	abbreviation: string;

	/** The unique identifier */
	id: string;

	/** The OTU's isolates */
	isolates: IndexOtuIsolate[];

	/** The display name */
	name: string;

	/** The segments the OTU is expected to have */
	schema: IndexOtuSchemaItem[];

	/** The NCBI taxonomy id, or null if unassigned */
	taxid: number | null;

	/** The version the index was built at */
	version: number;
};

/** The OTU fields an alignment hit is annotated with. */
export type IndexOtuRef = {
	/** The short form of the name, possibly empty */
	abbreviation: string;

	/** The unique identifier */
	id: string;

	/** The display name */
	name: string;

	/** The NCBI taxonomy id, or null if unassigned */
	taxid: number | null;

	/** The version the index was built at */
	version: number;
};

/** A reference index artifact, open for reading. */
export type WorkflowIndex = {
	/** The id of the index the artifact was built for */
	id: number;

	/** The path the artifact was read from */
	path: string;

	/** Release the underlying file handle */
	close(): void;

	/** Read the reference metadata */
	getReferenceMetadata(): Promise<IndexReference>;

	/** Resolve sequence ids to the OTUs that own them */
	getOtuRefsBySequenceIds(
		sequenceIds: Iterable<string>,
	): Promise<Record<string, IndexOtuRef>>;

	/** Iterate every sequence belonging to a default isolate */
	iterDefaultSequences(): AsyncIterableIterator<IndexSequence>;

	/** Iterate the OTUs as nested documents */
	iterOtus(): AsyncIterableIterator<IndexOtu>;

	/** Iterate every sequence belonging to the given OTUs */
	iterOtuSequences(
		otuIds: string | Iterable<string>,
	): AsyncIterableIterator<IndexSequence>;

	/** Iterate every sequence in the index */
	iterSequences(): AsyncIterableIterator<IndexSequence>;
};

const SELECT_SEQUENCES = `
	SELECT
		sequences.id AS id,
		sequences.accession AS accession,
		sequences.definition AS definition,
		sequences.host AS host,
		isolates.virtool_id AS isolate_id,
		isolates.otu_id AS otu_id,
		sequences.segment AS segment,
		sequences.sequence AS sequence
	FROM sequences
	JOIN isolates ON sequences.isolate_id = isolates.id
`;

/**
 * Python's ordering for every sequence query but `iter_sequences`, which
 * replaces it with the sequence id alone.
 */
const SEQUENCE_ORDER = `
	ORDER BY isolates.otu_id, isolates.virtool_id, sequences.id
`;

/**
 * The nested OTU document, assembled by SQLite rather than in JavaScript.
 *
 * **The `ORDER BY` in each subquery below does nothing, and must stay anyway.**
 * SQLite applies an `ORDER BY` to the single row an aggregate produces, not to
 * the rows going into it, so `json_group_array` collects isolates and sequences
 * in whatever order the scan yields — which the indexes on `isolates.otu_id`
 * and `sequences.isolate_id` make insertion order, not id order. Python's query
 * has the same clauses and the same no-op, so its OTU documents come out in
 * insertion order too. Reproducing that is the point: pathoscope feeds these
 * sequences to `cd-hit-est`, which picks its cluster representative by the
 * order it sees them in. Removing these clauses, or "fixing" them into a real
 * sort, changes which sequences survive collapsing and so changes the analysis.
 */
const SELECT_OTUS = `
	SELECT json_object(
		'id', otus.id,
		'abbreviation', otus.abbreviation,
		'isolates', json((
			SELECT coalesce(json_group_array(json_object(
				'default', json(CASE WHEN isolates.is_default = 1 THEN 'true' ELSE 'false' END),
				'id', isolates.virtool_id,
				'sequences', json((
					SELECT coalesce(json_group_array(json_object(
						'id', sequences.id,
						'accession', sequences.accession,
						'definition', sequences.definition,
						'host', sequences.host,
						'segment', sequences.segment,
						'sequence', sequences.sequence
					)), json('[]'))
					FROM sequences
					WHERE sequences.isolate_id = isolates.id
					ORDER BY sequences.id
				)),
				'source_name', isolates.source_name,
				'source_type', isolates.source_type
			)), json('[]'))
			FROM isolates
			WHERE isolates.otu_id = otus.id
			ORDER BY isolates.virtool_id
		)),
		'name', otus.name,
		'schema', json((
			SELECT coalesce(json_group_array(json_object(
				'molecule', otu_schema.molecule,
				'name', otu_schema.name,
				'required', json(CASE WHEN otu_schema.required = 1 THEN 'true' ELSE 'false' END)
			)), json('[]'))
			FROM otu_schema
			WHERE otu_schema.otu_id = otus.id
			ORDER BY otu_schema.name
		)),
		'taxid', otus.taxid,
		'version', otus.version
	) AS document
	FROM otus
	ORDER BY otus.id
`;

/**
 * Bind an id set as one JSON array rather than one parameter per id.
 *
 * `IN (?, ?, …)` would cap the callable set at SQLite's variable limit, and
 * chunking around that limit is not available to the sequence queries — each
 * chunk would be sorted on its own and the concatenation would not be in
 * Python's order. `json_each` takes the whole set as a single parameter, so
 * there is no limit to work around.
 */
const IN_ID_SET = "(SELECT value FROM json_each(?))";

/**
 * Open the artifact at `source.path` for reading.
 *
 * The returned handle holds an open file descriptor. A workflow process is
 * one-shot and exit reclaims it, so `close` matters only where a run opens
 * artifacts repeatedly — pathoscope reloads its collapsed reference in several
 * steps.
 *
 * @throws {IndexArtifactMissingError} when the artifact is absent or unopenable.
 * @throws {IndexArtifactFormatError} when it is not an artifact this reader understands.
 */
export function openWorkflowIndex(source: IndexArtifactSource): WorkflowIndex {
	const database = openIndexArtifact(source);

	return {
		id: source.id,
		path: source.path,

		close() {
			database.close();
		},

		async getReferenceMetadata(): Promise<IndexReference> {
			const row = database
				.prepare(
					`SELECT id, created_at, data_type, name, organism FROM reference`,
				)
				.get();

			if (row === undefined) {
				throw new IndexReferenceNotFoundError(
					`Index ${source.id} holds no reference metadata`,
				);
			}

			return {
				created_at: asString(row, "created_at"),
				data_type: asString(row, "data_type"),
				id: asString(row, "id"),
				name: asString(row, "name"),
				organism: asString(row, "organism"),
			};
		},

		async getOtuRefsBySequenceIds(
			sequenceIds: Iterable<string>,
		): Promise<Record<string, IndexOtuRef>> {
			const wanted = new Set(sequenceIds);

			if (wanted.size === 0) {
				return {};
			}

			const rows = database
				.prepare(
					`SELECT
						sequences.id AS sequence_id,
						otus.id AS otu_id,
						otus.abbreviation AS abbreviation,
						otus.name AS name,
						otus.taxid AS taxid,
						otus.version AS version
					FROM sequences
					JOIN isolates ON sequences.isolate_id = isolates.id
					JOIN otus ON isolates.otu_id = otus.id
					WHERE sequences.id IN ${IN_ID_SET}`,
				)
				.all(JSON.stringify([...wanted]));

			const refs: Record<string, IndexOtuRef> = {};

			for (const row of rows) {
				refs[asString(row, "sequence_id")] = {
					abbreviation: asString(row, "abbreviation"),
					id: asString(row, "otu_id"),
					name: asString(row, "name"),
					taxid: asNumberOrNull(row, "taxid"),
					version: asNumber(row, "version"),
				};
			}

			const missing = [...wanted].filter((id) => !(id in refs));

			if (missing.length > 0) {
				throw new IndexSequenceNotFoundError(missing);
			}

			return refs;
		},

		iterDefaultSequences(): AsyncIterableIterator<IndexSequence> {
			return iterateRows(
				database,
				`${SELECT_SEQUENCES} WHERE isolates.is_default = 1 ${SEQUENCE_ORDER}`,
				[],
				SEQUENCE_BATCH_SIZE,
				shapeSequence,
			);
		},

		iterOtus(): AsyncIterableIterator<IndexOtu> {
			return iterateRows(database, SELECT_OTUS, [], OTU_BATCH_SIZE, (row) =>
				checkOtu(JSON.parse(asString(row, "document")) as IndexOtu),
			);
		},

		iterOtuSequences(
			otuIds: string | Iterable<string>,
		): AsyncIterableIterator<IndexSequence> {
			const wanted =
				typeof otuIds === "string" ? new Set([otuIds]) : new Set(otuIds);

			if (wanted.size === 0) {
				return emptyIterator();
			}

			return iterateRows(
				database,
				`${SELECT_SEQUENCES} WHERE isolates.otu_id IN ${IN_ID_SET} ${SEQUENCE_ORDER}`,
				[JSON.stringify([...wanted])],
				SEQUENCE_BATCH_SIZE,
				shapeSequence,
			);
		},

		iterSequences(): AsyncIterableIterator<IndexSequence> {
			return iterateRows(
				database,
				`${SELECT_SEQUENCES} ORDER BY sequences.id`,
				[],
				SEQUENCE_BATCH_SIZE,
				shapeSequence,
			);
		},
	};
}

/**
 * Stream `sequences` to `path` as FASTA, one record per sequence.
 *
 * Written through a stream rather than a joined string: the records are the
 * whole index, and a caller reaching for `writeFile` would hold all of it at
 * once. `pipeline` propagates backpressure, so the SQLite scan is paced by how
 * fast the disk takes the bytes.
 */
export async function writeFasta(
	path: string,
	sequences: AsyncIterable<Pick<IndexSequence, "id" | "sequence">>,
): Promise<void> {
	await pipeline(async function* () {
		for await (const sequence of sequences) {
			yield `>${sequence.id}\n${sequence.sequence}\n`;
		}
	}, createWriteStream(path));
}

async function* iterateRows<T>(
	database: DatabaseSync,
	sql: string,
	parameters: SQLInputValue[],
	batchSize: number,
	shape: (row: Record<string, SQLOutputValue>) => T,
): AsyncGenerator<T> {
	const statement = database.prepare(sql);

	let sinceYield = 0;

	for (const row of statement.iterate(...parameters)) {
		yield shape(row);

		sinceYield += 1;

		if (sinceYield >= batchSize) {
			sinceYield = 0;

			await setImmediate();
		}
	}
}

async function* emptyIterator<T>(): AsyncGenerator<T> {}

function shapeSequence(row: Record<string, SQLOutputValue>): IndexSequence {
	return {
		accession: asString(row, "accession"),
		definition: asString(row, "definition"),
		host: asStringOrNull(row, "host"),
		id: asString(row, "id"),
		isolate_id: asString(row, "isolate_id"),
		otu_id: asString(row, "otu_id"),
		segment: asStringOrNull(row, "segment"),
		sequence: asString(row, "sequence"),
	};
}

/**
 * Python's `_validate_sqlite_otu`.
 *
 * An OTU with no isolates, or an isolate with no sequences, contributes nothing
 * to a FASTA and would otherwise pass silently into a Bowtie2 build that has
 * fewer references than the manifest says.
 */
function checkOtu(otu: IndexOtu): IndexOtu {
	if (otu.isolates.length === 0) {
		throw new IndexOtuIntegrityError(
			`OTU ${otu.id} has no isolates in the index`,
		);
	}

	for (const isolate of otu.isolates) {
		if (isolate.sequences.length === 0) {
			throw new IndexOtuIntegrityError(
				`Isolate ${isolate.id} in OTU ${otu.id} has no sequences in the index`,
			);
		}
	}

	return otu;
}

/**
 * Read one column out of a row, refusing a column the query did not select.
 *
 * The alternative is `String(undefined)`, which writes the literal text
 * `"undefined"` into a FASTA header or a cache key and is discovered as a failed
 * alignment rather than as a missing column. Every accessor below goes through
 * this, so a shaper that drifts from its `SELECT` names the column it wanted.
 */
function column(
	row: Record<string, SQLOutputValue>,
	name: string,
): SQLOutputValue {
	const value = row[name];

	if (value === undefined) {
		throw new IndexOtuIntegrityError(`Index query returned no ${name} column`);
	}

	return value;
}

function asString(row: Record<string, SQLOutputValue>, name: string): string {
	return String(column(row, name));
}

function asStringOrNull(
	row: Record<string, SQLOutputValue>,
	name: string,
): string | null {
	const value = column(row, name);

	return value === null ? null : String(value);
}

function asNumber(row: Record<string, SQLOutputValue>, name: string): number {
	return Number(column(row, name));
}

function asNumberOrNull(
	row: Record<string, SQLOutputValue>,
	name: string,
): number | null {
	const value = column(row, name);

	return value === null ? null : Number(value);
}
