import {
	buildMappingIndexCacheParams,
	canonicalizeCacheParams,
	deriveCacheKey,
	float,
	type RunSubprocess,
} from "@virtool/workflow";
import { describe, expect, it, vi } from "vitest";
import {
	buildTrimmedReadsCacheParams,
	REFERENCE_INDEX_EXTRA_PARAMS,
	REFERENCE_INDEX_KIND,
	SUBTRACTION_INDEX_EXTRA_PARAMS,
	SUBTRACTION_INDEX_KIND,
	WORKFLOW_NAME,
} from "./cacheParams";
import { calculateTrimmingMinLength, getSkewerVersion } from "./skewer";

/**
 * Keys generated by running Python, not by reasoning about the serialization:
 *
 * ```python
 * sha256(json.dumps(params, sort_keys=True, separators=(",", ":"),
 *                   ensure_ascii=True).encode()).hexdigest()
 * ```
 *
 * **Never edit one to match this implementation's output.** A mismatch means the
 * two implementations would derive different keys for the same inputs, and the
 * failure mode is silent — every lookup misses and a second copy is written
 * under a key nothing else asks for.
 */
const PYTHON_KEYS = {
	reference: "24a5b7a2a883c559846c286ca28ae788754b4a2c492c45c3ad24e924a332a636",
	subtraction:
		"cc597e3fb4493a15b44e35fcc65f85f9a9cfcd33ce84946549d47002e29cb0b1",
	trimmed: "281c27841041d174ac635364d404ad98001339aa7732a954798a329eaf47503e",
};

const BOWTIE2_BUILD_VERSION = "2.5.4";
const WORKFLOW_VERSION = "5.2.1";

function subprocessWriting(
	lines: readonly string[],
	{ stream = "stdout" }: { stream?: "stdout" | "stderr" } = {},
): RunSubprocess {
	return vi.fn(async (options) => {
		for (const line of lines) {
			await options[stream]?.(line);
		}

		return {
			command: options.command,
			exitCode: 0,
			signal: null,
			cancelled: false,
			stderrTail: [],
			durationMs: 1,
		};
	});
}

// The params themselves are the runtime's — every workflow that builds a bowtie2
// index derives them the same way. What is pinned here is that *this* workflow's
// inputs to them land on Python-nuvs' key, which is what makes the two
// implementations share the artifact.
describe("the shared mapping index namespaces", () => {
	it("derives Python's key for a reference mapping index", () => {
		const params = buildMappingIndexCacheParams({
			extra: REFERENCE_INDEX_EXTRA_PARAMS,
			indexKind: REFERENCE_INDEX_KIND,
			parentId: 42,
			toolVersion: BOWTIE2_BUILD_VERSION,
			workflow: WORKFLOW_NAME,
			workflowVersion: WORKFLOW_VERSION,
		});

		expect(deriveCacheKey(params)).toBe(PYTHON_KEYS.reference);
	});

	it("derives Python's key for a subtraction mapping index", () => {
		const params = buildMappingIndexCacheParams({
			extra: SUBTRACTION_INDEX_EXTRA_PARAMS,
			indexKind: SUBTRACTION_INDEX_KIND,
			parentId: 7,
			toolVersion: BOWTIE2_BUILD_VERSION,
			workflow: WORKFLOW_NAME,
			workflowVersion: WORKFLOW_VERSION,
		});

		expect(deriveCacheKey(params)).toBe(PYTHON_KEYS.subtraction);
	});

	// Pathoscope builds its reference index off a cd-hit-collapsed FASTA and says
	// so in `source` and `collapse_identity`. Sharing that namespace would restore
	// an index built over different sequences.
	it("keeps the reference index out of pathoscope's namespace", () => {
		const nuvs = buildMappingIndexCacheParams({
			extra: REFERENCE_INDEX_EXTRA_PARAMS,
			indexKind: REFERENCE_INDEX_KIND,
			parentId: 42,
			toolVersion: BOWTIE2_BUILD_VERSION,
			workflow: WORKFLOW_NAME,
			workflowVersion: WORKFLOW_VERSION,
		});

		const pathoscope = buildMappingIndexCacheParams({
			extra: {
				collapse_identity: "0.99",
				selection: "default_isolates",
				source: "collapsed_reference",
			},
			indexKind: REFERENCE_INDEX_KIND,
			parentId: 42,
			toolVersion: BOWTIE2_BUILD_VERSION,
			workflow: "pathoscope",
			workflowVersion: WORKFLOW_VERSION,
		});

		expect(deriveCacheKey(nuvs)).not.toBe(deriveCacheKey(pathoscope));
	});
});

describe("buildTrimmedReadsCacheParams", () => {
	it("derives Python's key for a full trimmed-reads param set", () => {
		const params = buildTrimmedReadsCacheParams({
			minLength: 20,
			mode: "pe",
			sampleId: 42,
			toolVersion: "0.2.2",
			workflowVersion: "3.2.1",
		});

		expect(deriveCacheKey(params)).toBe(PYTHON_KEYS.trimmed);
	});

	// `index_kind` is what the two mapping-index namespaces use. Python's trimmed
	// reads params say `kind`, and matching that spelling is the whole point.
	it("names its discriminator kind, not index_kind", () => {
		const params = buildTrimmedReadsCacheParams({
			minLength: 20,
			mode: "pe",
			sampleId: 42,
			toolVersion: "0.2.2",
			workflowVersion: "3.2.1",
		});

		expect(params.kind).toBe("trimmed_reads");
		expect(params.index_kind).toBeUndefined();
	});

	it("separates a single-end run from a paired one", () => {
		const paired = buildTrimmedReadsCacheParams({
			minLength: 20,
			mode: "pe",
			sampleId: 42,
			toolVersion: "0.2.2",
			workflowVersion: "3.2.1",
		});

		const single = buildTrimmedReadsCacheParams({
			minLength: 20,
			mode: "any",
			sampleId: 42,
			toolVersion: "0.2.2",
			workflowVersion: "3.2.1",
		});

		expect(deriveCacheKey(paired)).not.toBe(deriveCacheKey(single));
	});
});

// The two rates are Python floats, and the marker is what makes an integral one
// serialise as `1.0` rather than `1`. They round-trip identically at their
// defaults, so the marker is invisible today and is the only thing standing
// between the current values and a silent fork the day either becomes a whole
// number.
describe("the float markers on the skewer rates", () => {
	const params = buildTrimmedReadsCacheParams({
		minLength: 20,
		mode: "pe",
		sampleId: 42,
		toolVersion: "0.2.2",
		workflowVersion: "3.2.1",
	});

	it("serialises the default rates the way Python does", () => {
		const canonical = canonicalizeCacheParams(params);

		expect(canonical).toContain('"max_error_rate":0.1');
		expect(canonical).toContain('"max_indel_rate":0.03');
	});

	it("keeps a trailing .0 on an integral rate, where an unmarked number would not", () => {
		expect(
			canonicalizeCacheParams({ ...params, max_error_rate: float(1) }),
		).toContain('"max_error_rate":1.0');

		expect(canonicalizeCacheParams({ ...params, max_error_rate: 1 })).toContain(
			'"max_error_rate":1,',
		);
	});
});

describe("calculateTrimmingMinLength", () => {
	it.each([
		[0, 35],
		[79, 35],
		[80, 100],
		[159, 100],
		[160, 160],
		[301, 160],
	])("maps a maximum read length of %i to %i", (maxLength, expected) => {
		expect(calculateTrimmingMinLength(maxLength)).toBe(expected);
	});
});

describe("getSkewerVersion", () => {
	// Skewer prints `skewer version: 0.2.2`. The colon means the `version\s+`
	// pattern every other tool matches does not, and Python falls through to a
	// bare-number pattern for exactly this reason.
	it("parses a version printed after a colon", async () => {
		const runSubprocess = subprocessWriting([
			"skewer version: 0.2.2",
			"Author: Hongshan Jiang",
		]);

		await expect(getSkewerVersion(runSubprocess)).resolves.toBe("0.2.2");
	});

	it("prefers a labelled version where the output carries one", async () => {
		const runSubprocess = subprocessWriting(["skewer version 0.2.2"]);

		await expect(getSkewerVersion(runSubprocess)).resolves.toBe("0.2.2");
	});

	it("reads the banner from stderr as well as stdout", async () => {
		const runSubprocess = subprocessWriting(["skewer version: 0.2.2"], {
			stream: "stderr",
		});

		await expect(getSkewerVersion(runSubprocess)).resolves.toBe("0.2.2");
	});

	it("throws when the output carries no version", async () => {
		await expect(getSkewerVersion(subprocessWriting([]))).rejects.toThrow(
			"Could not parse skewer version",
		);
	});
});
