apiVersion: batch/v1
kind: Job
metadata:
  name: virtool-migration
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/component: migration
    app.kubernetes.io/part-of: virtool
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: migration
        app.kubernetes.io/component: migration
        app.kubernetes.io/part-of: virtool
    spec:
      restartPolicy: Never
      containers:
        - image: ghcr.io/virtool/internal:latest
          name: virtool-migration
          args: ["migrate"]
          envFrom:
            - configMapRef:
                name: virtool-env
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 800m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 1Gi
