/**
 * `findOrfs` against a golden generated by running Python.
 *
 * The tests in `bio.test.ts` are hand-written: they state what the port is
 * *meant* to do, which is exactly the thing that cannot catch a transliteration
 * that misread the original. This file compares against output Python actually
 * produced, over sequences chosen to exercise the quirks rather than the happy
 * path.
 *
 * The golden was generated with:
 *
 * ```
 * PYTHONPATH=<virtool site-packages> python3 packages/bio/src/fixtures/generateFindOrfs.py
 * ```
 *
 * against `virtool.bio.find_orfs`. **Never edit it to match this
 * implementation's output.** `pos` is stored positionally in every NuVs analysis
 * `results` blob and rendered by the UI, so a divergence here is a divergence in
 * data already written.
 */

import { describe, expect, it } from "vitest";
import { findOrfs } from "./bio";
import golden from "./fixtures/findOrfs.json" with { type: "json" };

type GoldenOrf = {
	frame: number;
	nuc: string;
	pos: number[];
	pro: string;
	strand: number;
};

type GoldenCase = {
	name: string;
	orfs: GoldenOrf[];
	sequence: string;
};

const cases: GoldenCase[] = golden.cases;

describe("findOrfs against Python's find_orfs", () => {
	it.each(cases.map((entry) => [entry.name, entry] as const))(
		"reproduces Python's ORFs for %s",
		(_name, entry) => {
			expect(findOrfs(entry.sequence)).toStrictEqual(
				entry.orfs.map((orf) => ({
					frame: orf.frame,
					nuc: orf.nuc,
					pos: [orf.pos[0], orf.pos[1]],
					pro: orf.pro,
					strand: orf.strand,
				})),
			);
		},
	);

	// A golden that had drifted to all-empty would pass every case above without
	// comparing anything.
	it("covers both strands, all three frames, and the two coordinate quirks", () => {
		const orfs = cases.flatMap((entry) => entry.orfs);

		expect(orfs.length).toBeGreaterThan(20);

		expect(new Set(orfs.map(({ strand }) => strand))).toEqual(new Set([1, -1]));

		expect(new Set(orfs.map(({ frame }) => frame))).toEqual(new Set([0, 1, 2]));

		// The forward-strand end adds the stop codon's three bases unconditionally
		// and then clamps, so an ORF running off the end reports the sequence
		// length.
		expect(
			cases.some((entry) =>
				entry.orfs.some(
					({ pos, strand }) => strand === 1 && pos[1] === entry.sequence.length,
				),
			),
		).toBe(true);

		// The reverse-strand start subtracts three and is never clamped, so an ORF
		// with no stop codon reports a negative start — and `nuc` is then sliced
		// with Python's negative-index semantics.
		expect(orfs.some(({ pos }) => (pos[0] ?? 0) < 0)).toBe(true);
	});

	// The gate is `> 300`, not `>= 300`, so a 300-base sequence yields nothing
	// even though 100 residues would fit in it exactly.
	it("returns nothing at or below 300 bases", () => {
		for (const entry of cases) {
			if (entry.sequence.length <= 300) {
				expect(findOrfs(entry.sequence)).toEqual([]);
			}
		}
	});
});
