"""Core database classes."""

from collections.abc import Callable
from contextlib import asynccontextmanager
from typing import Any

from motor.motor_asyncio import (
    AsyncIOMotorClientSession,
    AsyncIOMotorDatabase,
)
from pymongo import ReturnDocument
from pymongo.errors import DuplicateKeyError

from virtool.mongo.identifier import AbstractIdProvider
from virtool.mongo.utils import id_exists
from virtool.types import Document, Projection
from virtool.utils import ensure_naive_utc


def scrub_naive_utc(value: Any) -> Any:
    """Recursively enforce the naive-UTC datetime invariant on a value to be written.

    Walks nested documents, lists, and tuples, applying :func:`ensure_naive_utc`
    to every datetime encountered. This covers both plain documents and update
    specs whose datetimes are nested under operators (e.g. ``$set``). The value is
    returned unchanged; aware datetimes fail loudly rather than being coerced.

    :param value: the document, update spec, or sub-value to validate
    :return: the value unchanged
    :raises ValueError: if any datetime is aware
    """
    if isinstance(value, dict):
        for item in value.values():
            scrub_naive_utc(item)
    elif isinstance(value, (list, tuple)):
        for item in value:
            scrub_naive_utc(item)
    else:
        ensure_naive_utc(value)

    return value


class Collection:
    """A wrapper for a Motor collection.

    Wraps collection methods that modify the database and automatically dispatches
    websocket messages to inform clients of the changes.

    """

    def __init__(self, mongo: "Mongo", name: str):
        self.mongo = mongo
        self.name = name
        self._collection = mongo.motor_database[name]

        self.aggregate = self._collection.aggregate
        self.bulk_write = self._collection.bulk_write
        self.count_documents = self._collection.count_documents
        self.create_index = self._collection.create_index
        self.delete_many = self._collection.delete_many
        self.delete_one = self._collection.delete_one
        self.distinct = self._collection.distinct
        self.drop_index = self._collection.drop_index
        self.drop_indexes = self._collection.drop_indexes
        self.find_one = self._collection.find_one
        self.find = self._collection.find
        self.rename = self._collection.rename

    async def replace_one(
        self,
        filter: dict,
        replacement: Document,
        *args: Any,
        **kwargs: Any,
    ):
        """Replace a single document, enforcing the naive-UTC datetime invariant."""
        return await self._collection.replace_one(
            filter,
            scrub_naive_utc(replacement),
            *args,
            **kwargs,
        )

    async def update_one(self, filter: dict, update: dict, *args: Any, **kwargs: Any):
        """Update a single document, enforcing the naive-UTC datetime invariant."""
        return await self._collection.update_one(
            filter,
            scrub_naive_utc(update),
            *args,
            **kwargs,
        )

    async def update_many(self, filter: dict, update: dict, *args: Any, **kwargs: Any):
        """Update many documents, enforcing the naive-UTC datetime invariant."""
        return await self._collection.update_many(
            filter,
            scrub_naive_utc(update),
            *args,
            **kwargs,
        )

    async def find_one_and_update(
        self,
        query: dict,
        update: dict,
        projection: Projection | None = None,
        upsert: bool = False,
        session: AsyncIOMotorClientSession | None = None,
    ) -> Document | None:
        """Update a document and return the updated result.

        :param query: a MongoDB query used to select the documents to update
        :param update: a MongoDB update
        :param projection: a projection to apply to the document instead of the default
        :param upsert: insert a new document if no existing document is found
        :param session: an optional Motor session to use
        :return: the updated document

        """
        document = await self._collection.find_one_and_update(
            query,
            scrub_naive_utc(update),
            projection=projection,
            return_document=ReturnDocument.AFTER,
            upsert=upsert,
            session=session,
        )

        if document:
            return document

        return None

    async def insert_one(
        self,
        document: Document,
        session: AsyncIOMotorClientSession | None = None,
    ) -> Document:
        """Insert the `document`.

        If no `_id` is included in the `document`, one will be autogenerated. If a
        provided `_id` already exists, a :class:`DuplicateKeyError` will be raised.

        :param document: the document to insert
        :param session: an optional Motor session to use
        :return: the inserted document

        """
        document = scrub_naive_utc(document)

        if "_id" in document:
            await self._collection.insert_one(document, session=session)
            inserted = document
        else:
            document_id = self.mongo.id_provider.get()

            if await id_exists(self, document_id, session):
                inserted = await self.insert_one(document, session=session)
            else:
                inserted = {**document, "_id": document_id}
                await self._collection.insert_one(inserted, session=session)

        return inserted

    async def insert_many(
        self,
        documents: list[Document],
        session: AsyncIOMotorClientSession,
    ):
        inserted = await self._bulk_set_document_ids(
            [scrub_naive_utc(document) for document in documents],
            session=session,
        )

        await self._collection.insert_many(inserted, session=session)

        return inserted

    async def _bulk_set_document_ids(
        self,
        documents: list[Document],
        session: AsyncIOMotorClientSession = None,
    ) -> list[Document]:
        """Set the `_id` field for each document in ``documents`` that does not already
        have one.

        If a document already has an `_id`, it will be left unchanged. If an `_id`
        provided in ``documents`` is already in use, an ``DuplicateKeyError`` will be
        raised.

        :param documents: the documents to set `_id` fields for
        :param session: an optional Motor session to use
        :return: the documents with `_id` fields set
        """
        ids_already_exists = any("_id" in document for document in documents)

        id_documents = [
            {**document, "_id": document["_id"] or self.mongo.id_provider.get()}
            for document in documents
        ]

        if await self.count_documents(
            {"_id": {"in": [document["_id"] for document in id_documents]}},
            session=session,
        ):
            if ids_already_exists:
                raise DuplicateKeyError

            return await self._bulk_set_document_ids(documents)

        return id_documents


class Mongo:
    def __init__(
        self,
        motor_database: AsyncIOMotorDatabase,
        id_provider: AbstractIdProvider,
    ):
        self.motor_database = motor_database
        self.start_session = motor_database.start_session
        self.id_provider = id_provider

        self.analyses = self.bind_collection("analyses")
        self.history = self.bind_collection("history")
        self.hmm = self.bind_collection("hmm")
        self.indexes = self.bind_collection("indexes")
        self.jobs = self.bind_collection("jobs")
        self.labels = self.bind_collection("labels")
        self.otus = self.bind_collection("otus")
        self.tasks = self.bind_collection("tasks")
        self.references = self.bind_collection("references")
        self.samples = self.bind_collection("samples")
        self.sequences = self.bind_collection("sequences")
        self.status = self.bind_collection("status")
        self.subtraction = self.bind_collection("subtraction")

    def bind_collection(self, name: str) -> Collection:
        return Collection(self, name)

    @asynccontextmanager
    async def create_session(self):
        async with (
            await self.motor_database.client.start_session() as s,
            s.start_transaction(),
        ):
            yield s

    async def with_transaction(self, func: Callable) -> Any:
        """Run the passed async function in a MongoDB transaction."""
        async with await self.motor_database.client.start_session() as s:
            return await s.with_transaction(func)
