post-switch = "python3 {{ primary_worktree_path }}/dev/scripts/coast.py ensure --worktree {{ worktree_path }}"
pre-remove = "python3 {{ primary_worktree_path }}/dev/scripts/coast.py remove --worktree {{ worktree_path }}"

[list]
url = "{{ vars.coasturl | default('') }}"
