import pytest

from virtool.identifier import FakeIdProvider


@pytest.fixture
def id_provider() -> FakeIdProvider:
    """A deterministic id provider shared by the data layer and data faker.

    A single instance is used across the app's data layer, the ``data_layer`` fixture,
    and the ``fake`` fixture so that ids generated by any of them draw from one seeded
    sequence, keeping generated ids stable across test runs.
    """
    return FakeIdProvider()
