import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { createTestWorkPath } from "@virtool/workflow/testing";
import { describe, expect, it, onTestFinished } from "vitest";
import {
	buildFastqcCommand,
	findFastqcDataFile,
	readFastqcReport,
	reduceQuality,
} from "./fastqc";

/**
 * Real FastQC 0.11.9 output, generated by `src/fixtures/generate.sh` from the
 * paired example reads. Never edit one to match what the parser produces.
 */
function fixturePath(mate: 1 | 2): string {
	return join(
		import.meta.dirname,
		"fixtures",
		`paired_${mate}.fastqc_data.txt`,
	);
}

function readFixture(mate: 1 | 2): Promise<string> {
	return readFile(fixturePath(mate), "utf8");
}

/** A directory laid out the way `--extract` leaves one. */
async function seedReport(outputPath: string, mate: 1 | 2): Promise<void> {
	const dataFile = join(outputPath, `paired_${mate}_fastqc`, "fastqc_data.txt");

	await mkdir(dirname(dataFile), { recursive: true });
	await writeFile(dataFile, await readFixture(mate));

	// The zip and the html FastQC writes alongside the directory. They are here
	// so the search has something to skip.
	await writeFile(join(outputPath, `paired_${mate}_fastqc.zip`), "");
	await writeFile(join(outputPath, `paired_${mate}_fastqc.html`), "");
}

describe("buildFastqcCommand", () => {
	it("states the format and extracts, matching Python", () => {
		expect(
			buildFastqcCommand("/work/uploads/left.fq.gz", "/work/fastqc/1"),
		).toStrictEqual([
			"fastqc",
			"-f",
			"fastq",
			"-o",
			"/work/fastqc/1",
			"--extract",
			"/work/uploads/left.fq.gz",
		]);
	});
});

describe("findFastqcDataFile", () => {
	it("finds the report directory and skips the zip and html beside it", async () => {
		const { path: workPath, cleanup } = await createTestWorkPath();

		onTestFinished(cleanup);

		await seedReport(workPath, 1);

		expect(await findFastqcDataFile(workPath)).toBe(
			join(workPath, "paired_1_fastqc", "fastqc_data.txt"),
		);
	});

	it("refuses an output directory holding no report", async () => {
		const { path: workPath, cleanup } = await createTestWorkPath();

		onTestFinished(cleanup);

		await expect(findFastqcDataFile(workPath)).rejects.toThrow(
			"wrote no report directory",
		);
	});

	/**
	 * Two reports in one output directory is the ambiguity the per-read layout
	 * exists to prevent — it is how Python ends up pairing a report with a read
	 * by filesystem order.
	 */
	it("refuses an output directory holding two reports", async () => {
		const { path: workPath, cleanup } = await createTestWorkPath();

		onTestFinished(cleanup);

		await seedReport(workPath, 1);
		await seedReport(workPath, 2);

		await expect(findFastqcDataFile(workPath)).rejects.toThrow(
			"wrote 2 report directories",
		);
	});
});

describe("readFastqcReport", () => {
	it("parses real FastQC 0.11.9 output", async () => {
		const { path: workPath, cleanup } = await createTestWorkPath();

		onTestFinished(cleanup);

		await seedReport(workPath, 1);

		const quality = await readFastqcReport(workPath);

		expect(quality.count).toBe(20000);
		expect(quality.encoding).toBe("Sanger / Illumina 1.9");
		expect(quality.gc).toBe(41);
		expect(quality.length).toStrictEqual([50, 301]);

		// The reads are binned past position 9, and every bin is expanded to one
		// row per position — so there is a row for each of the 301 positions.
		expect(quality.bases).toHaveLength(301);
		expect(quality.composition).toHaveLength(301);
		expect(quality.sequences).toHaveLength(50);
	});
});

describe("reduceQuality", () => {
	it("returns a single report unchanged", async () => {
		const { path: workPath, cleanup } = await createTestWorkPath();

		onTestFinished(cleanup);

		await seedReport(workPath, 1);

		const quality = await readFastqcReport(workPath);

		expect(reduceQuality([quality])).toBe(quality);
	});

	it("composites a pair", async () => {
		const { path: workPath, cleanup } = await createTestWorkPath();

		onTestFinished(cleanup);

		await mkdir(join(workPath, "1"), { recursive: true });
		await mkdir(join(workPath, "2"), { recursive: true });
		await seedReport(join(workPath, "1"), 1);
		await seedReport(join(workPath, "2"), 2);

		const [left, right] = await Promise.all([
			readFastqcReport(join(workPath, "1")),
			readFastqcReport(join(workPath, "2")),
		]);

		const composite = reduceQuality([left, right]);

		expect(composite.count).toBe(left.count + right.count);
		expect(composite.gc).toBe((left.gc + right.gc) / 2);
		expect(composite.encoding).toBe(left.encoding);
		expect(composite.length).toStrictEqual([
			Math.min(...left.length, ...right.length),
			Math.max(...left.length, ...right.length),
		]);
	});

	it("refuses more than two reports", async () => {
		const { path: workPath, cleanup } = await createTestWorkPath();

		onTestFinished(cleanup);

		await seedReport(workPath, 1);

		const quality = await readFastqcReport(workPath);

		expect(() => reduceQuality([quality, quality, quality])).toThrow(
			"Expected 1 or 2 FastQC reports",
		);
	});

	it("refuses no reports", () => {
		expect(() => reduceQuality([])).toThrow("Expected 1 or 2 FastQC reports");
	});
});
