# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot


snapshots = Snapshot()

snapshots['test_import_results[uvloop] 1'] = {
    '_id': 'foobar',
    'nuvs': True,
    'pathoscope': False
}

snapshots['test_import_results[uvloop] 2'] = {
    '_id': 'baz',
    'ready': True,
    'results': [
        {
            'orfs': [
                {
                    'hits': [
                        {
                            'best_bias': 440.3,
                            'best_e': 5e-135,
                            'best_score': 4.5,
                            'full_bias': 4.5,
                            'full_e': 3.9e-135,
                            'full_score': 440.7,
                            'hit': 'bar'
                        }
                    ],
                    'name': 'Foo'
                }
            ]
        },
        {
        },
        {
            'orfs': [
                {
                    'hits': [
                        {
                            'best_bias': 400.7,
                            'best_e': 1.7e-123,
                            'best_score': 0.8,
                            'full_bias': 0.8,
                            'full_e': 1.4e-123,
                            'full_score': 401.0,
                            'hit': 'foo'
                        }
                    ],
                    'name': 'Bar'
                }
            ]
        }
    ],
    'sample': {
        'id': 'foobar'
    },
    'workflow': 'nuvs'
}

snapshots['test_vfam[uvloop] 1'] = {
    'sequences': [
        {
            'orfs': [
                {
                    'hits': [
                        {
                            'best_bias': 440.3,
                            'best_e': 5e-135,
                            'best_score': 4.5,
                            'full_bias': 4.5,
                            'full_e': 3.9e-135,
                            'full_score': 440.7,
                            'hit': 'bar'
                        }
                    ],
                    'name': 'Foo'
                }
            ]
        },
        {
        },
        {
            'orfs': [
                {
                    'hits': [
                        {
                            'best_bias': 400.7,
                            'best_e': 1.7e-123,
                            'best_score': 0.8,
                            'full_bias': 0.8,
                            'full_e': 1.4e-123,
                            'full_score': 401.0,
                            'hit': 'foo'
                        }
                    ],
                    'name': 'Bar'
                }
            ]
        }
    ]
}

snapshots['test_process_fasta[uvloop] 1'] = [
    {
        'index': 0,
        'orfs': [
            {
                'frame': 0,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    831,
                    1257
                ),
                'pro': 'AMTHLAGALECYETRFWAHVQKCLDLTALTYIAGTARGRGAFKNSLGTQAIENASICPINHQVRRSRNTNNTALKIETQIIEVCWSTITIDLKKSIQTFSVNGHPKVNGSQPSVDQLAIISEINTFTPLESINSCIPHGTS',
                'strand': 1
            },
            {
                'frame': 0,
                'hits': [
                ],
                'index': 1,
                'pos': (
                    1791,
                    2106
                ),
                'pro': 'SILAVFSPSTLQEFTLLEGTSIDHRTELICTISDLDSQFFLHVSFNCIAIKCRLNVRVDTQNIVIAVYNQDHVVGKKRSLNLRYKRAISTPNQYLIENRIEVNS',
                'strand': 1
            },
            {
                'frame': 0,
                'hits': [
                ],
                'index': 2,
                'pos': (
                    2772,
                    3111
                ),
                'pro': 'RPGLDETCDGISTTTLESTPTTCTFTLPFGFNGTRDDTGVFKFTITPRITVPNLRRTGGSQFIELPGTGSFNIERGNLIFMMAINGLIHGNHSSSHAHIMEFLGDFITHGCQ',
                'strand': 1
            },
            {
                'frame': 0,
                'hits': [
                ],
                'index': 3,
                'pos': (
                    3111,
                    3453
                ),
                'pro': 'LLIDFLHGMSEFFHTIFVGVVTLTLWHRRKPRVRSTEYCWYFAWYTIHVVLLWDGHKLSLLAVMRLVPPIQPSKFRIAKGGNPSFKIEPSDVGNTCKSINLNVRKFAHICRSP',
                'strand': 1
            },
            {
                'frame': 0,
                'hits': [
                ],
                'index': 4,
                'pos': (
                    4806,
                    5115
                ),
                'pro': 'ILGLFNVLCIVVDARLFYDVCHSRAEIHPILLLILRGLTTLYPYRSFCPIIPLHHAEFSCCSAIMGIKGNSSFPSGLNNYSAASVESLPIMDLGISTGRIAI',
                'strand': 1
            },
            {
                'frame': 0,
                'hits': [
                ],
                'index': 5,
                'pos': (
                    6708,
                    7098
                ),
                'pro': 'CLKRARWQTGFGIPHCLGRAFGPDHKVFRICPAAVNPINGNNQILPSLRGGDAVQETRCLPKAGANETLRKLLHRNRRRWRYHLVLVPLGHFHSRAQSPLRAQTHGIQASPRELACLLPCKGSNTPRLL',
                'strand': 1
            },
            {
                'frame': 1,
                'hits': [
                ],
                'index': 6,
                'pos': (
                    3661,
                    4105
                ),
                'pro': 'SSTNLKCSVRVEKYFTFNASRSESEYIFIACFPREGIRLSKYVQISLSAYSVSAEARHWKVLKLLPATLKPTDEPSGMAWAWCLVMANLLPGTRFTCTAGISLLQVSRRPHSCHFSSCPVSSDQTAGISRERCGMFLRPILAPYSDA',
                'strand': 1
            },
            {
                'frame': 1,
                'hits': [
                ],
                'index': 7,
                'pos': (
                    4759,
                    5107
                ),
                'pro': 'FSHTWYNCLVRLCFIEYWACSMSSALWWTRACSMTYATVVRKSIQYCSLSSGASPLCTHIGVSARSSLSTTQNSAAAVLSWGLKATPAFPRVLITTLRRRLKACRSWILASVPAE',
                'strand': 1
            },
            {
                'frame': 1,
                'hits': [
                ],
                'index': 8,
                'pos': (
                    5743,
                    6298
                ),
                'pro': 'TVPNFSKRYAARAHTASFPRLMPSKDWANLPQYIMVSVLKPVNPEPTAFSAPSTLSTPVQLVAWISSGTKDWFKSTASMVGGHSSTPRKARILAETTARSSHLVRIMPQPSIPRAPDITQPVRVPTRDISRSSFNTFSTKRVHAQVMIITKLTQCVSHMTENSCEPFFNTDWAHSLHLAHSEFT',
                'strand': 1
            },
            {
                'frame': 1,
                'hits': [
                ],
                'index': 9,
                'pos': (
                    6823,
                    7303
                ),
                'pro': 'MGITKSSLRCGEATQFRRPDVSQKLGPTRPSGNSCTETGEGGDTTLFLCLLGTFTVGLKALFVHRRTEYKPAPESWRACCRARAATPLACCEARRIFLQASCLRAVRALCFFASALAILACSAKKLFFNCLPMAGEGGLLLESMPNTHTRRALGKLSRQ',
                'strand': 1
            },
            {
                'frame': 1,
                'hits': [
                ],
                'index': 10,
                'pos': (
                    7303,
                    7642
                ),
                'pro': 'RGPNAFDPFKAPFIRRRASESQGGIAFLVGCVRTALGLSQPVGTRDVPPFEGLRASSAESNSPAWRVLPARAGYTNERRAGDPTSTTTAQSCLRRGAAAFTGLLGRAVGVGA',
                'strand': 1
            },
            {
                'frame': 0,
                'hits': [
                ],
                'index': 11,
                'pos': (
                    7486,
                    7867
                ),
                'pro': 'FNTKQSLQFSFNCSKTDHHGVDLPYPGLCVRSLHLEQSWTKGGWSVLLHALSWGHVWCPSCQVGTRSSSKGFCGTSSPDSHCPPQKASESCSTPAQAGLCCCGRGWVPSPPLVCIPCSCRKNSPCW',
                'strand': -1
            },
            {
                'frame': 0,
                'hits': [
                ],
                'index': 12,
                'pos': (
                    6913,
                    7237
                ),
                'pro': 'PPFSCHRKAVEEEFLGTTSQDCQCTGKETKCTYCTQARGLQEDPPCFTAGEGCCCPCTATSTPALWGWLVFRASVHEEGFEPYCESAQEAQEQGGISTFSCFCAGVS',
                'strand': -1
            },
            {
                'frame': 1,
                'hits': [
                ],
                'index': 13,
                'pos': (
                    708,
                    7908
                ),
                'pro': 'SQSHCYNSLVSIFDLIQSKVYSFLLIVQKLITMGWTCPIQGCVYARSTWSNRGLKEDGLSSSMRCPGAMCGALLVRSEPVQVPKVSVAPQAPTPTALPKRPVKAAAPLRRQDCAVVVEVGSPALLSFVYPALAGRTRHAGEFDSALLARRPSNGGTSRVPTGWLKPRAVRTQPTRKAIPPWLSEARRLIKGALKGSNAFGPRYCRDNFPRARLVWVLGMLSKSSPPSPAIGRQLKKSFLALQARIASALAKKQSARTARRQEACRKIRLASQQARGVAALARQQARQLSGAGLYSVRLCTKRALSPTVKVPKRHKNKVVSPPSPVSVQEFPEGLVGPSFWETSGLLNCVASPQRREDLVIPIYGIDSCRTDPENFVVGPKSPSQAMGDAKPRLPTCPLEALNLLWASNLFEDWELDIIGQMVSDGLLTSQAFLDGCTLVSYYGQEQMVDSFHCLLQDPVPTEVAEALAVDVQALDFDAVFGCGISDFLRGTRDAIRGWIMDPVIAKSTTWCNTIIDKVRALFDKYFAPFHKIIDGMSYVNSLWAKCKEWAQSVLKNGSQLFSVMWETHCVSFVIIITCACTLLVENVLKELRLISRVGTLTGCVISGALGILGCGMILTKCEDLAVVSASIRAFLGVLLCPPTMEAVDLNQSLVPEEIQATSWTGVDRVLGALNAVGSGLTGFNTDTIIYWGRFAQSFDGMRRGKDAVCALAAYLFEKLGTVYNRVTGKEAAFFHELSSLVSIDVQGWLNSSRKVMAESIAFAKSDAVAFATVERLINDGETIQLTAASAPKSHSMQFGQILAERLRELRTLRNDMAHAGSFEGRRCVPFWLYIYGPPGVGKTTTMHEFSQALLTAFEFPSDSLTSKSATDKYWSLYRRQALVQIDDLGAISESGMEQEMMNIVSSATYNPTMAVANEKTTLFDSKFIVSTSNGYSAGTDAKIHDRQAFNRRRRVVIKTRGKAGVAFNPHDSTAAAEFCVVERDDRAETPIWVQSGEAPEDKEQYWMDFRTTVAYVIEQARVHHNAEDIEQAQYSMKHSRTRQLYQVCENYIGEVKMSIANFVPGDMLGAWNLEPKGRFFYSCVDGRVYSYDPEQKAHDEGPVDKTLDFEQICLEKLSYTLQADIQGGPKSATAGIFLRSMVSGECAVESVDKLNKGASREHLIFFKNLSLADRVYLRLVQKRILQLAMVGDPLGVRSYTVMMEGFQNSYNYVKENGGRLLLILCSCMLLGIACYTFFNALAVLIGGTSVAAGAAAMVDIGACGSTSTYASEYGAKMGRRNMPHRSREIPAVWSEETGHDEKWQLCGLLETCRSDMPAVHVNLVPGNKFAITKHQAQAIPDGSSVGLSVAGRSFRTFQWRASALTEYAESEICTYFDSRIPSLGKQAMKMYSDSDLDALNVKYFSTRTLHFRLVDDQVEKRHWDADACVISTPKTIVSTINGVIYRQEIPTAITYRRESVKHDCGALVFTEVRGKPKAVGMLVGTLGGTTYVCKFPHIEVDAFACVPDIRGFNLEAGVSTLGYSKLGWLDRRHQPHNSEKTEFVPIPEKYHMDGVPCKIPAILSASDPRLASVPQSKGYDPYKNGMEKFAHPMQEIDEQLLATVCDEIAQEFHDVGVRGRMVSMDEAINGHHKYEIPSFYVEGASTRELNELRTSCSTEVWHCDPGSDCEFEYPRVIPGPVESKWKCESTCCGSTFKSGGTDAITSFVKARSSCCEEIFFDGLDLTTSEGYPLFLDRPAGAKGKERFFEGSDNQKFLIPGCPLDVQLQKGIEETHLGTPQLIIKESAKDELLREGKVLPSEGMPGTRLFSICPAWYNIAVRQHFVYIAESVRKRRRTLSSQVGIVVGSREWDDLAARLRSKKNDKMYCCDYSKFDGLMTPQIIHAITNIYERMFSGKDGMSQFRQNLLMGICNRISICGSQVYRVEAGMPSGFALTVDFNSIFNEILVRCAYRSLVPEIERPFFSNNVVLIVYGDDNVLGIHPNVESAFNGNTIKAYMKEELGIKITDGADKLSPVIDARPLEQCEFLKRTWRKDRQYGLYRAPLVETSIYSCLRYVRLQNYDWQAPLLQNVQGSLYEASLHGPEMHARIYTHFAVHFPKWVEEHELYTYEQCRTRFIAAKNGDFNFHPASAQMGHVFSQQTEIQELSQPQNPKRCYQLHEKIHICGPGHNENDCFYVDVRVKGKITKGKGFHHAPVFSAGSGQLGTVKWASSFRSSSACPMRDAAVDAFKRGECIYFRDNGELINAWLAAINFGMSINAEGLDGLLQVYRNCGPTHLDDLSFYFEGGVVGVPAPAHLMVYGTDTSILNRLCPKTVLESAPPPGRSSNVSERCQVQTFLHMSPKPCFITLKGSSKVCHGLRCSDSCRGHISCTDVVRNSVANQRAAMLDVLRRGCYNIQ',
                'strand': -1
            },
            {
                'frame': 2,
                'hits': [
                ],
                'index': 14,
                'pos': (
                    2732,
                    3449
                ),
                'pro': 'GERHMCANFLTLRLMLLHVFPTSEGSILKLGFPPLAILNLDGWIGGTSRITARRLSLCPSQRSTTWMVYHAKYQQYSVLLTRGLRLCHRVRVTTPTKMVWKNSLIPCKKSMSNYWQPCVMKSPRNSMMWACEEEWFPWMRPLMAIINMRFPRSMLKEPVPGSSMNCEPPVLRRFGTVIRGVIVNLNTPVSSLVPLNPNGSVKVHVVGVLSRVVVLMPSQVSSRPGLHVVRKFSSMVLT',
                'strand': -1
            },
            {
                'frame': 2,
                'hits': [
                ],
                'index': 15,
                'pos': (
                    1361,
                    1823
                ),
                'pro': 'SVLGEKTASMDYTGLHSWKLVYIHAYVMYAFRIMTGRLPFCRMSKGAFMRPVYMVPKCTRVFTHILQCISQSGWKSMNCTLMNSVARGSLLLRMEISISIQLLLKWDMFSPNRLRFRSYLSLKIQRDVTNSTKKSTFVVPDIMKMTVFTLMSG',
                'strand': -1
            }
        ],
        'sequence': 'GTTCGGACAGAACGACACTAAGGAAGCTTAAGAACAAAACTAAATGCATATTTTTGTGTGCTTGCTAAAGGCACGACCTCAGAGAGGGAGCTACAGAAAGAAAACTAACTATGACTCAAAGCATTAAAACAGATAATCTCGGCTTATTATGCCTACGGAACAAGCCGTAGCACACCTTTACACCACCGACTCTGCAATCGGCTCCAATTTTCTGATAAACTGGAAAACTCGTCATACTGCTCTGGGACGTCACCACCAGAAGAAAGACATTTAACAGTACCGCTGAACCTACAAGCTGTCTAGACTCATAGGGGCCATGTGTAAAACACAAACTCACATGGCACAGCTTTAGTTGGCTCAATTAACCCGGAGCCGAAGGGTTGCTCTCACACCTTAGAAACTGAGTTTCAGAGAGTTGCCACATACCGATTTCACGGAACCCTATCAATAGGGTATCTACTTCATTCGCCCCCAAAGCGTCGTAGAGTTTGGCACTTGTCTGATTACCGATTTCACGGAACATATAGTATCAGGATTTTGGTGTGATTCCAGCATGTTTCCTTCTCGGTGAAACTAACCGATTATTCTTCCTAAAAAAAAGAAAAGAAATATATACAGGATAGATGGCAGTAAGATGCCAGCTAAAACCACGTAGTTCCGTGGTAGCAGCACACGAAGTCTGCCGGCTTGCCTAAAAACACCCAGCTCCTACTGGATATTGTAACAACCTCTCCTCAGCACATCCAACATTGCGGCCCGCTGATTGGCCACAGAATTGCGAACCACATCAGTACATGAAATGTGGCCGCGACACGAGTCACTGCAGCGTAGGCCATGACACACCTTGCTGGAGCCCTTGAGTGTTATGAAACAAGGTTTTGGGCTCATGTGCAGAAATGTTTGGACCTGACAGCGCTCACTTACATTGCTGGAACGGCCAGGGGGAGGGGCGCTTTCAAGAACAGTCTTGGGACACAAGCGATTGAGAATGCTAGTATCTGTCCCATAAACCATCAAGTGCGCAGGAGCAGGAACACCAACAACACCGCCCTCAAAATAGAAACTCAAATCATCGAGGTGTGTTGGTCCACAATTACGATAGACTTGAAGAAGTCCATCCAAACCTTCAGCGTTAATGGACATCCCAAAGTTAATGGCAGCCAACCAAGCGTTGATCAACTCGCCATTATCTCTGAAATAAATACATTCACCCCGCTTGAAAGCATCAACAGCTGCATCCCGCATGGGACAAGCTGAGGATGAGCGGAATGATGATGCCCATTTAACAGTACCAAGTTGGCCAGAACCTGCAGAGAACACAGGTGCATGGTGGAAGCCCTTACCCTTGGTAATCTTTCCTTTCACCCGGACATCAACGTAAAAACAGTCATTTTCATTATGTCCGGGACCACAAATGTGGATTTTTTCGTGGAGTTGGTAACATCTCTTTGGATTTTGAGGCTGAGATAACTCCTGAATCTCAGTCTGTTGGGAGAAAACATGTCCCATTTGAGCAGAAGCTGGATGGAAATTGAAATCTCCATTCTTAGCAGCAATGAACCGCGTGCGACACTGTTCATAAGTGTACAGTTCATGCTCTTCCACCCACTTTGGGAAATGCACTGCAAAATGTGTGTAAATACGCGCGTGCATTTCGGGACCATGTAGACTGGCCTCATAAAGGCTCCCTTGGACATTCTGCAAAAGGGGAGCCTGCCAGTCATAATTCTGAAGGCGTACATAACGTAGGCATGAATATATACTAGTTTCCACGAGTGGAGCCCGGTATAATCCATACTGGCGGTCTTTTCTCCAAGTACGCTTCAGGAATTCACACTGCTCGAGGGGACGAGCATCGATCACAGGACTGAGCTTATCTGCACCATCAGTGATCTTGATTCCCAATTCTTCCTTCATGTAAGCTTTAATTGTATTGCCATTAAATGCAGACTCAACGTTCGGGTGGATACCCAAAACATTGTCATCGCCGTATACAATCAAGACCACGTTGTTGGAAAAAAAAGGTCTCTCAATCTCAGGTACAAGAGAGCGATAAGCACACCTAACCAGTATCTCATTGAAAATAGAATTGAAGTCAACAGTTAAAGCAAACCCGGAGGGCATGCCAGCTTCAACTCTGTAAACTTGTGAGCCACAGATAGAGATACGGTTACAGATACCCATCAGTAGGTTCTGTCGGAACTGACTCATCCCATCTTTACCACTAAACATCCTCTCATAGATATTTGTGATAGCATGAATAATTTGGGGAGTCATCAGCCCATCAAATTTGGAATAATCGCAGCAATACATTTTGTCATTTTTCTTCGACCTAAGTCGTGCTGCTAGATCATCCCATTCCCGGGAACCAACGACAATTCCCACCTGGCTAGACAAAGTACGTCGTCGCTTGCGCACACTCTCAGCAATATATACAAAGTGTTGGCGCACAGCAATGTTGTACCACGCTGGACAAATGGAGAACAATCGCGTTCCCGGCATCCCCTCGGAAGGCAAAACCTTCCCTTCTCTAAGTAGCTCATCCTTAGCACTCTCTTTGATGATCAATTGTGGCGTGCCAAGGTGAGTCTCCTCAATACCCTTCTGTAGCTGTACGTCTAGTGGGCAACCAGGTATGAGGAACTTTTGGTTGTCGCTACCCTCAAAAAATCTTTCCTTTCCTTTTGCCCCAGCTGGGCGATCCAGGAAAAGAGGGTAGCCCTCAGAAGTGGTTAGGTCAAGACCATCGAAGAAAATTTCCTCACAACATGAAGACCGGGCCTTGACGAAACTTGTGATGGCATCAGTACCACCACTCTTGAAAGTACTCCCACAACATGTACTTTCACACTTCCATTTGGATTCAACGGGACCAGGGATGACACGGGGGTATTCAAATTCACAATCACTCCCCGGATCACAGTGCCAAACCTCCGTAGAACAGGAGGTTCGCAATTCATTGAGCTCCCTGGTACTGGCTCCTTCAACATAGAACGAGGGAATCTCATATTTATGATGGCCATTAATGGCCTCATCCATGGAAACCATTCTTCCTCGCACGCCCACATCATGGAATTCCTGGGCGATTTCATCACACACGGTTGCCAATAATTGCTCATCGATTTCTTGCATGGGATGAGCGAATTTTTCCATACCATTTTTGTAGGGGTCGTAACCCTTACTCTGTGGCACAGACGCAAGCCGCGGGTCAGAAGCACTGAGTATTGCTGGTATTTTGCATGGTACACCATCCATGTGGTACTTCTCTGGGATGGGCACAAACTCAGTCTTCTCGCTGTTATGCGGCTGGTGCCGCCTATCCAACCATCCAAGTTTAGAATAGCCAAGGGTGGAAACCCCAGCTTCAAGATTGAACCCTCGGATGTCGGGAACACATGCAAAAGCATCAACCTCAATGTGAGGAAATTTGCACACATATGTCGTTCCCCCTAAAGTACCCACCAACATGCCTACAGCCTTTGGTTTGCCACGCACTTCTGTAAAAACGAGTGCACCACAATCATGCTTCACGCTTTCACGTCTGTACGTAATAGCTGTAGGTATCTCTTGCCGATATATCACCCCATTAATGGTAGAAACAATGGTCTTTGGGGTTGATATAACACATGCATCCGCATCCCAATGACGTTTCTCGACTTGATCGTCCACCAACCTAAAATGCAGTGTGCGAGTCGAAAAGTATTTCACATTCAACGCATCAAGATCAGAATCCGAATACATTTTCATAGCTTGTTTCCCAAGGGAAGGAATTCGACTATCGAAATATGTACAGATCTCACTTTCAGCATATTCTGTGAGCGCCGAGGCGCGCCACTGGAAAGTCCTAAAACTTCTCCCTGCTACACTCAAACCCACAGATGAACCATCTGGAATGGCCTGGGCTTGGTGCTTGGTTATGGCAAATTTATTACCTGGTACAAGGTTCACATGTACAGCAGGCATATCGCTTCTGCAGGTCTCCAGAAGACCACACAGTTGCCATTTCTCGTCGTGTCCGGTTTCTTCAGACCAGACTGCAGGAATTTCCCGGGAGCGATGTGGCATGTTCCTACGGCCCATCTTAGCGCCGTATTCTGATGCATAGGTAGAAGTGCTACCACACGCTCCAATATCCACCATAGCAGCTGCGCCAGCAGCCACTGAAGTGCCACCAATGAGTACTGCCAAAGCATTGAAAAAAGTGTAGCAGGCAATACCCAACAACATGCAACTACAAAGTATTAACAAAAGTCTTCCTCCATTCTCCTTGACATAATTGTAAGAATTTTGGAATCCCTCCATCATTACAGTGTAGCTCCTCACTCCCAGAGGATCCCCGACCATCGCAAGCTGTAAAATTCGCTTTTGCACGAGGCGGAGATACACCCTATCAGCCAAGGATAAGTTTTTGAAAAAAATAAGGTGTTCCCGTGACGCTCCCTTATTCAACTTATCCACACTCTCCACAGCACATTCTCCCGAAACCATTGACCGCAAAAAAATACCAGCAGTCGCAGATTTAGGGCCACCCTGAATATCGGCTTGCAGGGTGTAGGAGAGCTTTTCCAAACAAATCTGCTCGAAATCTAGGGTCTTATCGACCGGTCCCTCATCATGGGCCTTCTGCTCGGGATCATAGGAATAAACCCGACCATCAACACATGAATAGAAGAACCTGCCTTTAGGCTCTAAATTCCAAGCTCCCAACATGTCCCCAGGTACAAAATTTGCAATGGACATCTTCACTTCCCCAATGTAGTTCTCGCACACCTGGTACAATTGTCTTGTCCGGCTGTGTTTCATTGAATACTGGGCTTGTTCAATGTCCTCTGCATTGTGGTGGACGCGCGCTTGTTCTATGACGTATGCCACAGTCGTGCGGAAATCCATCCAATATTGCTCCTTATCCTCAGGGGCCTCACCACTCTGTACCCATATAGGAGTTTCTGCCCGATCATCCCTCTCCACCACGCAGAATTCAGCTGCTGCAGTGCTATCATGGGGATTAAAGGCAACTCCAGCTTTCCCTCGGGTCTTAATAACTACTCTGCGGCGTCGGTTGAAAGCTTGCCGATCATGGATCTTGGCATCAGTACCGGCAGAATAGCCATTTGACGTAGAAACAATGAACTTACTATCGAAAAGCGTCGTCTTTTCGTTAGCAACTGCCATAGTAGGATTGTATGTTGCAGAGGAAACGATATTCATCATCTCCTGTTCCATGCCACTTTCAGAGATAGCACCCAGGTCATCAATCTGCACCAGGGCCTGGCGCCGATAGAGTGACCAGTACTTATCAGTGGCACTTTTGGATGTTAGGGAATCTGAAGGAAACTCAAAAGCTGTCAACAGGGCCTGCGAAAACTCGTGCATAGTGGTGGTTTTACCCACCCCTGGAGGTCCGTAAATGTACAACCAAAAAGGTACACACCTACGCCCCTCGAAAGAGCCAGCATGAGCCATGTCATTCCGTAAAGTACGGAGTTCCCTCAGACGCTCAGCAAGGATCTGACCAAACTGCATGGAATGGGACTTTGGAGCAGAAGCAGCGGTCAGCTGGATGGTTTCACCATCGTTTATCAACCTCTCCACAGTAGCAAAGGCAACAGCATCTGACTTAGCGAAAGCTATAGATTCTGCCATCACCTTGCGTGAGGAGTTCAACCATCCTTGGACATCAATGGAAACGAGTGAGGAGAGCTCATGGAAAAAAGCTGCCTCCTTACCCGTTACACGATTGTAAACAGTGCCCAATTTCTCAAAAAGATATGCTGCGAGAGCACACACAGCATCCTTTCCTCGTCTCATGCCGTCAAAAGATTGGGCAAATCTGCCCCAGTATATTATGGTGTCTGTATTGAAACCTGTCAATCCAGAACCAACGGCATTCAGTGCACCAAGCACTCTGTCAACACCAGTCCAGCTTGTAGCTTGGATTTCCTCAGGGACCAAGGACTGGTTTAAATCCACTGCTTCCATGGTTGGAGGACACAGTAGCACGCCGAGAAAGGCTCGAATACTAGCAGAAACCACGGCAAGATCCTCGCATTTGGTGAGAATCATGCCGCAGCCAAGTATTCCGAGGGCTCCAGATATAACACAGCCAGTAAGAGTACCAACACGTGATATCAGCCGGAGTTCTTTCAACACATTCTCCACCAAAAGGGTACATGCGCAGGTTATGATAATAACAAAACTCACGCAATGTGTTTCCCACATGACAGAGAACAGTTGTGAACCATTCTTCAACACAGACTGGGCCCACTCCTTGCATTTAGCCCACAGTGAATTTACATAGGACATACCATCAATGATCTTGTGGAAAGGTGCAAAGTATTTATCAAATAAAGCACGCACCTTATCAATGATGGTGTTACACCAGGTCGTCGACTTGGCAATTACTGGATCCATAATCCATCCTCTTATGGCATCACGTGTTCCCCGAAGGAAATCCGAGATACCACATCCGAAGACAGCATCAAAATCCAGAGCTTGCACATCGACAGCCAGTGCCTCAGCAACCTCAGTAGGGACAGGATCTTGCAGCAGACAATGAAAAGAGTCCACCATCTGCTCCTGGCCGTAATAAGAAACCAGGGTACAACCATCCAGGAAGGCTTGTGAGGTCAACAAACCATCCGAAACCATCTGCCCAATGATATCAAGCTCCCAATCCTCAAAAAGATTAGAAGCCCACAGCAAATTTAATGCCTCAAGAGGGCACGTTGGCAGACGGGGTTTGGCATCCCCCATTGCTTGGGAAGGGCTTTTGGGCCCGACCACAAAGTTTTCCGGATCTGTCCGGCAGCTGTCAATCCCATAAATGGGAATAACCAAATCCTCCCTTCGCTGCGGGGAGGCGACGCAGTTCAGGAGACCAGATGTCTCCCAAAAGCTGGGGCCAACGAGACCCTCAGGAAACTCCTGCACAGAAACAGGAGAAGGTGGAGATACCACCTTGTTCTTGTGCCTCTTGGGCACTTTCACAGTAGGGCTCAAAGCCCTCTTCGTGCACAGACGCACGGAATACAAGCCAGCCCCAGAGAGCTGGCGTGCTTGTTGCCGTGCAAGGGCAGCAACACCCCTCGCCTGCTGTGAAGCAAGGCGGATCTTCCTGCAGGCCTCTTGCCTGCGTGCAGTACGTGCACTTTGTTTCTTTGCCAGTGCACTGGCAATCCTGGCTTGTAGTGCCAAGAAACTCTTCTTCAACTGCCTTCCGATGGCAGGAGAAGGGGGGCTACTCTTAGAGAGCATGCCCAACACCCACACAAGGCGGGCCCTCGGGAAATTATCCCGGCAGTAGCGAGGACCGAACGCATTCGATCCTTTTAAGGCCCCCTTTATCAGGCGGCGGGCCTCAGAAAGCCAGGGAGGGATTGCCTTCCTGGTAGGCTGTGTGCGCACAGCCCTCGGCTTAAGCCAGCCGGTCGGCACTCGAGATGTGCCCCCATTTGAGGGCCTTCGCGCGAGTAGCGCGGAATCAAACTCACCAGCATGGCGAGTTCTTCCTGCAAGAGCAGGGTATACAAACGAGAGGAGGGCTGGGGACCCAACCTCTACCACAACAGCACAATCCTGCCTGCGCAGGGGTGCTGCAGCTTTCACTGGCCTTTTGGGGAGGGCAGTGGGAGTCGGGGCTTGAGGTGCCACAGAAACCTTTGGAACTTGAACGGGTTCCGACCTGACAAGAAGGGCACCACACATGGCCCCAGGACAGCGCATGGAGGAGGACAGACCATCCTCCTTTAGTCCACGATTGCTCCAAGTGGAGCGAGCGTACACACAGCCCTGGATAGGGCAAGTCCACCCCATGGTGATCAGTTTTTGAACAATTAAAAGAAAACTGTAAACTTTGCTTTGTATTAAATCAAAGATAGAGACAAGAGAGTTGTAACAATGAGACTGAGAT'
    },
    {
        'index': 1,
        'orfs': [
            {
                'frame': 0,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    3480,
                    3822
                ),
                'pro': 'CFRLLDSRHLGCSTPPLRLAARRLYCSPTTPFSRFRLLPFRSPLLRESLLLSFPLATKMFQFARLSLACPWIKQQFERLTYSGISGSTLIFNSPKHFVAYYALPRLWVPRYPP',
                'strand': 1
            },
            {
                'frame': 0,
                'hits': [
                ],
                'index': 1,
                'pos': (
                    6894,
                    7299
                ),
                'pro': 'VSFLRTYSPGGILNALATALHGSIRTAPSIHRLRLGLLGYLIPFAPLAFVSQCQCRPSRVLSPLVFFPISTHFTAPPEIPSAPTVLQLGSFHRLSRVEPWDLTADLKSHLQTLYAQSFRITLASSVLPRLLAQS',
                'strand': 1
            },
            {
                'frame': 1,
                'hits': [
                ],
                'index': 2,
                'pos': (
                    772,
                    1171
                ),
                'pro': 'IMKIDGECLIELIVSCRNKVQVYRSVRMPQLHTSLHFHLTPIVMINGSSRRDLLLNSQNFCRSTPAGAENPSLSWLCYRRLWGSRNRRALILGWAYYLDAFSSYPLRTWLPSVYRGHDNWYTRGASFPVLSY',
                'strand': 1
            },
            {
                'frame': 1,
                'hits': [
                ],
                'index': 3,
                'pos': (
                    1912,
                    2383
                ),
                'pro': 'LRPPFTGASVAGSPVIRSPTSLTFRHWAGVSPHTWSYDFAETCVFGKQSPGPGHCDPLCEGAPLLPKLRGYFAEFLRESCLAPLGILYLPTCVGFGYRYPFVEGRSSFSWEYGMGYFSAVAPGTRTLARGIFSTPSYPEKSGAPRVLEPITIFRLT',
                'strand': 1
            },
            {
                'frame': 1,
                'hits': [
                ],
                'index': 4,
                'pos': (
                    2515,
                    2821
                ),
                'pro': 'VFGALDSHQCLRYSSRHSRFRFVHRRSRGCFPLGGTLPYRCIFTSHSFGRSLSPVHLRRKSARSVSYYALFQGWLLLGKPPGCLCTPTSFITERSFRGLSW',
                'strand': 1
            },
            {
                'frame': 2,
                'hits': [
                ],
                'index': 5,
                'pos': (
                    2747,
                    3110
                ),
                'pro': 'ANLLAVSAPLPPLSLSGHLGALAGDPGCFPLDDEAYPPSSHWPTLTPVILRSYLVFRVCLDLVPLSRPAPKQCFTPRCPVNCCASTHFGENQLALGSSGISPLTTTHPLILQHQSVRTST',
                'strand': 1
            },
            {
                'frame': 2,
                'hits': [
                ],
                'index': 6,
                'pos': (
                    6185,
                    6509
                ),
                'pro': 'LRRSSLLFGCEAVSNQNTQQALALPEKEVIQPHLPVRLPCYDFTPVTSPAFGIPPLAVKVTTSGMASSHSVTGGVYKARERIHRRMADRRLLAIPASCRRVAAYNPN',
                'strand': 1
            },
            {
                'frame': 0,
                'hits': [
                ],
                'index': 7,
                'pos': (
                    3875,
                    4241
                ),
                'pro': 'LDPPEPQESLVRMGFQLSTFPFEILRRVALWRAQYDESCKLCSGGSYCLSLASMVESVGGLRGGSLPCGGCQRFESAYLQLANLADTKLYDSTQFFRFGSSIYAMIYHSWTLIRSFHLAAP',
                'strand': -1
            },
            {
                'frame': 0,
                'hits': [
                ],
                'index': 8,
                'pos': (
                    1073,
                    1430
                ),
                'pro': 'SDGAEWKGRRSTDKSYSRDNRLIFPKSSHRREGLAPRCRLFATWGCSMFQGLGCSPIKAVRELGSERRETVRSISGVGVRALRGPFPSTRGPGRTHLWCTSYRAHGKRWVAKCGADNC',
                'strand': -1
            },
            {
                'frame': 1,
                'hits': [
                ],
                'index': 9,
                'pos': (
                    5248,
                    5572
                ),
                'pro': 'QRIFTDQELRDRPFHSGVTEGSYHSSLFFHAFPGGLEKAAINRIFLILPSRKEEREIFFSFRRDQEIVSSRKKNAWLINNSLLGLRPPQSLRTPPISAMGCVYLSIS',
                'strand': -1
            }
        ],
        'sequence': 'GGCCATTCCATTTCGACAAAAGACCCACGCCCAAATTCCATAGCTTTGGGTCCGCTATCCCGATCATGATTTTCCTACCCCCAAAGGGAAAGGTCCTTCCCTTTTTGGCCGGTTGTGGGCGAGGAGGGATTCGAACCCCCGACACCGTGGTTCGTAGCCACTTGCTCTAATCCTCTGAGCTACAGGCCCCACCCCGTCTCCACTGGATCTGTTCCCGGGAGTACCCTAAAAAAAAGGAACCTTTCCTCTCCCCAGCCGTTTCCGGTTAAGAAGATGTGAAAGCGCCTCTCTCTATATATATAAATATAAGAACGGTGCGTTCCGAGGTGTGAAGTGGGAGAGAAGGGATTTCATAATTGGATTGGGGTTTTGAATAAGACGACCTTTTCATTTTTTTTTTTTTTATTTTTGAATTTGAAAAAGTAATAAGAATGAGAGGTGTTAAGCTTTTTATCATCCTGGCGTCGAGCTATTTTTCCGCAGGACCTCCCCTACAGTATCGTCACCGCAGTAGAGTTTAACCACCAAGTTCGGGATGGATTGGTGTGGTTCCTCTACGCCTAGGACACCAGAATATCGAACCATGAACGAAGAAAGGCATGAGAGAAAAGCATATTGGCTAGTGATTGTGAGGCCAAAATTCTTGACTGGAGGGGACACCAAAGGCCTCCGCCCTTCCATCCCTTGGATAGATAGAGGGGAGGGCAGAGCTTTTGGTTTTTCATGTTGTCAAAGAGTTGAACAATGGTTTTTCGTGTTGTCAAAGAGTTGAATAATGAAAATAGATGGCGAGTGCCTGATCGAATTGATCGTGTCATGTAGGAACAAGGTTCAAGTCTACCGGTCTGTTAGGATGCCTCAGCTGCATACATCACTGCACTTCCACTTGACACCTATCGTAATGATAAACGGCTCGTCTCGCCGTGACCTTCTCTTGAATTCTCAAAACTTCTGTCGCTCCACCCCCGCAGGGGCAGAAAACCCATCGCTGTCTTGGCTGTGCTACCGGAGGCTCTGGGGAAGTCGGAATAGGAGAGCACTCATCTTGGGGTGGGCTTACTACTTAGATGCTTTCAGCAGTTATCCGCTCCGCACTTGGCTACCCAGCGTTTACCGTGGGCACGATAACTGGTACACCAGAGGTGCGTCCTTCCCGGTCCTCTCGTACTAGGGAAAGGTCCTCTCAATGCTCTAACGCCCACACCGGATATGGACCGAACTGTCTCACGACGTTCTGAACCCAGCTCACGTACCGCTTTAATGGGCGAACAGCCCAACCCTTGGAACATACTACAGCCCCAGGTGGCGAAGAGCCGACATCGAGGTGCCAAACCTTCCCGTCGATGTGAGCTCTTGGGGAAGATCAGCCTGTTATCCCTAGAGTAACTTTTATCCGTTGAGCGACGGCCCTTCCACTCGGCACCGTCGGATCACTAAGGCCGACTTTCGTCCCTGCTCGACGGGTGGGTCTTGCAGTCAAGCTCCCTTCTGCCTTTGCACTCGAGGGCCAATCTCCGTCTGGCCCGAGGAAACCTTTGCACGCCTCCGTTACCTTTTGGGAGGCCTACGCCCCATAGAAACTGTCTACCTGAGAATGTCCCTTGGCCCGTAGGTCCTGACACAAGGTTAGAATTCTAGCTCTTCCAGAGTGGTATCTCACTGATGGCTCGGGCCCCCCCGGAAGGGGGCCTTCTTCGCCTTCCACCTAAGCTGCGCAGGAAAGGCCCAAAGCCAATCCCAGGGAACAGTGAAGCTTCATAGGGTCTTTCTGTCCAGGTGCAGGTAGTCCGCATCTTCACAGACATGTCTATTTCACCGAGCCTCTCTCCGAGACAGTGCCCAGATCGTTACGCCTTTCGTGCGGGTCGGAACTTACCCGACAAGGAATTTCGCTACCTTAGGACCGTTATAGTTACGGCCGCCGTTCACCGGGGCTTCGGTCGCCGGCTCCCCTGTCATCAGGTCACCAACTTCCTTGACCTTCCGGCACTGGGCAGGCGTCAGCCCCCATACATGGTCTTACGACTTTGCGGAGACCTGTGTTTTTGGTAAACAGTCGCCCGGGCCTGGTCACTGCGACCCCCTTTGTGAGGGGGCACCCCTTCTCCCGAAGTTACGGGGCTATTTTGCCGAGTTCCTTAGAGAGAGTTGTCTCGCGCCCCTAGGTATTCTCTACCTACCCACCTGTGTCGGTTTCGGGTACAGGTACCCTTTTGTTGAAGGTCGTTCGAGCTTTTCCTGGGAGTATGGCATGGGTTACTTCAGCGCCGTGGCGCCTGGTACTCGAACATTGGCTCGAGGCATTTTCTCTACCCCTTCTTACCCTGAAAAATCAGGGGCACCCCGCGTCCTTGAACCGATAACCATCTTTCGGCTAACCTAGCCTCCTCCGTCCCTCGGGACCAACAAGGGGTAGTACAGGAATATTCACCTGTTGTCCATCGACTACGCCTTTCGGCCTGATCTTAGGCCCTGACTCACCCTCCGTGGACGAACCTTGCGGAGGAACCCTTAGGTTTTCGGGGCATTGGATTCTCACCAATGTTTGCGTTACTCAAGCCGACATTCTCGCTTCCGCTTCGTCCACCGCCGCTCGCGCGGGTGCTTCCCTCTAGGCGGAACGCTCCCCTACCGATGCATTTTTACATCCCACAGCTTCGGCAGATCGCTTAGCCCCGTTCATCTTCGGCGCAAGAGCGCTCGATCAGTGAGCTATTACGCACTCTTTCAAGGGTGGCTGCTTCTAGGCAAACCTCCTGGCTGTCTCTGCACCCCTACCTCCTTTATCACTGAGCGGTCATTTAGGGGCCTTAGCTGGTGATCCGGGCTGTTTCCCTCTCGACGATGAAGCTTATCCCCCATCGTCTCACTGGCCGACCTTGACCCCTGTTATTTTGAGGTCATATCTAGTATTCAGAGTTTGCCTCGATTTGGTACCGCTCTCGCGGCCCGCACCGAAACAGTGCTTTACCCCTAGATGTCCAGTCAACTGCTGCGCCTCAACGCATTTCGGGGAGAACCAGCTAGCTCTGGGTTCGAGTGGCATTTCACCCCTAACCACAACTCATCCGCTGATTCTTCAACATCAGTCGGTTCGGACCTCCACTTAGTTTCACCCAAGCTTCATCCTGGTCATGGATAGATCACCCAGGTTCGGGTCCATAAGCAGTGACAATTGCCCTATGAAGACTCGCTTTCGCTACGGCTCCGGTGGGTTCCCTTAACCAAGCCACTGCCTATGAGTCGCCGGCTCATTCTTCAACAGGCACGCGGTCAGAGCCCAGGGCTCCCCCCACTGCTTGGGAGCTTACGGTTTCATGTTCTATTTCACTCCCCGATGGGGGTTCTTTTCACCCTTCCCTCACGGTACTACTTCACTATCGGTCACCCAGGAGTATTTAGCCTTGCAAGGTGGTCCTTGCTGATTCACACGGGATTCCACGTGTCCCATGCTACTCGGGTCAGAGCGTAAGCTAGTGATGCTTTCGGCTACTGGACTCTCGCCATCTAGGGTGCAGCACTCCACCGCTTCGCCTAGCAGCACGACGCTTGTATTGCTCTCCCACAACCCCGTTTTCACGGTTTAGGCTGCTCCCATTTCGCTCGCCGCTACTACGGGAATCGCTTTTGCTTTCTTTTCCTCTGGCTACTAAGATGTTTCAGTTCGCCAGGTTGTCTCTTGCCTGCCCATGGATTAAGCAGCAGTTCGAAAGGTTAACCTATTCGGGAATCTCCGGATCTACGCTTATTTTCAACTCCCCGAAGCATTTCGTCGCTTACTACGCCCTTCCTCGTCTCTGGGTGCCTAGGTATCCACCGTAAGCCTTTCCTCGTTTGAACCTCGCCCTTAACTTTATTTAAGGCTATGCCATCCCCTAAGGTGCTGCTAAATGGAAGGATCTTATCAACGTCCATGAATGATAAATCATAGCATAGATCGAACTGCCGAATCGGAAAAATTGGGTGCTATCATATAGCTTTGTATCGGCTAAATTCGCGAGTTGGAGATAAGCGGACTCGAACCGCTGACATCCGCCACAGGGTAAACTACCGCCTCTCAGGCCCCCGACTGATTCTACCATAGAGGCCAACGATAGACAATAACTCCCCCCCGAACACAGCTTACAACTTTCATCGTACTGTGCTCTCCAAAGAGCAACTCTTCTCAAAATCTCAAAAGGAAAGGTGCTGAGTTGGAATCCCATTCTAACTAAGGATTCTTGTGGTTCCGGAGGATCTAGCTACAGGAGAACCAGGAACGGAGAGCTTTCCCCCCTTTTCCACCCGACTCTTTGGTCTTAAGAATGCTGGTTTTAAGAATGAGTGATTGCCCTTCTCCGACCCTTACTGCCCAACCTGAAAGCGGACATCTAATGCTTTCCACTTATTGAACTGGGTTCTATGGTCGGTCCGCGACCCCTGGATGCCGAAGGCGTCCTTGGGGTGATCTCGTAGTTCCTACGGGGTGGAGACGATGGGGTCGGTCCATGGATTTTTCTTCCTTTTGCCGCATTTCGCTCAAAGGGTTGAAGGGAGATAGTGCATCAAGCTGTTCGCAAGGGCCAACTTGATCCTCTTCCCCAGGGATCCCAGATGAGGGAACCCTAGGAGAGCCGCCGACTCCAACTACCGTCCATGTACGATCCATACTAGATCTGACCAACTGCCCATCCTACCTCCTCTACGTTCTTGACAGCCCATCTTTGTCTCAGTAGAGTCTTTCAGTGGCATGTTTCGGTCCTCTTCCCCATTACTTAGAAAAAGTGAGCCACCGGTTCAGGTACAAGATACTATCATTACCGCCTGGACAATTAGACATCCAACCCGTAATCGCAACGACCCAATTGCAAGAGCGGAGCTCTACCAACTGAGCTATATCCCCCCGAGCCAAGTGGAGCATGCATGAAGGAGTCAAATGCTTCTTCTATTCTTTTCCTTGGCGCAGCTGGGCCATCCTGGACTTGAACCAGAGACCTCGCCCGTGAAGTAAATCATCGCACCTACGGTCCAACCAATTGGGAGAGAATCAATAGATTCCTTTTCGGGAGCGATTCATCCTTCCCGAACGCAGCATACAACTCTCCGTTGTACTGCGCTCTCCAAGTGTGCTTGTTCCTCCCTTCTTCCTTACCATGGCAAGTCTTTGTGAAATAACTCCGATGAGAAGAAAAAAGAAGGCGTTAAGAGACCCTCCTGGCCCAACCCTAGACACTCTAAGATCCTTTTTCAAACCTGCTCCCATTTCGAGTCAAGAGATAGATAAATAGACACATCCCATTGCACTGATCGGGGGCGTTCGTAGTGACTGAGGGGGTCGAAGACCAAGAAGTGAGTTATTTATCAGCCAAGCATTCTTCTTACGGCTAGATACAATCTCCTGGTCCCTGCGGAAAGAAAAAAAAATTTCACGTTCTTCCTTTCGGGAAGGGAGGATTAGGAAAATCCTATTGATTGCAGCTTTCTCCAGACCTCCGGGAAAAGCATGAAAAAAAAGGCTCGAATGGTACGATCCCTCCGTCACCCCAGAATGAAAGGGGCGATCTCGTAGTTCTTGGTCTGTGAAGATACGTTGTTAGGTGCTCCGTTTTATTTTCCCATTGAGGCCGAACCTAAACCTGTGCTCGAGAGATAGCTGTCCATATACTGATAAGGGATGTATGGATTCTCGAGAAGAGAGGAGCCGTGGTGGTCCCTCCCGGACCGCCCGGATCCCACGAGTGAATAGAAAGTTGGATCTACATTGGATCTCACCTGAACCGCCCCATCTATCCTCCTGAGTAGAAGTTTGGTTTCAAACCCCGGTTCGAACAGGAGAAGTACGCCATGCTAATGTGCCTTGGATGATCCACATCTCAGGGTCAGGCGCTGATGAGCACATTGAACTATCCATGTGGCTGAGAGCCCTCACAGCCCAGGCACAACGACGCAATTATCAGGGGCGCGCTCTACCACTGAGCTAATAGCCCGCCGTGCGGGCCTCCCGATGGGGGCCCGCTATGCCAAAAGCGAGAGAAACCCCATCCCTCTCTTTCCTTTTTTACGCCCCCACGTCGCCACACGGGAGGGACATGGGGACGTAAAAAAGGGGATCCTATCAACTTGTTCCGACCTAGGATAATAAGCTCATGAGCTTAGTCTTACTTCACCGTCGAGAAACGAAAGAAGACTTCCATCTCCAAGTTTAACTCAGACGTAGCTCGCTTCTTTTTGGGTGTGAAGCAGTGTCAAACCAAAATACCCAACAAGCATTAGCTCTCCCTGAAAAGGAGGTGATCCAGCCGCACCTTCCAGTACGGCTACCTTGTTACGACTTCACTCCAGTCACTAGCCCTGCCTTCGGCATCCCCCCCCTTGCGGTTAAGGTAACGACTTCGGGCATGGCCAGCTCCCATAGTGTGACGGGCGGTGTGTACAAGGCCCGGGAACGAATTCACCGCCGTATGGCTGACCGGCGATTACTAGCGATTCCGGCTTCATGTAGGCGAGTTGCAGCCTACAATCCGAACTGAGGACGGGTTTTTGGAGTTAGCTCACCCTCGCGGGATCGCGACCCTTTGTCCCGGCCATTGTAGCACGTGTGTCGCCCAGGGCATAAGGGGCATGATGACTTGACGTCATCCTCACCTTCCTCCGGCTTATCACCGGCAGTCTGCTCAGGGTTCCAAACTCAACGGTGGCAACTAAACACGAGGGTTGCGCTCGTTGCGGGACTTAACCCAACACCTTACGGCACGAGCTGACGACAGCCATGCACCACCTGTGTCCGCGTTCCCGAAGGCACCCCTCTCTTTCAAGAGGATTCGCGGCATGTCAAGCCCTGGTAAGGTTCTTCGCTTTGCATCGAATTAAACCACATGCTCCACCGCTTGTGCGGGCCCCCGTCAATTCCTTTGAGTTTCATTCTTGCGAACGTACTCCCCAGGCGGGATACTTAACGCGTTAGCTACAGCACTGCACGGGTCGATACGCACAGCGCCTAGTATCCATCGTTTACGGCTAGGACTACTGGGGTATCTAATCCCATTTGCTCCCCTAGCTTTCGTCTCTCAGTGTCAGTGTCGGCCCAGCAGAGTGCTTTCGCCGTTGGTGTTCTTTCCGATCTCTACGCATTTCACCGCTCCACCGGAAATTCCCTCTGCCCCTACCGTACTCCAGCTTGGTAGTTTCCACCGCCTGTCCAGGGTTGAGCCCTGGGATTTGACGGCGGACTTAAAAAGCCACCTACAGACGCTTTACGCCCAATCATTCCGGATAACGCTTGCATCCTCTGTATTACCGCGGCTGCTGGCACAGAGTTAGCCGATGCTTATTCCCCAGATACCGTCATTGCTTCTTCTCCGGGAAAAGAAGTTCACGACCCGTAGGCCTTCTACCTCCACGCGGCATTGCTCCGTCAGGCTTTCGCCCATTGCGGAAAATTCCCCACTGCTGCCTCCCGTAGGAGTCTGGGCCGTGTCTCAGTCCCAGTGTGGCTGATCATCCTCTCGGACCAGCTACTGATCATCGCCTTGGTAAGCTATTGCCTCACCAACTAGCTAATCAGACGCGAGCCCCTCCTCGGGCGGATTCCTCCTTTTGCTCCTCAGCCTACGGGGTATTAGCAGCCGTTTCCAGCTGTTGTTCCCCTCCCAAGGGCAGGTTCTTACGCGTTACTCACCCGTCCGCCACTGGAAACACCACTTCCCGTCCGACTTGCATGTGTTAAGCATGCCGCCAGCGTTCATCCTGAGCCAGGATCGAACTCTCCATGAGATTCATAGTTGCATTACTTATAGCTTCCTTGTTCGTAGACAAGGCGGATTCGGAATTGTCTTTCATTCCAAGGCATAACTTGTATCCATGCGCTTCATATA'
    },
    {
        'index': 2,
        'orfs': [
            {
                'frame': 0,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    132,
                    3513
                ),
                'pro': 'ISNSHSSHSSPVSLCLTGTMSQFWGEFPEAVINTFQRLQIALIGDIKKCPLSSPLFPELSKLDAHSQHHLLASFELPRFGGVTPGVMEQLHDAESELAEARARLLRERLHAVANKENIPYLGDCMYYDAPGIGQEELLQAAFLEAPTPEWESERIRPLWPKNEWFRDAQQGSYPEDYGNIPQGDLDTLCQAFDALVEEHWMPIYLMISTFAMFQQYGTQPLLSECVQSAGSLIPACMMTDHHLQPTGDRQADKEERQDYADSQDSIQSMGDFWKEFYSKDSGKKIPDSHKSRLANDPNKVGFTKSALFHKQPLAHSLAQTWANFRGTQDKADLVKVTMDMNVEKYTVRLPDAVRTTAGPLYIEWINLPRMSENSARRLAEAGWNNADICGVDLAVKSHIAVGTPVRVIISLVDGACSDMPTATMCAFEVNLAAQNNRSLNLPLLSLPFSRLLADLHDFQHRVKIACQFRDPEGFNVGTPMLSFSSLEFSELKQTAFERNSLLRDSWSEIEKRACHGGGRCVASQGIVQTWEKEVNPPLKEYAPLVLPPVPRPKRNFIDQQSGEVVRPLIQKSRSMRFKSPSDLWGRPSVDGGSTFTVSPPRGSLRCDDVPGCAYEVDPLHLLYYESVNVPKDTLGGTLLTRMDVRDKAATFDSAVWRQWVRDGCLKPKIKMRITAATSCFSGIVLGACLDAYRRIPATTKTDITASLVTGLPNIVWATRDTSEIEWDIDLAAVCGHTFFALEDTFGYMDFLIYVLRGNEVTAVADWSIYVSFHVDWTQESMSATLVPTFVWPPKSTDISLLKEVWGPYRFTLDGTEARESFSLMPGMAITHGKQTVRTFPRVIAAHFRSWTGKVKISIQEVSSIFLTGTYMVGVSWNASAELTDITTRKHWIVKSGEVFELDLYCPYGENPTFTGLVNGMPYIIVHKLGGIVGPKDSVGTFGFFIHIHGLTGVYKNPTLHSGDRSVGSAWFRVTNIIDDNLTFNIPGRIEDMAAVVGKYDVTNYVNPTSLLFSVTGLHGGIIRLHITWCPNTSLGESRGTLKYMQYLYHTPTENFFGDQATRGIIDQDGFTVDLACGDFFGATRVGLKGEVERLGIYSSNAKSIAEIRVSFEILSMNFYGSTIRVK',
                'strand': 1
            },
            {
                'frame': 0,
                'hits': [
                ],
                'index': 1,
                'pos': (
                    2676,
                    3006
                ),
                'pro': 'RRIFIHTSQAMYVYKKTKRSNRILWPNNPTKFMYNDIWHTIDQACESWILTIWTIKIQLKNFTRFNNPMFSSGYVGEFSRSIPRHTNHVCSSQENGRNFLDRYLDLPSP',
                'strand': -1
            },
            {
                'frame': 0,
                'hits': [
                ],
                'index': 2,
                'pos': (
                    456,
                    792
                ),
                'pro': 'WLSTILLEHGKCGYHEVNGHPMLLHKSIKRLTQCVQITLRDITIILRVGTLLGVPKPFIFRPKRPDAFTLPLRCGSLKESCLKQLLLSDARCIVIHTIPEIGDVFLIGYRV',
                'strand': -1
            },
            {
                'frame': 1,
                'hits': [
                ],
                'index': 3,
                'pos': (
                    2000,
                    2387
                ),
                'pro': 'IKKSIYPKVSSSAKKVCPHTAARSMSHSISEVSRVAHTMLGRPVTRDAVISVFVVAGILRYASRHAPNTIPEKHEVAAVMRILILGLRHPSLTHCRHTALSKVAALSRTSIRVNRVPPRVSFGTLTDS',
                'strand': -1
            },
            {
                'frame': 1,
                'hits': [
                ],
                'index': 4,
                'pos': (
                    1529,
                    1838
                ),
                'pro': 'INGLTTSPDCWSIKFLLGRGTGGKTRGAYSFKGGLTSFSQVCTMPWDATQRPPPWQARFSISDQESLSKEFRSNAVCFNSENSSEEKLNIGVPTLKPSGSRN',
                'strand': -1
            },
            {
                'frame': 1,
                'hits': [
                ],
                'index': 5,
                'pos': (
                    1112,
                    1529
                ),
                'pro': 'QAILTRCWKSCKSASSREKGKLNSGRFNDRLFCAAKFTSKAHIVAVGISEHAPSTREMMTRTGVPTAICDLTARSTPQISALFHPASASLRAEFSDMRGKLIHSIYNGPAVVRTASGRRTVYFSTFISMVTLTRSALS',
                'strand': -1
            }
        ],
        'sequence': 'CATTCATCTCAGTCTCATTGTTACAGCTCTTTTATCTCTGTCTCTCATCTCTTGATACGATATCTCAACAATCTCTCTGTTACTGGACATAACGATAAGTTTTCTGGAAATTTCCTTTTAATTGTTCAATAAATTTCCAACTCCCATTCTTCTCACTCATCTCCTGTATCATTGTGCCTTACTGGCACAATGTCTCAGTTTTGGGGAGAATTCCCCGAGGCTGTTATCAACACCTTTCAGCGCCTACAGATAGCGCTGATTGGTGACATCAAGAAATGCCCCCTCTCCTCCCCCCTGTTTCCCGAGCTTTCCAAGCTCGATGCTCACTCCCAGCATCATTTGCTGGCTTCCTTCGAACTCCCCAGGTTCGGAGGTGTTACACCTGGTGTCATGGAGCAACTCCATGATGCGGAGTCTGAACTGGCTGAGGCCAGGGCTAGACTCCTTCGCGAACGGCTACACGCGGTAGCCAATAAGGAAAACATCCCCTATCTCGGGGATTGTATGTATTACGATGCACCTGGCATCGGACAGGAGGAGCTGCTTCAAGCAGCTTTCCTTGAGGCTCCCACACCTGAGTGGGAGAGTGAACGCATCAGGCCTCTTTGGCCTAAAAATGAATGGTTTAGGGACGCCCAACAAGGTTCCTACCCTGAGGATTATGGTAATATCCCTCAGGGTGATTTGGACACATTGTGTCAAGCGTTTGATGCTCTTGTGGAGGAGCATTGGATGCCCATTTACCTCATGATATCCACATTTGCCATGTTCCAACAGTATGGTACTCAGCCATTATTGTCGGAGTGTGTGCAATCTGCAGGTAGTCTGATTCCTGCGTGCATGATGACTGACCACCATCTTCAACCGACGGGTGATAGGCAGGCCGACAAGGAAGAGCGGCAGGATTATGCGGATAGCCAAGACTCTATTCAGAGCATGGGTGATTTCTGGAAAGAATTCTATTCCAAGGATTCAGGAAAGAAAATACCCGACTCTCACAAGTCAAGGTTGGCCAATGATCCCAACAAAGTTGGTTTTACCAAGAGTGCACTGTTTCACAAGCAACCCCTAGCGCACTCGCTAGCTCAAACATGGGCTAATTTTAGGGGCACTCAGGATAAGGCGGACCTGGTCAAAGTGACCATGGATATGAATGTTGAGAAATATACTGTCCGTCTTCCTGATGCAGTGCGTACCACAGCGGGTCCATTGTATATAGAATGGATCAACTTACCACGCATGTCTGAGAATTCTGCACGCAGGCTAGCTGAAGCCGGGTGGAATAATGCAGATATTTGTGGTGTGGACCTTGCTGTTAAGTCACATATAGCTGTCGGCACGCCAGTACGTGTCATCATCTCCCTTGTAGATGGTGCATGTTCCGATATGCCCACAGCAACTATGTGTGCTTTTGAGGTAAATTTAGCGGCGCAAAATAATCGATCATTGAATCTTCCGCTGTTAAGTTTGCCCTTTTCACGGCTGCTTGCTGACTTGCATGATTTCCAACATCGTGTCAAGATTGCTTGTCAGTTTCGGGACCCAGAGGGTTTTAATGTGGGTACGCCTATGTTAAGTTTCTCTTCACTTGAATTTTCTGAGTTGAAGCAAACCGCATTTGAGCGGAATTCTTTACTTAGGGATTCTTGGTCTGAAATTGAGAAGCGCGCTTGCCATGGTGGTGGCCGTTGTGTTGCGTCCCAGGGCATTGTGCAAACCTGGGAAAAGGAGGTTAATCCTCCCTTGAAGGAATATGCACCCCTGGTTTTACCTCCCGTTCCCCGGCCCAAAAGGAATTTTATCGACCAGCAGTCTGGGGAGGTTGTAAGACCATTGATTCAGAAGTCCCGCTCCATGCGATTTAAATCGCCGTCTGATTTGTGGGGTAGGCCCTCCGTTGATGGGGGATCAACATTTACAGTGTCACCACCAAGGGGTTCTTTACGGTGCGATGATGTACCTGGATGTGCCTATGAGGTGGATCCATTACATTTGTTGTACTACGAATCTGTTAACGTGCCAAAAGACACCCTTGGTGGTACTCTGTTAACCCGGATGGACGTTCGGGACAAGGCTGCGACTTTTGACAGTGCCGTATGGCGACAATGGGTAAGAGATGGATGTCTCAAACCCAAAATCAAAATGCGCATTACTGCAGCTACTTCGTGTTTCTCTGGTATTGTATTGGGTGCGTGTCTCGATGCGTATCGGAGAATTCCTGCAACCACGAAGACAGATATCACTGCGTCCCTTGTGACGGGCCTACCTAACATTGTGTGGGCTACGCGCGATACTTCAGAGATCGAATGGGACATCGATCTCGCAGCAGTGTGCGGACATACTTTTTTTGCACTGGAAGATACCTTTGGGTATATGGACTTTTTAATCTATGTACTCAGGGGCAATGAGGTCACTGCTGTTGCTGATTGGTCGATATACGTCTCCTTTCATGTCGATTGGACACAGGAGAGTATGTCGGCCACACTTGTCCCAACTTTCGTGTGGCCCCCAAAATCAACTGATATATCTCTTTTGAAAGAAGTATGGGGACCCTATCGTTTTACACTTGATGGTACCGAGGCAAGAGAAAGTTTTAGTCTAATGCCCGGTATGGCCATCACTCATGGGAAGCAAACTGTGCGCACTTTTCCCCGCGTTATAGCCGCACACTTCCGATCATGGACTGGGAAGGTCAAGATATCTATCCAGGAAGTTTCTTCCATTTTCTTGACTGGAACATACATGGTTGGTGTGTCGTGGAATGCTTCTGCTGAACTCACCGACATAACCACTCGAAAACATTGGATTGTTAAATCTGGTGAAGTTTTTGAGTTGGATCTTTATTGTCCATATGGTGAGAATCCAACTTTCACAGGCCTGGTCAATGGTATGCCATATATCATTGTACATAAACTTGGTGGGATTGTTGGGCCAAAGGATTCTGTTGGAACGTTTGGTTTTTTTATACACATACATGGCTTGACTGGTGTGTATAAAAATCCTACGTTACACAGTGGAGATCGTTCCGTGGGGAGTGCCTGGTTCCGCGTTACCAACATCATTGATGACAACCTGACATTCAACATACCAGGTCGCATTGAAGATATGGCTGCGGTTGTTGGGAAGTATGATGTTACAAATTATGTCAACCCTACCAGTTTGCTTTTCTCTGTTACTGGGTTGCATGGTGGCATTATACGTCTCCACATTACATGGTGTCCAAACACGAGTCTCGGTGAATCGCGAGGTACACTAAAATACATGCAATATTTGTACCATACGCCCACTGAGAACTTCTTTGGTGATCAGGCAACTCGTGGAATCATTGATCAAGATGGTTTCACGGTTGATCTGGCTTGTGGCGATTTCTTTGGCGCTACAAGAGTTGGATTGAAAGGGGAAGTTGAGAGACTTGGTATTTATAGCTCGAATGCCAAGTCCATTGCTGAAATTCGAGTTTCCTTTGAGATACTGTCCATGAACTTTTATGGCAGCACTATCAGGGTGAAATGATTTTGAGAGCAACCCTTCGGCTCCGGGTTAATTGAGCCAACTAAAGCTGTGCCATGTGAGTTTGTGTTTTACACATGG'
    },
    {
        'index': 3,
        'orfs': [
            {
                'frame': 2,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    1014,
                    2553
                ),
                'pro': 'RGISMGLPWYRVHTVVLNDPGRLIAVHIMHTALVAGWAGSMALYELAVFDPSDPVLDPMWRQGMFVIPFMTRLGITNSWGGWSITGGTVTNPGIWSYEGVAGAHIVFSGLCFLAAIWHWVYWDLEIFTDERTGKPSLDLPKIFGIHLFLSGVACFGFGAFHVTGLYGPGIWVSDPYGLTGRVQSVNPAWCVEGFDPFVPGGIASHHIAAGTLGILAGLFHLSVRPPQRLYKGLRMGNIETVLSSSIAAVFFAAFVVAGTMWYGSATTPIELFGPTRYQWDQGYFQQEIYRRIGAGLAENQSLSEAWSKIPEKLAFYDYIGNNPAKGGLFRAGSMDNGDGIAVGWLGHPIFRDKEGRELFVRRMPTFFETFPVVLVDGDGIVRADVPFRRAESKYSVEQVGVTVEFYGGELNGVSYSDPATVKKYARRAQLGEIFELDRATLKSDGVFRSSPRGWFTFGHASFALLFFFGHIWHGARTLFRDVFAGIDPDLDAQVEFGAFQKLGDPTTRRQVV',
                'strand': -1
            }
        ],
        'sequence': 'ATCAAGATGACAGACCCATACTCTGTACAATCCATAGGATCAATAAAACCAAGTCACACACTCATATTCCGGAAATACAGAAACAAAGAAATTCCACGGTCGAACTACCAAAATAGAATGGGATAAAAATCATAAACCTAAACGCTTCATTTTGTATTGAAAAAGCCAGTTAATGGTTCTTGTGAATCTAATTCATTGAAATTCCATCCAGTAAAATGGAAGAATTATAAATCTCCAAAATAATCGATAGGAATATCGCAAATAGAGCCATTGCGAAACCCATCAAAGGAGTAGTTCCCCACCCAGGAGCTACTTTACCATATTCTGAATTCAATGGTTTCAATAAACTCCCTGCATTAGTTCGTTTGGGGCGGCCAGAGCTAGAACTACCCTCAACGGTTTGTGTAGCCATAATATTTTATATTCAGTAAGATCTGTTGACTTTGTATACCATTCCGTTGTAAATAAATGATCTTATCATAGATCCATTGTGGTCTTAAAACTATATAATGTCTTAAAACTATATAATAATGGAAACAGCAACCCTAGTTGCCATCTTTTTATCCGGTTTACTTGTAAGTTTTACTGGGTACGCCTTATATACTGCTTTTGGGCAACCCTCTCAACAACTAAGAGATCCATTCGAGGAACACGGGGACTAGTTGAAGTAATGATCCTCCCAATATTGGGAGGATCATTACTTTACTTTCAATTGAGATAATGAAAAATCATTTCACCTTTTTAGTTGGAACTTTAGGCGGTTCTCGAAAAAAGATAGCGAAAAAAATTATTCCTAGAGTTGAGACTAAAAGGAATGTATAAACCAATGCTTCCATAGATTTGATCGTGGTTTACAATTATAGCTTCCATACCTGTTTATTGGGGATCGTCTCCCGGATAAATAAAGAACAAGAGTCAAAGAAAAGGCAGTGATTCAAATCAAGATTTATCCGGTACCCTATATCAAATCACAAAATAAAAATGAAAAGTAACAAGTAACAAAGCAATATTGTATCAAACTACTTGTCTTCTTGTAGTTGGATCTCCGAGTTTTTGGAATGCTCCAAATTCCACTTGAGCATCTAAATCTGGATCAATACCAGCAAAAACATCTCTAAACAAGGTTCTAGCGCCATGCCAAATGTGTCCGAAGAAGAAGAGCAAAGCAAACGAAGCATGCCCAAAAGTAAACCAACCCCTTGGACTGCTACGAAAAACACCATCGGATTTCAAAGTAGCACGATCTAATTCAAAAATTTCACCCAATTGAGCGCGTCTAGCATATTTTTTCACAGTAGCGGGATCACTATAACTGACTCCGTTGAGTTCGCCGCCATAGAACTCGACAGTTACACCTACTTGTTCGACACTATATTTTGATTCTGCCCTTCTAAAAGGAACATCGGCTCTAACAATTCCGTCTCCGTCTACCAAAACAACCGGAAACGTTTCAAAAAAGGTAGGCATACGACGTACAAAAAGTTCGCGCCCCTCTTTATCTCTAAAGATAGGATGTCCTAACCACCCAACAGCTATTCCATCCCCGTTGTCCATTGAGCCCGCTCTGAATAACCCCCCCTTTGCCGGATTATTGCCGATGTAATCATAAAAAGCCAGTTTTTCAGGAATTTTAGACCAAGCTTCAGATAAACTTTGATTTTCAGCTAACCCAGCACCAATTCTGCGATATATTTCTTGTTGGAAGTATCCTTGATCCCATTGATAACGAGTGGGACCAAATAATTCAATCGGGGTAGTTGCTGAACCATACCACATAGTTCCGGCAACTACAAAAGCTGCAAAAAAGACAGCAGCAATACTACTGGAAAGGACAGTTTCAATATTTCCCATACGTAATCCTTTGTATAGGCGTTGAGGTGGACGGACACTAAGATGGAATAGACCCGCCAATATGCCCAATGTCCCTGCTGCAATATGATGAGAGGCTATTCCTCCCGGAACAAAAGGATCAAAACCCTCCACACACCACGCTGGATTTACGGATTGTACCCTTCCGGTTAGTCCATAAGGATCGGACACCCATATTCCAGGACCATACAATCCTGTTACATGAAATGCACCAAAACCAAAGCAAGCCACCCCTGATAGAAATAAATGAATTCCAAAGATCTTAGGCAAATCCAAAGAGGGTTTTCCTGTACGTTCATCAGTAAATATTTCTAGATCCCAATACACCCAATGCCAGATAGCTGCCAAAAAGCACAAGCCAGAAAACACAATATGTGCTCCGGCCACACCTTCGTAACTCCAAATACCTGGATTCGTTACAGTACCCCCTGTGATACTCCAACCGCCCCATGAATTGGTTATTCCTAAACGAGTCATGAAAGGTATAACGAACATACCCTGTCTCCACATTGGATCAAGAACAGGATCAGAAGGATCAAAAACTGCTAATTCGTATAGAGCCATCGAACCGGCCCAACCAGCAACCAGAGCTGTATGCATTATATGGACAGCAATCAAACGGCCGGGATCATTCAATACAACGGTATGAACACGATACCAAGGCAAACCCATGGAAATACCCCTTTATCAACGAAAAATAGACACAAAGTAACTTTATTGCATTGGAAAAAAATATGCTGTGG'
    },
    {
        'index': 4,
        'orfs': [
            {
                'frame': 0,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    537,
                    957
                ),
                'pro': 'NMAKPIPKIGSRRNRRIGSRKNARRVPKGVIHVQASFNNTIVTVTDVRGRVISWSSAGACGFKGTRRGTPFAAQTAAGNAIRTVVDQGMQRAEVMIKGPGLGRDAALRAIRRSGILLSFIRDVTPMPHNGCRPPKKRRV',
                'strand': 1
            },
            {
                'frame': 1,
                'hits': [
                ],
                'index': 1,
                'pos': (
                    1015,
                    2002
                ),
                'pro': 'YTMVREKVTVSTRTLQWKCVESRADSKRLYYGRFILAPLMKGQADTIGIAMRRALLGEIEGTCITRAKFEKIPHEYSTIIGIQESVHEILMNLKEIVLRSNLYGTRNASICIKGPGYVTAQDIILPPSVEIVDNTQHIANLTEPINLCIELQIERNRGYRIKTPNNFQDGSYPIDAVFMPVRNANHSIHSYVNGNEKQEILFLEIWTNGSLTPKEALHDASRNLIDLFIPFLHAEEENLQLENNQHKVTLPLFTFHGRLAKQRKNKKEIALQYIFIDQSELFPRVYNCLKRSNIHTLLDLLNNSQEDLMKIKHFRIEDVKHILNILEI',
                'strand': 1
            },
            {
                'frame': 2,
                'hits': [
                ],
                'index': 2,
                'pos': (
                    114,
                    567
                ),
                'pro': 'TNFWYRFCHILSSHKNKSEIYGYIHFMSKRILIFFYLFICTSVHRLLLISRVFFALERLALSLFMSRVGTNYYNSSPPTDQSTFFTNFTNRGPYFHICHSFSYYLLEENKFLEIFNFELYPHERMLKLKKPPNHSSLCFGVYKLYVLWFK',
                'strand': -1
            }
        ],
        'sequence': 'GTTCGTTTAGATTTGAGATAATGAAAATATGATTCTGGCTTTTGTTTCGGAAAGGATTCGACGTTGGTTTATACGTATACTACCAAGAAATAGAATAAAAATTGAGGTAAGTCCTTATTTAAACCAAAGGACGTATAGTTTATAGACTCCAAAGCAAAGACTCGAATGATTCGGTGGTTTTTTCAATTTCAACATTCTTTCGTGGGGATACAATTCGAAGTTAAAAATTTCAAGAAACTTATTTTCTTCCAATAAATAGTAAGAAAAGGAATGACAAATATGAAAATAAGGGCCTCTGTTCGTAAAATTTGTGAAAAATGTCGATTGATCCGTAGGCGGGGACGAATTATAGTAATTTGTTCCAACCCGAGACATAAACAAAGACAAGGCTAATCTTTCTAAAGCAAAAAAGACTCTAGAAATCAAAAGTAACCGATGTACAGATGTACAAATAAATAAGTAAAAAAAAATAAGGATACGTTTTGACATGAAATGGATATATCCATATATCTCTGACTTATTTTTATGAGATGATAAAATATGGCAAAACCTATACCAAAAATTGGTTCACGTAGAAATAGACGTATTGGTTCACGTAAGAATGCGCGTAGAGTACCAAAGGGAGTTATTCATGTTCAAGCAAGTTTCAATAATACGATTGTGACTGTTACAGATGTGCGGGGTCGAGTAATTTCTTGGTCCTCCGCCGGGGCTTGTGGATTCAAGGGTACAAGAAGAGGTACACCATTTGCCGCTCAAACCGCAGCAGGAAATGCTATTAGGACAGTAGTGGATCAAGGTATGCAACGAGCAGAAGTCATGATAAAAGGCCCGGGTCTCGGAAGAGATGCGGCATTAAGAGCTATTCGTAGAAGTGGTATACTATTAAGTTTCATACGCGATGTAACCCCTATGCCACATAATGGCTGTAGGCCCCCTAAAAAAAGGCGTGTGTAAAAATAAACATTGAAGAGATTTCAAGAGAAATAAATAATTCAATGATTTGATCAAATAATATACTATGGTTCGAGAGAAAGTAACAGTATCTACTCGGACACTACAGTGGAAGTGTGTTGAATCAAGAGCAGACAGTAAGCGTCTTTATTATGGACGCTTTATTCTGGCCCCACTTATGAAAGGTCAAGCGGATACAATAGGAATTGCGATGCGAAGAGCTTTGCTCGGAGAAATAGAAGGAACATGTATCACACGCGCAAAATTTGAGAAAATACCACATGAATATTCTACCATAATAGGTATTCAAGAATCCGTACATGAAATTTTAATGAATTTGAAAGAAATTGTATTGAGAAGTAATCTATATGGAACTCGTAACGCGTCTATTTGTATCAAGGGTCCTGGATATGTAACTGCTCAAGACATTATCTTACCACCTTCTGTGGAAATCGTTGATAATACACAGCATATAGCTAACCTAACAGAACCAATTAATTTGTGTATTGAATTACAAATTGAGAGGAATCGCGGATATCGTATAAAAACGCCAAATAACTTTCAAGACGGAAGTTATCCTATAGATGCTGTATTCATGCCTGTTCGAAATGCGAATCATAGCATTCATTCTTATGTGAATGGGAATGAAAAACAGGAGATACTTTTTCTCGAAATATGGACAAATGGAAGTTTAACTCCTAAAGAAGCACTTCATGACGCCTCCCGGAATTTGATTGATTTATTTATTCCTTTTTTACATGCAGAAGAAGAAAACTTACAGTTAGAAAACAATCAACACAAAGTTACTTTGCCCCTTTTTACTTTTCATGGTAGATTGGCTAAACAAAGGAAAAATAAAAAAGAAATCGCATTGCAATATATTTTTATTGACCAATCAGAATTGTTCCCCAGGGTCTATAATTGCCTCAAAAGGTCCAATATACATACATTATTGGATCTTTTGAATAACAGTCAAGAAGATCTTATGAAAATTAAACATTTTCGCATAGAAGATGTAAAACATATATTGAACATTCTAGAAATATAAATAGAAAGATAAAAGCATTTAGAATAAATTTAAAAGGGTTATTTAATTTTTTTTTCTAAAGTTTTTGTATAAAAAGATAAAAATGAGTTTTGAATCTTTAGCACAATTCATATATTCAGAATAGGTC'
    },
    {
        'index': 5,
        'orfs': [
            {
                'frame': 1,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    1,
                    1429
                ),
                'pro': 'LQVGDGIARIYGLDEVMAGELVEFEEGTIGIALNLESNNVGVVLMGDGLMIQEGSSVKATGRIAQIPVSEAFLGRVINALAKPIDGRGEISSSESRLIESPAPGIISRRSVYEPLQTGLIAIDSMIPIGRGQRELIIGDRQTGKTAVATDTILNQQGQNVVCVYVAIGQKASSVAQVVTALQERGAMEYTIVVAETADSPATLQYLAPYTGAALAEYFMYRELHTLIIYDDLSKQAQAYRQMSLLLRRPPGREAYPGDVFYLHSRLLERAAKSSSRLGEGSMTALPIVETQSGDVSAYIPTNVISITDGQIFLSADLFNAGIRPAINVSISVSRVGSAAQIKAMKQVAGKSKLELAQFAELEAFAQFASDLDKATQNQLARGQRLRELRKQSQSSPLSVEEQILTIYTGTNGYLDSLEIGQVRKFLVELRTYLTTNKPQFQEIISSTKTFTDEAEALLKEAIQEQMERFLLQEQV',
                'strand': 1
            }
        ],
        'sequence': 'ACTTCAAGTAGGCGATGGCATTGCTCGTATTTATGGTCTTGATGAAGTAATGGCAGGTGAATTAGTAGAATTTGAAGAGGGTACGATAGGCATTGCTCTGAATTTGGAATCAAATAATGTTGGTGTTGTATTAATGGGTGACGGTTTGATGATACAAGAGGGGAGTTCTGTAAAAGCAACAGGAAGAATTGCTCAGATACCCGTAAGCGAGGCTTTTTTAGGTCGTGTTATAAATGCACTGGCTAAACCTATTGATGGTCGGGGCGAAATTTCATCTTCTGAATCTCGATTAATTGAATCTCCCGCTCCTGGTATTATTTCGAGACGTTCCGTATACGAGCCTCTTCAAACAGGGCTTATTGCTATTGATTCTATGATCCCTATAGGGCGTGGTCAGCGAGAATTAATTATTGGGGACAGACAGACCGGTAAAACAGCAGTAGCCACAGATACTATTCTCAATCAACAAGGGCAAAATGTAGTATGCGTTTATGTAGCTATCGGTCAAAAAGCATCTTCTGTGGCTCAGGTGGTGACTGCTTTACAGGAAAGGGGAGCAATGGAATACACTATTGTGGTAGCTGAAACGGCGGACTCCCCTGCTACATTACAATACCTTGCTCCTTATACAGGAGCAGCTCTGGCTGAATATTTTATGTACCGTGAACTACACACTTTAATCATTTATGATGATCTCTCCAAACAAGCGCAGGCTTATCGCCAAATGTCTCTTCTATTACGAAGACCGCCGGGCCGCGAAGCTTATCCGGGAGATGTTTTTTATTTACATTCACGCCTTTTGGAAAGAGCCGCTAAATCAAGTTCTCGTTTAGGTGAAGGAAGTATGACTGCTTTACCAATAGTTGAGACCCAATCGGGAGATGTTTCGGCGTATATTCCTACTAATGTAATTTCCATTACAGACGGACAAATATTCTTATCTGCCGATTTATTTAATGCTGGAATCAGACCGGCCATTAATGTGAGTATTTCTGTTTCCAGGGTAGGATCCGCAGCTCAAATTAAAGCCATGAAACAAGTAGCTGGCAAATCAAAATTGGAATTGGCACAATTTGCAGAATTAGAAGCCTTTGCACAATTCGCTTCTGATCTCGATAAAGCTACTCAGAATCAATTGGCAAGAGGTCAACGATTACGTGAGTTGCGTAAACAATCTCAATCATCTCCCCTTTCGGTGGAAGAACAGATACTGACTATTTATACCGGAACGAACGGTTATCTTGATTCATTAGAAATCGGACAGGTAAGGAAATTTCTTGTTGAGTTACGTACTTACTTAACTACGAATAAACCTCAGTTCCAAGAAATCATATCATCTACCAAGACATTTACCGACGAAGCGGAAGCCCTTTTGAAAGAAGCTATTCAGGAACAGATGGAACGTTTTCTACTTCAGGAACAAGTATAAATAAATACTTTGAATCTTCATC'
    },
    {
        'index': 6,
        'orfs': [
            {
                'frame': 0,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    1011,
                    1320
                ),
                'pro': 'GVSYISNKLTFFSSNGLDVVASTFVTIKTSKPVSPYSCPCTSRRFSSYRCPCFFRWNSRLRSYSKCCQDISIFGFIVRSIISQFIIFNTSFEPNTCFSLCLW',
                'strand': 1
            },
            {
                'frame': 2,
                'hits': [
                ],
                'index': 1,
                'pos': (
                    -3,
                    1347
                ),
                'pro': 'LMSCREGLMSPQTETKASVGFKAGVKDYKLTYYTPDYETKDTDILAAFRVTPQPGVPPEEAGAAVAAESSTGTWTTVWTDGLTSLDRYKGRCYHIEPVAGEESQFIAYVAYPLDLFEEGSVTNMFTSIVGNVFGFKALRALRLEDLRIPTAYVKTFQGPPHGIQVERDKLNKYGRPLLGCTIKPKLGLSAKNYGRAVYECLRGGLDFTKDDENVNSQPFMRWRDRFVFCAEASYKAQAETGEIKGHYLNATAGTVDEMMKRAAFARELGVPIVMHDYLTGGFTANTTLAHYCRDNGLLLHIHRAMHAVIDRQKNHGMHFRVLAKALRMSGGDHIHAGTVVGKLEGERDITLGFVDLLRDDFVEKDRSRGIYFTQDWVSMPGVLPVASGGIHVWHMPALTEIFGDDSVLQFGGGTLGHPWGNAPGAVANRVSLEACVHARNEGRDLAREG',
                'strand': -1
            }
        ],
        'sequence': 'ACCCTCACGAGCAAGATCACGTCCCTCATTACGAGCATGTACACATGCTTCTAGAGATACTCGATTAGCAACGGCACCAGGTGCATTTCCCCAAGGGTGTCCTAAAGTTCCGCCGCCAAATTGTAGTACAGAATCATCTCCAAAGATCTCGGTCAGAGCAGGCATATGCCAAACGTGAATACCCCCTGAAGCTACAGGCAAAACACCTGGCATAGAGACCCAATCTTGAGTGAAATAAATACCGCGGCTTCGATCTTTTTCAACAAAATCATCACGTAGTAAATCAACAAAGCCTAAAGTGATATCCCTTTCCCCCTCAAGTTTACCTACTACGGTACCGGCGTGTATATGATCTCCACCAGACATACGTAACGCTTTAGCTAGTACACGAAAGTGCATACCATGATTCTTCTGTCTATCAATAACTGCATGCATTGCACGGTGGATGTGAAGAAGTAAACCATTATCTCGGCAATAATGAGCCAAGGTAGTATTTGCAGTGAATCCCCCTGTTAAGTAATCATGCATTACGATAGGAACCCCCAATTCTCTGGCAAATGCAGCTCTTTTCATCATCTCGTCTACTGTACCTGCAGTAGCGTTCAAGTAATGCCCTTTGATTTCACCTGTTTCAGCCTGTGCTTTATAACTCGCTTCGGCACAAAATACGAAACGGTCTCTCCAACGCATAAATGGTTGGGAATTAACGTTCTCATCATCTTTGGTAAAATCAAGTCCACCGCGGAGACATTCATAAACTGCTCTACCGTAATTCTTAGCGGATAACCCCAATTTAGGTTTAATAGTACATCCCAATAGGGGGCGGCCATACTTGTTCAATTTATCTCTCTCAACTTGGATCCCATGAGGCGGGCCTTGGAAGGTTTTAACATAAGCAGTAGGGATTCGCAAATCCTCCAGACGTAGCGCGCGCAGGGCCTTGAACCCAAACACATTACCTACAATGGAAGTAAACATGTTAGTAACAGAACCCTCTTCAAAAAGGTCTAAGGGGTAAGCTACATAAGCAATAAATTGACTTTCTTCTCCAGCAACGGGCTCGATGTGGTAGCATCGACCTTTGTAACGATCAAGACTAGTAAGCCCGTCAGTCCATACAGTTGTCCATGTACCAGTAGAAGATTCAGCAGCTACCGCTGCCCCTGCTTCTTCAGGTGGAACTCCAGGTTGAGGAGTTACTCGAAATGCTGCCAAGATATCAGTATCTTTGGTTTCATAGTCAGGAGTATAATAAGTCAATTTATAATCTTTAACACCAGCTTTGAACCCAACACTTGCTTTAGTCTCTGTTTGTGGTGACATAAGTCCCTCCCTACAACTCATCAATTAATAATTCTCACAAGAACAAGGTCTACTCGACATAAATTATGAAGTTAATGAAACCTTTAACAGGAATCTTTCACAAAATTATCAAC'
    },
    {
        'index': 7,
        'orfs': [
            {
                'frame': 0,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    938,
                    1295
                ),
                'pro': 'RSHKDFFSVNFHLLISSFTESTPPPLTVQEYAELNMSGSTGERSFADIITSIRYWVIHSITIPSLFIAGWLFVSTGLAYDVFGSPRPNEYFTESRQGIPLITGRFDPLEQLDEFSRSF',
                'strand': -1
            }
        ],
        'sequence': 'CAATTTCAAAAAAAAAAATTTTAACTTTTATTAGTATTAGATTAAATATTTGTTAGATTAATATAGAGTAAGGTTCTATGCTATTAGTATAGAAAGGGTTTGCATGATATCTGATCGTATAGAAATATATAGTATATATAATTGTGAGTCATCCAAAAAGAGTAAATAGAGTGATTCCTTCTTCGTTTTAAGTATTGACAGATACTATTGAGTAACAGATGTGAGTAACAGATGTTCTGAATCCCTTAACGAAGTTAATTTTTCAAAAACATTATCAGAAAAAGTGTAGGTTTTTGAAACATCTATAAAAAATATTATGATTATTAAGAACTCAACGGGACCTACCCCCTCCTTCCTTGTCTGATTCGAGGGGGATCCCGTTGAGTTCTTATGCTTTCATGTCTACAACTCAGTTCATCCGATTATTACAGGGATGAACCTAATCCAGAATAGGAACCATAAAAGAAAATACCGATTAAACCGATCACAAGAATACCCGCTACAGTACCTATTATCCAAAGAGGAATCCTTCCAGTAGTATCGGCCATTTGTCCTACTTTCCTCCACATTTTATCAAGTGGTCATGCTCGAGACATAAACAGCCATAGATAATTATGAGATGATATCTTTCCGAATGGGATAAGAGAATTCTTATATTCTTTTTTTTTTTTTAATTAAAGAAATTATTGGAAAATAAAGCAGCAAGTACAAAAATGAGTAATAACCCCCAGTAGAGACTGGTACGATTCAATTCAACACTTTGTTCGTTCGGGTTTGATTGTGTCATAGCTCTATGATTCGGATTAGGTTTATCGTTGGATGAACTGCATTGCTGATATTGACCCTAAAAAAAAAACGGTAGGTACAGCTAGTCCGTGAACAGCCAACCATCGCACTGTAAAAATCGGATAGGTTCTATCTATAGTCATTGGGGCCTCCTAAAAAGATCTACTAAATTCATCGAGTTGTTCCAAAGGATCAAAACGGCCAGTTATTAATGGAATTCCTTGTCGGCTTTCTGTAAAATACTCGTTTGGACGAGGGCTTCCAAATACATCGTAAGCTAAACCCGTGCTGACGAATAACCAACCCGCAATAAATAAGGAAGGTATAGTAATGCTATGAATGACCCAGTATCGAATACTGGTAATAATATCAGCAAAAGAACGTTCTCCTGTGCTTCCAGACATGTTGAGCTCCGCATATTCTTGTACAGTCAGGGGGGGGGGGGTCGATTCCGTAAAAGATGAAATCAGTAAATGGAAATTCACTGAAAAAAAATCTTTGTGAGATCGTCAATATTGTACCAAGGGTGTCTTTAGAGTATACCG'
    },
    {
        'index': 8,
        'orfs': [
            {
                'frame': 0,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    765,
                    1116
                ),
                'pro': 'SDRNRIGIFRIRNKQTMDKSKRILLKSKRSFRRRLPPIQSGDRIDYRNMSLISRFISEQGKILSRRVNRLTLKQQRLITIAIKQARILSLLPFLNNEKQFERSESTRKKKKKIGEE',
                'strand': 1
            }
        ],
        'sequence': 'GTTTTTGTTGTTTTTTTTTTGTTTTTTTTTTTTTTTTTATTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTATAATAATTTATTCTAAAAAAAAAAAAACAAAGAAAAAGCGGTTTCGCCCTCAGTGAAACTATGAACCCGGGCCCAGGCTCAAATTAATATTAATATAATAATAGAGTGGAAATGAAAATGTGATGGTTGGGGCAACTATATCATACAAGATACTTAACTGAAAATACTGTACGGCAATTCTTAATTATAAATATAGTTAGAAATCATTATATTACTTATTATTACTATATTGATTGCAACGAAATCTTTCTTTTATAATTTGATTTCGAGTTACCTGCTTCTATTTTTTTTTTGTCCTTTATTCTTCCTTGCTTCGGATCGGAAAATTAAAGAATTGAGTGAATCATAAACCAAAGGAGGTTCATGGCCAAGGGTAAAGATGTCCGAGTAACAGTTATTTTGGAATGTACCAGTTGTCTTCGAAATCGTGTTAATAAGGAATCAACGGGCATTTCCAGATATATTACTCAAAAGAATCGACACAATACGCCTGGTCGATTGAAATTGAGAAAATTCTGTCCCTGTTGTTACAAACATACGATTCATGGGGAGATAAAGAAATAGATCGAACCGACCGCTCGTGTGTCAGTCTTCCAAGGAAGGTGAAAAATTACATATTATATATAACATATATTTATTTAAATATAAACAAACCCAATCCTATTTCTTAATTCTACATCATGTTTGATCCGATCGAAATAGGATTGGGATTTTCAGGATAAGGAATAAACAAACCATGGATAAATCCAAGCGAATCCTTCTTAAATCCAAGCGATCTTTTCGTAGGCGTTTGCCTCCGATCCAATCGGGGGATCGAATTGATTATAGAAACATGAGTTTAATTAGTCGATTTATTAGCGAACAAGGAAAAATATTATCTAGACGGGTAAATAGGTTGACCTTAAAACAACAACGATTAATTACTATTGCTATAAAACAAGCTCGTATTTTATCTCTGTTACCTTTTCTTAATAATGAGAAACAATTTGAAAGAAGCGAGTCAACTCGTAAGAAAAAAAAAAAAATTGGAGAAGAATAAATATTTTTTATTGAACGTGTTTCTTCATTTTGATGACTTTATCATATTTTATCATACTAATTTCTACTCTACCTTCCCAGAGTTCATTCTCCAGGGAACTCCATTTAAACTATTCCAACGGATTCCTTCCAATCTCTTTATT'
    },
    {
        'index': 9,
        'orfs': [
            {
                'frame': 2,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    116,
                    1196
                ),
                'pro': 'INQDFTMTAILERRESESLWGRFCNWITSTENRLYIGWFGVLMIPTLLTATSVFIIAFIAAPPVDIDGIREPVSGSLLYGNNIISGAIIPTSAAIGLHFYPIWEAASVDEWLYNGGPYELIVLHFLLGVACYMGREWELSFRLGMRPWIAVAYSAPVAAATAVFLIYPIGQGSFSDGMPLGISGTFNFMIVFQAEHNILMHPFHMLGVAGVFGGSLFSAMHGSLVTSSLIRETTENESANEGYRFGQEEETYNIVAAHGYFGRLIFQYASFNNSRSLHFFLAAWPVVGIWFTALGISTMAFNLNGFNFNQSVVDSQGRVINTWADIITRANLGMEVMHERNAHNFPLDLAAVEVPSING',
                'strand': 1
            }
        ],
        'sequence': 'GGTTGACATGGGTATATAAGTCATGTTATACTGTTGAATAACAAGCCCTCAATTATCTATTATTTCTATTTATAGAGAATTCGTGTGCTTGGGAGTCCCTGATGATTAATGATTAAATAAACCAAGATTTTACCATGACTGCAATTTTAGAGAGACGCGAAAGCGAAAGCCTATGGGGTCGCTTTTGTAACTGGATAACCAGCACTGAAAACCGTCTTTACATTGGATGGTTTGGTGTTTTGATGATCCCTACTTTATTGACCGCAACTTCTGTATTTATTATTGCTTTCATTGCTGCACCTCCAGTAGATATTGATGGTATTCGTGAACCTGTTTCTGGATCTTTACTTTATGGAAACAATATTATTTCTGGTGCCATTATTCCTACCTCTGCAGCTATAGGTTTGCACTTTTACCCGATATGGGAAGCGGCTTCCGTTGATGAATGGTTATACAATGGTGGTCCTTATGAACTAATTGTTCTACACTTCTTACTTGGTGTAGCTTGCTACATGGGTCGTGAGTGGGAACTTAGTTTCCGTCTGGGTATGCGCCCTTGGATTGCTGTTGCATATTCAGCTCCTGTTGCAGCTGCTACTGCTGTTTTCTTGATATATCCAATTGGTCAAGGAAGCTTTTCTGACGGTATGCCCCTAGGAATCTCCGGTACTTTCAACTTCATGATTGTATTCCAAGCTGAGCACAACATCCTTATGCACCCATTTCACATGTTAGGCGTAGCTGGTGTATTCGGCGGCTCCCTATTCAGTGCTATGCATGGGTCCTTGGTAACCTCTAGTTTGATCAGGGAAACCACAGAAAATGAATCTGCTAATGAAGGTTACAGATTCGGTCAAGAGGAAGAAACCTATAATATCGTAGCCGCTCATGGTTATTTTGGCCGATTGATCTTCCAATATGCTAGTTTCAACAACTCTCGTTCTTTACATTTCTTCCTAGCTGCTTGGCCTGTAGTAGGTATCTGGTTTACCGCTTTAGGTATCAGCACTATGGCTTTCAACTTAAATGGTTTTAATTTCAATCAATCTGTAGTTGATAGTCAGGGTCGTGTAATTAATACTTGGGCTGATATTATTACCCGGGCTAACCTTGGTATGGAAGTTATGCATGAACGTAATGCTCATAATTTCCCTCTAGATCTAGCTGCTGTTGAAGTTCCATCTATAAATGGATAAGACTTAGGTCTTAGTATATACGAGATCTTGAAAGAAAAGG'
    },
    {
        'index': 10,
        'orfs': [
            {
                'frame': 0,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    351,
                    783
                ),
                'pro': 'ELRNGEQIEEMTLNLCVLTPNRIVWDSEVKEIILSTNSGQIGVLPNHAPVATAVDIGILRIRLNDQWLTMALMGGFARIGNNEITVLVNDAEKGSDIDPQEAQQTLEIAEANLRKAEGKRQTIEANLALRRARTRVEAINVMS',
                'strand': -1
            }
        ],
        'sequence': 'GTCCCATTTGTTTCTCTTTGTGATGATAAATGACCTACTTAACTCAGTGGTTAGAGTATTGCTTTCATACGGCGGGAGTCATTGGTTCAAATCCAATAGTAGGTAAAACTAATTAGATACCAGTAGATACCAGAGTCAATGGTATCTAATAAGTTTTTCTACTCATCTTTTTATATTAATTTTTTATCTTTTTCGTCCTACCTTCTCTCTTTAGTTAATTTAATTTTAAAAATTTTTGTATTTCATTAGAATTTTATTCCACTTGATTGTATTTGATTCTTATTCAATCGGCAGGAACAAAATTAGGTGTATAAACTTATTTTGCTTATTCGGACGGACCAACTAGACTAGTTACGACATCACATTGATAGCCTCTACTCGTGTCCTAGCTCGTCTGAGAGCTAAATTTGCCTCAATTGTTTGTCTCTTGCCTTCAGCTTTCCTCAAGTTAGCTTCCGCTATTTCAAGAGTTTGTTGCGCTTCTTGTGGATCAATGTCACTACCCTTCTCTGCATCATTTACTAAAACCGTGATCTCATTATTGCCTATTCTAGCAAAACCACCCATCAGAGCCATCGTTAACCATTGGTCGTTAAGGCGTATTCTCAAAATACCGATATCTACAGCTGTGGCAACAGGCGCGTGATTTGGTAATACGCCAATTTGTCCACTATTAGTAGATAAAATAATTTCTTTCACTTCCGAATCCCAAACAATTCGATTCGGGGTCAGTACACAAAGATTTAAGGTCATTTCTTCAATTTGCTCTCCATTTCTAAGTTCCTAAGGTCGTAGCTTTCGCAGTAGCTTCATCGATGTTACCTACCAAATAAAAGGCCTGTTCAGGAAGGCCGTCTAATTCTCCAGAAAGGATCAATTTAAACCCTCTAATCGTTTCTGCTAGACCAACGTATTTTCCTGGGGAACCGGTAAATACTTCTGCTACGAAAAAGGGTTGTGATAAGAAACGCTCAATTTTTCGTGCTCTTGCTACGGTTAAGCGATCGTCTTCGGATAATTCGTCCAACCCAAGGATAGCTATAATGTCTT'
    },
    {
        'index': 11,
        'orfs': [
            {
                'frame': 1,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    31,
                    916
                ),
                'pro': 'LTQAPLSNAYPIFAQQGYENPREATGRIVCANCHLANKPVDIEVPQAVLPDTVFEAVVRIPYDLQLKQVLANGKKGALNVGAVLILPEGFELAPPDRILPEIKEKIGNLSFQSYRPTKKNILVIGPVPGQKYSEITFPILSPDPATKKDVHFLKYPIYVGGNRGRGQIYPDGSKSNNNVYNATAAGIVSKIIRKEKGGYEITIANASDGRQVVDIIPPGPELLVSEGESIQLDQPLTSNPNVGGFGQGDAEIVLQDPLRVQGLLLFLASVILAQIFLVLKKKQFEKVQLSEMNF',
                'strand': 1
            }
        ],
        'sequence': 'ATCCATTTCCGTATCGTTCATTTTATATTAATTAACCCAGGCACCCCTTTCAAATGCATATCCCATTTTTGCACAGCAGGGTTATGAAAATCCACGAGAAGCGACTGGCCGTATTGTATGTGCCAATTGCCATTTAGCTAATAAACCCGTGGATATCGAGGTTCCACAAGCGGTACTTCCTGATACTGTATTTGAAGCAGTTGTTCGAATTCCTTATGATCTGCAACTGAAACAAGTTCTTGCTAATGGTAAAAAAGGAGCTTTGAATGTAGGGGCTGTTCTTATTTTACCCGAGGGGTTTGAATTAGCCCCTCCCGATCGTATTTTGCCCGAGATAAAAGAAAAGATAGGAAATCTGTCTTTTCAGAGCTATCGCCCCACTAAAAAAAATATTCTTGTGATAGGTCCTGTTCCTGGTCAGAAATATAGTGAAATCACCTTTCCTATTCTTTCCCCGGACCCCGCTACTAAGAAAGATGTTCACTTCTTAAAATATCCCATATACGTAGGCGGGAACAGGGGAAGGGGTCAGATTTATCCCGACGGGAGCAAGAGTAACAATAATGTTTATAATGCTACAGCAGCAGGTATAGTAAGCAAAATCATACGAAAAGAAAAGGGGGGGTACGAAATAACCATAGCGAATGCATCGGATGGACGTCAAGTGGTTGATATTATCCCTCCAGGACCGGAACTTCTTGTTTCAGAGGGCGAATCCATCCAACTTGATCAACCATTAACGAGTAATCCTAATGTGGGTGGATTTGGTCAGGGGGATGCGGAAATAGTACTTCAAGATCCATTACGTGTCCAAGGTCTTTTGCTATTCTTGGCATCTGTTATTTTGGCACAAATATTTTTGGTTCTTAAAAAGAAACAGTTTGAGAAGGTTCAATTGTCCGAAATGAATTTCTAGATAAGCGTATTTATAAAAATAAAGCTCTTAAAATAAACAAATTATAGTTGGCAATTATGTTATGTAATTATGTATAATCAAAAAAATATTGATT'
    },
    {
        'index': 12,
        'orfs': [
            {
                'frame': 1,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    1,
                    502
                ),
                'pro': 'TGFAMTFYYRPTVTEAFASVQYIMTEANFGWLIRSVHRWSASMMVLMMILHVFRVYLTGGFKKPRELTWVTGVVLGVLTASFGVTGYSLPRDQIGYWAVKIVTGVPDAIPVIGSPLVELLRGSASVGQSTLTRFYSLHTFVLPLLTAVFMLMHFPMIRKQGISGPL',
                'strand': 1
            }
        ],
        'sequence': 'AACAGGGTTTGCTATGACTTTTTATTATCGTCCGACCGTTACAGAGGCTTTTGCTTCTGTTCAATATATAATGACTGAAGCTAATTTTGGTTGGTTAATCCGATCGGTTCATCGATGGTCGGCAAGTATGATGGTCCTAATGATGATCCTGCACGTATTTCGTGTGTATCTAACCGGTGGCTTTAAAAAACCTCGCGAATTGACTTGGGTTACAGGTGTGGTTTTGGGTGTATTGACCGCATCTTTTGGTGTAACTGGTTATTCCTTACCTCGGGACCAAATTGGTTATTGGGCAGTAAAAATTGTAACAGGCGTACCAGACGCTATTCCTGTAATAGGCTCGCCCCTGGTAGAGTTATTACGCGGAAGTGCTAGTGTGGGACAATCCACTTTGACTCGTTTTTATAGTTTACACACTTTTGTATTACCTCTTCTTACTGCCGTATTTATGTTAATGCACTTCCCAATGATACGTAAGCAAGGTATTTCTGGTCCTTTATAAAGAATATATACCATCTGTAATCAATCATTTATCACTTGGGGTAGGAACAATAGTATTTCATTGCTACAAATATGGATTATTGAAAAGAATAAGACATGTATTGGGATATTTCTCTTCAACTCTACAAAAATGTATTATTTTTTTGACACTCATAGTTGAAGCGAATTTTCCGAAGATAAAATGGATTATGGGAGTGTGTGACTTGAACTATTGATCGGGCCTTGCAGATATATGCCCTTATCTATCTGCCACATTTTAATTCACAACAAAAAATGTGTCTTTGTTCCAACCACCGCGTAAGCCCCATACAGAAGATAGGCCGGTTCGTTTGAAGAGAATCTTTTCTATGATCAGACCCGATCATGTCGTGTATGATATGAACAGGCTCCGTAAGATCCGATCCAGTAGAATAAGTGATTGGCATAATCCGG'
    },
    {
        'index': 13,
        'orfs': [
            {
                'frame': 2,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    341,
                    707
                ),
                'pro': 'SMNILFFFQFLIDSQQFFHFSYKYQKIKIRAVINHLEIVLQYYTYAYRFILHPFGSFDVRIPLLTQCSQLHLLEQLPLSLCTYPFLFSVYETLVCFNKTGFGSGSPIFNSRVSLNLKVLTW',
                'strand': 1
            }
        ],
        'sequence': 'GTTCGTTTGTACGTGTATCATATATATAACACATGAGGCTTGTGATAAGAAAAAAATTTCCGCTCAGATCCGTTTGTGAAAGAGTAGAATGAATGAGAAACATAACGAATTTTGAATCGCTAACAAAATGATAAAAGATAAATAATTAGGGAGTCAACCGTTTCGTTTTGGGGATAGAGGGACTTGAACCCTCACGATTTCTAAAGTCGACGGATTTTCCTCTTACTATAAATTTCATTGTTGTCGATATTGACATGTATAATGGGACTCTATCTTTATTCTCGTCCGATTAATCAATTCTTAAAAAGATCTATCAGACTATGATGGAGTGAATGATTTGATCAATGAATATTCTATTCTTTTTTCAATTTTTAATCGATTCACAACAATTCTTTCATTTTTCATATAAATATCAAAAAATAAAGATTCGGGCCGTCATTAATCATTTGGAGATAGTATTGCAGTACTATACGTATGCATATAGGTTTATCCTTCATCCTTTCGGAAGTTTCGATGTAAGGATTCCTTTACTAACACAATGCAGCCAACTCCATTTGTTAGAACAGCTTCCATTGAGTCTCTGCACCTATCCTTTTTTATTCTCGGTTTATGAAACCCTTGTTTGTTTTAATAAAACAGGATTTGGCTCAGGATCGCCCATTTTTAATTCCAGGGTTTCTCTGAATTTGAAAGTTCTCACTTGGTAGGTTTCCATACCAAGGCTCAATCCAATTAAGTCCGTAGCGTCTACCAATTTCGCCATATCCCCTTTTTTGTTTTGTGATTAGGATCACATTATGATGCCGTCACCCTTTTTTCTTTCGTTTATATTATGCTGGAACCGTTGAATTCATTAGATACCGGTTCCTTTATTTAAA'
    },
    {
        'index': 14,
        'orfs': [
            {
                'frame': 1,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    1,
                    774
                ),
                'pro': 'QQRKHFFTLSYTRGFHLEKKMFHTNGFGSITMGSNVRDLVALTNEALSISITQKKSIIDTNIIRSALHRQTWDLRSQVRSVQDHGILFYQIGRAVAQNVLLSNCSIDTISIYMKKKSCNEGDSYLYKWYFELGTSMKKLTILLYLLSCSAGSVAQDLWSLPRPDEKNGITSYGLVENDSDLVHGLLEVEGAPVGSSRTEKDCSQFDNDRVTLLLRPEPRNPLDMMQNGSCSIVDQRFLYEQYESEFEEGEGVLDPQR',
                'strand': 1
            }
        ],
        'sequence': 'ACAACAACGAAAGCACTTTTTCACTCTTTCATATACTAGGGGATTTCACTTGGAAAAGAAAATGTTCCATACTAATGGATTCGGGTCCATAACCATGGGTTCCAATGTACGAGATCTTGTAGCACTTACCAATGAGGCCCTATCGATTAGTATTACACAGAAGAAATCAATTATAGACACTAATATAATTAGATCTGCTCTTCATAGACAAACTTGGGATTTGCGATCCCAAGTAAGATCGGTTCAGGATCATGGGATCCTTTTCTATCAGATAGGAAGGGCTGTTGCACAAAATGTACTTCTAAGTAATTGCTCCATAGATACTATATCTATCTATATGAAGAAGAAATCATGTAACGAAGGGGATTCTTATTTGTACAAATGGTACTTCGAACTTGGAACGAGCATGAAGAAATTAACGATACTTCTTTATCTTTTGAGTTGTTCTGCCGGATCGGTCGCTCAAGACCTTTGGTCTCTACCCCGACCCGATGAAAAAAATGGGATCACTTCTTATGGACTCGTTGAGAATGATTCTGATCTAGTTCATGGCCTATTAGAAGTAGAAGGCGCTCCGGTGGGATCCTCACGGACAGAAAAAGATTGCAGTCAGTTTGATAATGATCGAGTGACATTGCTTCTTCGGCCCGAACCAAGGAATCCCTTAGATATGATGCAAAATGGATCTTGTTCTATCGTTGATCAGAGATTTCTCTATGAACAATACGAATCGGAGTTTGAAGAAGGGGAAGGAGTCCTCGACCCGCAACGGAT'
    },
    {
        'index': 15,
        'orfs': [
            {
                'frame': 2,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    2,
                    690
                ),
                'pro': 'AGHQVHVSLPINQFLNVGVDPKEIPLPHEFILNRDLLAQLYPSFAEGATPFFTLNWSKYAEFLTFRGGLDPVTGGLWLTDIAHHHLAIAILFLVAGHMYRTNWGIGHGIKDILEAHKGPFTGQGHKGLYEILTTSWHAQLSINLAMLGSLTIIVAHHMYSMPPYPYLATDYGTQISLLTHNMWIGGFLIVGAAAHAAIFMVRDYDPTTRYNDLLDRVLRHRDAIISHLN',
                'strand': 1
            }
        ],
        'sequence': 'AGGCGGGACATCAAGTACACGTATCTTTACCAATTAACCAATTTCTAAACGTTGGAGTAGATCCTAAAGAGATTCCACTTCCTCATGAATTTATCTTGAATCGGGATCTTTTGGCTCAACTTTATCCCAGTTTTGCTGAGGGAGCAACCCCATTTTTCACCTTGAATTGGTCAAAATATGCGGAATTTCTTACCTTTCGTGGAGGATTAGATCCAGTAACTGGAGGTCTATGGCTGACCGATATTGCACACCATCATTTAGCTATTGCAATTCTTTTCCTGGTAGCGGGTCACATGTATAGAACCAACTGGGGCATTGGTCATGGTATAAAAGATATTTTAGAGGCTCATAAAGGCCCATTTACGGGCCAGGGCCATAAAGGCCTATATGAGATCCTAACAACGTCATGGCATGCTCAATTATCTATTAACCTCGCTATGTTAGGATCTTTAACCATTATTGTAGCTCACCATATGTATTCGATGCCCCCTTATCCATATCTAGCTACTGACTATGGTACACAAATTTCATTGTTAACACATAACATGTGGATTGGTGGATTTCTCATAGTTGGTGCTGCTGCGCATGCAGCCATTTTTATGGTAAGAGACTATGATCCAACTACTCGATACAACGATCTATTAGATCGTGTTCTTAGGCATCGCGATGCAATCATATCACATCTCAACT'
    },
    {
        'index': 16,
        'orfs': [
            {
                'frame': 1,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    -1,
                    539
                ),
                'pro': 'TKVFVLGWRLKISLMKTLYSLRRFYPVETLFNGTLALAGRDQETTGFAWWAGNARLINLSGKLLGAHVAHAGLIVFWAGAMNLFEVAHFVPEKPMYEQGLILLPHLATIGWGVGPGGEVLDTFPYFVSGVLHLISSAVLGFGGIYHALLGPETLEESFPFFGYVWKDRNKMTTILGIHL',
                'strand': -1
            }
        ],
        'sequence': 'ATTAAGTGAATACCCAAAATTGTAGTCATTTTGTTTCTATCTTTCCATACATAACCGAAGAATGGAAAAGATTCTTCAAGAGTCTCGGGTCCCAGAAGTGCATGATAAATACCGCCAAAGCCCAATACTGCAGAGGAAATTAAGTGAAGTACTCCAGACACAAAGTATGGAAAGGTGTCTAGAACTTCCCCACCCGGACCTACCCCCCATCCTATAGTAGCTAGGTGGGGAAGTAAAATTAATCCTTGTTCATACATAGGCTTCTCTGGTACGAAATGAGCCACTTCAAATAGGTTCATTGCTCCGGCCCAGAATACGATTAATCCGGCATGGGCTACATGAGCCCCCAGTAGTTTACCGGATAAATTGATAAGTCGGGCATTCCCGGCCCACCAAGCGAAACCAGTGGTTTCTTGGTCACGACCGGCTAAAGCTAAAGTTCCATTAAAGAGCGTTTCCACGGGGTAGAACCTCCTCAGGGAATATAAGGTTTTCATGAGGCTGATCTTGAGCCGCCATCCAAGCACGAATACCTTCGTTTAAGAGAATATTTTTGGTGTAGAAAGTCTCAAATTCAGGATCTTCCGCTGCACGGATTTCCTGAGAAACGAAGTCATAGGCACGTAGGTTCAGGGCCAGACCGACTACTCCAAGAGCACTCATCCACAAACCGGTTACTGGTAC'
    },
    {
        'index': 17,
        'orfs': [
            {
                'frame': 1,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    1,
                    676
                ),
                'pro': 'LQPVFAQWIQHTHALAPSATAPGATTSTSLTWGGGDLVAVGGKVALLPIPLGTADFLVQHIHAFTIHVTVLILLKGVLFARSSRLIPDKANLGFRFPCDGPGRGGTCQVSAWDHVFLGLFWMYNAISVVIFHFSWNMQSDVWGSISDQGVVTHITGGNFAQSSITINGWLRDFLWAQASQVIQSYGSSLSAYGLFFLGAHFVWAFSLMFLFSGRGYWQELIESIV',
                'strand': 1
            }
        ],
        'sequence': 'ATTACAACCCGTCTTTGCTCAATGGATACAACACACCCATGCTTTAGCACCCAGTGCAACGGCCCCTGGTGCAACAACAAGCACCAGTTTGACTTGGGGGGGTGGTGATTTAGTGGCAGTGGGCGGCAAAGTTGCTTTGTTACCTATTCCATTAGGAACCGCAGATTTTTTGGTGCAGCACATTCATGCATTTACAATTCATGTGACGGTATTAATACTCCTGAAAGGTGTTCTATTTGCTCGAAGTTCACGTTTGATACCAGATAAAGCAAATCTTGGTTTTCGTTTCCCTTGTGATGGGCCGGGAAGAGGAGGGACATGCCAAGTATCCGCTTGGGATCATGTCTTCTTAGGGCTATTCTGGATGTATAATGCAATTTCGGTAGTAATATTCCATTTCAGTTGGAATATGCAGTCAGATGTTTGGGGTAGTATCAGTGATCAAGGAGTGGTAACTCATATCACGGGAGGAAACTTTGCGCAGAGTTCCATTACTATTAATGGGTGGCTCCGCGATTTCTTATGGGCACAGGCATCCCAGGTAATTCAGTCTTATGGTTCTTCATTATCCGCATATGGCCTTTTTTTCCTAGGTGCGCATTTTGTATGGGCTTTTAGTTTAATGTTTCTATTCAGCGGGCGTGGTTATTGGCAAGAACTTATTGAATCCATCGTT'
    },
    {
        'index': 18,
        'orfs': [
            {
                'frame': 2,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    11,
                    506
                ),
                'pro': 'NNSPILITKKPDLNDPVLRAKLAKGMGHNYYGEPAWPNDLLYIFPVVILGTIACNVGLAVLEPSMIGEPADPFATPLEILPEWYFFPVFQILRTVPNKLLGVLLMVSVPAGLLTVPFLENVNKFQNPFRRPVATTVFLIGTAVALWLGIGATLPIDKSLTLGLF',
                'strand': 1
            }
        ],
        'sequence': 'GATTGATATAAAATAATTCACCTATCCTAATAACAAAAAAACCTGACTTGAATGATCCTGTGTTAAGAGCTAAATTGGCTAAAGGGATGGGTCATAATTATTACGGAGAGCCCGCATGGCCAAACGATCTTTTATATATTTTTCCAGTAGTAATTTTAGGTACTATTGCATGTAACGTAGGCTTAGCGGTTCTAGAACCATCAATGATTGGTGAACCCGCGGATCCGTTTGCAACTCCTTTGGAAATATTGCCTGAGTGGTATTTCTTTCCCGTATTTCAAATACTTCGTACAGTGCCAAATAAGTTATTGGGTGTTCTTTTAATGGTTTCAGTACCTGCGGGATTATTAACAGTACCCTTTTTGGAGAATGTTAATAAATTCCAAAATCCATTTCGTCGTCCCGTAGCGACAACCGTCTTTTTGATTGGTACTGCAGTAGCCCTTTGGTTGGGTATTGGAGCAACACTACCTATTGATAAGTCCTTAACTTTAGGTCTTTTTTAAATTGATTCAATTGTGAAATAAAAAAAAATATATTACCACGTGTGTATCTAGGGAATAGTCGCTTCAAAGTGAATTTTCCCTAGATACATCTATTCAATTTTATTTTGGAC'
    },
    {
        'index': 19,
        'orfs': [
            {
                'frame': 2,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    -2,
                    598
                ),
                'pro': 'LLNYLLAGLFVCVVRKEEDSMIIRSPEPEVKILVDRDPVKTSFEEWARPGHFSRTIAKGPDTTTWIWNLHADAHDFDSHTSDLEEISRKVFSAHFGQLSIIFLWLSGMYFHGARFSNYEAWLSDPTHIGPSAQVVWPIVGQEILNGDVGGGFRGIQITSGFFQLWRASGITSELQLYCTAIGALVFAALMLFAGWFHYH',
                'strand': -1
            }
        ],
        'sequence': 'TGTGATAATGGAACCAACCAGCAAATAGCATTAAGGCAGCAAAGACCAATGCACCAATTGCAGTACAATAGAGTTGTAATTCACTAGTTATTCCAGATGCTCGCCAAAGCTGAAAAAACCCAGAGGTTATTTGTATTCCTCGGAAACCCCCGCCGACATCACCATTCAATATTTCTTGACCCACTATTGGCCAAACCACCTGGGCACTAGGTCCAATGTGAGTAGGATCACTTAGCCATGCTTCATAATTGGAAAAACGAGCACCATGGAAATACATACCACTCAGCCAAAGAAAGATGATGGAGAGTTGACCGAAATGGGCACTAAATACTTTGCGAGAGATCTCCTCCAAATCACTGGTATGGCTATCAAAATCGTGAGCATCAGCGTGTAGGTTCCAGATCCAAGTGGTAGTATCAGGTCCCTTAGCTATTGTTCTTGAGAAATGACCCGGTCTGGCCCATTCCTCGAAAGAAGTTTTTACGGGATCCCTATCTACCAAAATTTTAACTTCTGGTTCCGGCGAACGAATAATCATTGAGTCCTCCTCTTTCCGGACAACACATACAAAGAGACCCGCCAATAAATAGTTAAGTAATTAGTGAACAT'
    },
    {
        'index': 20,
        'orfs': [
            {
                'frame': 0,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    12,
                    510
                ),
                'pro': 'RGYASMITYMLFYISMNLGTFACIVLFGLRTGTDNIRDYAGLYTKDPFLALSLALCLLSLGGLPPLAGFFGKLHLFWCGWQAGLYFLVSIGLLTSVVSIYYYLKKIKLLMTGRNQEITPHVRNYRRSPLRSNNSIELSMIVCVIASTIPGISMNPIIEIAQDTLF',
                'strand': -1
            }
        ],
        'sequence': 'AGATTCTAGAAGCTAAAAAAGGGTATCCTGAGCAATTTCAATAATCGGGTTCATTGATATTCCTGGTATAGTAGATGCTATCACACATACAATCATACTCAATTCGATGGAATTGTTTGATCTTAAAGGGGATCTTCTATAATTTCGCACGTGAGGGGTTATTTCTTGGTTTCGTCCAGTCATTAATAACTTGATTTTTTTTAGATAATAGTAGATAGAAACAACGCTCGTAAGGAGTCCTATTGAAACCAAGAAATATAGGCCTGCCTGCCATCCACACCAGAATAAATGAAGTTTTCCGAAAAAACCTGCTAGTGGAGGAAGACCTCCTAAGGATAAGAGACAAAGGGCTAAAGAGAGAGCCAAAAAAGGATCTTTTGTGTATAATCCTGCATAATCTCGAATGTTATCAGTTCCGGTACGTAGACCAAATAATACAATGCAAGCAAAAGTTCCTAGATTCATGGAGATATAGAACAGCATATAAGTTATCATGCTTGCATATCCACG'
    },
    {
        'index': 21,
        'orfs': [
            {
                'frame': 2,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    148,
                    484
                ),
                'pro': 'RYQLIQQLDRWSYRIISLGFIFLTVGILSGAVWANEAWGSYWNWDPKETWAFITWTVFAIYLHIRTNKIFESINSAIVASMGFLIIWICYFGVNLLGIGLHSYGSFTLTSN',
                'strand': -1
            }
        ],
        'sequence': 'GTCTGGCATTTCTGAGAACCATTTGAATCGAGTAATGGAAATGGAATGATTCAAATGGTTCTTAATGGTTTACATGAAGTTTTCGTATATATACACGTATGCCATCCTATGTTTCTATTCGTCAAGTCAGTCAAGTCCTTTATTTAATTCAATTAGATGTTAATGTAAATGAACCATAACTATGCAACCCTATTCCTAATAGATTAACCCCAAAATAGCATATCCAAATTATAAGAAAGCCCATTGAGGCCACAATTGCAGAATTTATACTTTCAAAAATTTTATTTGTTCTAATATGTAAATAAATCGCGAATACGGTCCAAGTAATAAATGCCCAAGTCTCCTTTGGATCCCAATTCCAATATGATCCCCATGCTTCATTAGCCCATACTGCTCCCGAAAGAATACCAACGGTTAAAAAGATAAACCCTAGACTAATAATACGATAACTCCACCGATCCAATTGTTGAATCAATTGGTACCTGT'
    },
    {
        'index': 22,
        'orfs': [
            {
                'frame': 0,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    144,
                    472
                ),
                'pro': 'NEWKDNLLSLSDLLDNRKQRILKTIRNSEELREGALDQLEKARARLRKVETEADQFRVNGYSEIEREKLNLINSTYKTLEQLENYKNETIHFEQQRAINQVRQRVFQQA',
                'strand': 1
            }
        ],
        'sequence': 'GAATATGAATAGAGAAGAGAGGATAGGCTCATTACATTAAAAAAAAAATGGGAATTCCCATAAGTAATTGAAAAAATTGAGCGTGAGAGCCAAATGAAGCGAAAGATTCATGTTTGGTTCGGGAAGGGATCGTGGAAGTTTTGAAATGAATGGAAAGATAATCTACTTTCATTAAGTGATTTATTAGATAATCGAAAACAGAGGATCTTGAAGACTATTCGAAATTCAGAAGAACTACGCGAGGGGGCCCTAGACCAACTGGAAAAAGCCCGGGCCCGCTTACGGAAAGTAGAAACGGAAGCGGATCAGTTTCGAGTGAATGGATACTCTGAAATAGAACGAGAAAAATTGAATTTGATTAATTCCACCTATAAGACTTTGGAACAATTAGAAAATTACAAAAATGAAACCATTCATTTTGAACAACAAAGAGCGATTAATCAAGTTAGACAACGGGTTTTTCAGCAAGCCT'
    },
    {
        'index': 23,
        'orfs': [
            {
                'frame': 1,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    46,
                    469
                ),
                'pro': 'AVISNPEVKRTLATLRKAEFGFLGVIVEKLTDKSPLLPLYRTVHEIFTSYGSSFNSFEVIGSFSSFENLFPYSTPFRRVTRTNSVTFSFIWNLGSSTSFLFTYFFIIFPSLFFFYFFFYSLPSFLKSHRFDPVESDPFSH',
                'strand': 1
            }
        ],
        'sequence': 'GACTACAGAATGTTCTTGTAAATTATGGCCAATACCAGGTATATAAGCAGTGATTTCAAATCCAGAGGTTAAGCGTACTCTGGCAACTTTACGTAAGGCAGAGTTTGGTTTTTTGGGGGTGATAGTGGAAAAGTTGACAGATAAGTCACCCTTACTGCCACTCTACAGAACCGTACATGAGATTTTCACCTCATACGGCTCCTCGTTCAATTCTTTTGAAGTCATTGGATCCTTTTCCTCGTTCGAGAATCTCTTCCCTTATTCCACTCCGTTCCGAAGAGTAACTAGGACCAATTCAGTCACGTTTTCATTCATTTGGAATCTGGGCTCTTCTACTTCATTTTTATTTACTTATTTTTTTATTATTTTTCCCTCTCTTTTCTTTTTTTATTTCTTTTTTTATTCCCTTCCATCATTCCTTAAGTCCCATAGGTTTGATCCTGTAGAATCTGACCCATTTTCTCATTGAGC'
    },
    {
        'index': 24,
        'orfs': [
            {
                'frame': 1,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    1,
                    463
                ),
                'pro': 'FNTSCLAERRIFLAHYQTITYSQTSCGANSFHFPSHGKPFSLRLALSLSRGILVIGSLGTGRSYLVKYLATNSYVPFITVFLNKFLDNKPKGFLVDDSDDIDDSDDIDDSDDRDFDTELELLTMMNALTMGMMPEIDRFYITLQFELAKAMSPC',
                'strand': 1
            }
        ],
        'sequence': 'GTTCAATACATCCTGTTTAGCAGAAAGACGGATATTCCTTGCTCATTATCAGACAATCACTTATTCACAAACCTCCTGTGGGGCTAATAGTTTTCATTTCCCATCTCATGGAAAACCCTTTTCGCTCCGCTTAGCCCTATCCCTCTCTAGGGGTATTTTAGTGATAGGTTCTCTAGGAACTGGACGATCCTATTTGGTCAAATACCTAGCGACAAACTCCTATGTTCCTTTCATTACAGTATTTCTGAACAAGTTCCTGGATAACAAGCCCAAGGGTTTTCTTGTTGATGATAGTGACGATATTGATGATAGCGACGATATTGATGATAGTGACGACCGTGACTTTGATACGGAGCTAGAGCTTCTAACTATGATGAATGCGCTAACTATGGGTATGATGCCGGAAATAGACCGATTTTATATCACCCTTCAATTCGAATTAGCAAAAGCAATGTCTCCTTGC'
    },
    {
        'index': 25,
        'orfs': [
            {
                'frame': 1,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    1,
                    435
                ),
                'pro': 'GNLFHVAWQGNFEAWVQDPLHVRPIAHAIWDPHFGQPAVEAFTRGGALGPVNIAYSGVYQWWYTIGLRTNEDLYTGALFLLFLSAISLIAGWLHLQPKWKPSVSWFKNAESRLNHHLSGLFGVSSLAWTGHLVHVAIPGSRGEN',
                'strand': 1
            }
        ],
        'sequence': 'CGGAAATCTGTTTCATGTAGCTTGGCAAGGAAATTTTGAGGCATGGGTACAGGATCCTTTACATGTAAGACCTATTGCTCATGCAATTTGGGATCCTCATTTTGGTCAACCAGCTGTAGAAGCTTTTACTCGGGGGGGTGCTCTTGGCCCAGTGAATATCGCTTATTCTGGTGTTTATCAGTGGTGGTATACAATTGGTTTACGTACTAACGAGGATCTTTATACTGGCGCTCTTTTTCTATTATTTCTTTCTGCCATATCCTTAATAGCGGGTTGGTTACACCTACAACCGAAATGGAAGCCGAGCGTTTCGTGGTTTAAAAATGCCGAATCTCGTCTAAATCATCATTTGTCAGGACTATTCGGAGTGAGTTCCTTAGCTTGGACAGGACATTTAGTTCATGTCGCTATTCCCGGATCCAGGGGAGAAAACGT'
    },
    {
        'index': 26,
        'orfs': [
            {
                'frame': 0,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    -2,
                    412
                ),
                'pro': 'DLFNHIVWAPRIWRPWGFLFDCIERPNELGFPYWVRAFRGKRIIYDEEDGLQENDSEFLQSGTMQYQTRDRSSKEQGFFRISQFIWDPADPLFFLFKDQPFISVFSHREFFADEEMSKGLLTSQTDLPTSIYKRWFI',
                'strand': -1
            }
        ],
        'sequence': 'AGATAAACCAGCGTTTATATATAGATGTAGGAAGATCCGTTTGGGAAGTAAGAAGCCCCTTTGACATCTCTTCATCTGCAAAGAATTCTCGATGTGAAAACACAGAGATAAAAGGCTGATCTTTGAATAGGAAAAAGAGTGGATCCGCAGGGTCCCAAATGAATTGGCTTATTCGAAAAAAGCCTTGTTCTTTGGAAGATCTATCTCGTGTCTGGTACTGCATGGTTCCACTCTGCAAGAACTCCGAATCATTTTCTTGAAGCCCATCCTCTTCATCATAAATGATACGCTTGCCCCGAAATGCCCTGACCCAATAGGGAAAACCCAATTCATTGGGCCTTTCGATACAATCAAATAGAAAGCCCCACGGGCGCCATATTCTAGGAGCCCAAACTATGTGATTGAATAAATC'
    },
    {
        'index': 27,
        'orfs': [
            {
                'frame': 1,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    1,
                    331
                ),
                'pro': 'AKISSALYDYQSNKKLFYVSILTSPTTGGVTASFGMLGDIIIAEPNAYIAFAGKRVIEQTLNKTVPEDSQVAEYLFHKGLFDPIVPRNPLKGVLGELFRLHAFFPLNKN',
                'strand': 1
            }
        ],
        'sequence': 'GGCTAAAATATCTTCTGCTTTATATGATTATCAATCAAATAAAAAGTTATTTTATGTATCAATCCTTACATCCCCTACCACAGGTGGGGTGACGGCCAGCTTTGGTATGTTGGGAGATATCATTATTGCCGAACCCAATGCTTACATTGCATTTGCGGGTAAAAGAGTAATTGAACAAACATTGAATAAGACAGTACCTGAGGATTCACAAGTGGCTGAATATTTATTCCATAAGGGCTTATTCGATCCAATCGTACCACGTAATCCTTTAAAGGGCGTTCTGGGTGAGTTATTTCGGCTACATGCTTTCTTTCCTTTGAATAAAAATTAGATCGATCAAGTAGAGCCTTAGAGTCTTAATTTAATAAGAGTTTTAATTTATTAAATCTTAATAAAATTTTTTTTTTTTG'
    },
    {
        'index': 28,
        'orfs': [
            {
                'frame': 1,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    1,
                    380
                ),
                'pro': 'LSLLLGHGENTGLSSSTPWLTPLTPTASSTESGLNSAARRRTGCRRRSPTPGLTMSSIALSLLGPKLLSSCTRSSKEWTLTPIVSRLPTMKTCYSAPLGGTALLSTVRAIPLAMACLSTVITGVTG',
                'strand': 1
            },
            {
                'frame': 1,
                'hits': [
                ],
                'index': 1,
                'pos': (
                    -2,
                    379
                ),
                'pro': 'TSNTSNNSGQAGHRKRNCPHRGQQSGPPQRSGVTCFHCGQSGHYRSECPLLTAASTTRQELGAQQGQSDRGHGQTRGGGSSSAAGSSSSSGVQSTFRGRGGRSQRGQPWRATTQARVFSMPQQEAQ',
                'strand': -1
            }
        ],
        'sequence': 'CCTGAGCCTCCTGCTGGGGCATGGAGAAAACACGGGCCTGAGTAGTAGCACGCCATGGCTGACCCCTCTGACTCCTACCGCCTCGTCCACGGAAAGTGGACTGAACTCCGCTGCTCGAAGAAGAACCGGCTGCAGAAGAAGATCCCCCACCCCGGGTCTGACCATGTCCTCTATCGCTTTGTCCCTGCTGGGCCCCAAGCTCCTGTCTAGTTGTACTCGCAGCAGTAAGGAGTGGACACTCACTCCTATAGTGTCCAGACTGCCCACAATGAAAACATGTTACTCCGCTCCTCTGGGGGGGACCGCTCTGCTGTCCACGGTGCGGGCAATTCCTCTTGCGATGGCCTGCTTGTCCACTGTTATTACTGGTGTTACTGGTC'
    },
    {
        'index': 29,
        'orfs': [
            {
                'frame': 0,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    0,
                    367
                ),
                'pro': 'EGVLIDQKEESTSTDMPLGTAIHNIEITLGKGGQLARAAGAVAKLIAKEGKSATLKLPSGEVRLISKNCSATVGQVGNVGVNQKSLGKAGSKCWLGKRPVVRGVVMNPVDHPHGGGEGRAPI',
                'strand': 1
            },
            {
                'frame': 2,
                'hits': [
                ],
                'index': 1,
                'pos': (
                    17,
                    365
                ),
                'pro': 'IGALPSPPPWGWSTGFITTPLTTGRLPSQHLDPALPKLFWFTPTFPTCPTVAEQFLDIKRTSPEGNFNVADFPSFAISFATAPAALANCPPFPSVISMLCMAVPKGISVEVDSSF',
                'strand': -1
            }
        ],
        'sequence': 'GAAGGGGTTTTGATTGATCAAAAAGAAGAATCTACTTCAACCGATATGCCCTTAGGCACGGCCATACATAACATAGAAATCACACTTGGAAAGGGTGGACAATTAGCTAGAGCAGCAGGTGCTGTAGCGAAACTGATTGCAAAAGAGGGGAAATCGGCCACATTAAAATTACCTTCTGGAGAGGTCCGTTTGATATCCAAAAACTGCTCAGCAACAGTCGGACAAGTGGGGAATGTTGGGGTGAACCAGAAAAGTTTGGGTAAAGCCGGATCTAAATGTTGGCTAGGTAAGCGTCCTGTAGTAAGAGGAGTAGTTATGAACCCTGTAGACCATCCCCATGGGGGTGGTGAAGGGAGGGCCCCAATTG'
    },
    {
        'index': 30,
        'orfs': [
            {
                'frame': 1,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    -1,
                    338
                ),
                'pro': 'RKLLDRYPTSELNSFWLKNLFLVAREQLGDSLEEIRGSASVGNMLWGGGPAYGVKSIRSKKKYLNINLIDIISIIPNPINRIAFSRNTRHLSHTSKEIYSLIRKRKNVNGDW',
                'strand': -1
            }
        ],
        'sequence': 'ATCCAATCACCGTTCACGTTTTTTCTTTTTCTTATCAATGAATAGATCTCTTTACTTGTATGACTTAGATGTCTCGTATTTCTCGAAAAAGCGATTCTATTGATGGGATTTGGTATGATACTTATGATATCGATGAGATTTATATTCAAATATTTCTTCTTAGAACGTATTGATTTGACCCCATAAGCGGGACCACCACCCCATAGCATGTTGCCGACAGAAGCAGAACCCCGTATTTCTTCTAGAGAATCTCCTAATTGTTCCCGAGCAACTAGAAAGAGATTCTTTAACCAGAAAGAATTCAGTTCAGATGTAGGATACCTATCCAGAAGTTTTCGC'
    },
    {
        'index': 31,
        'orfs': [
            {
                'frame': 2,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    -2,
                    316
                ),
                'pro': 'NQSYPVALEIIFYIGFLIAFAVKSPIIPLHTWLPDTQGEAHYSTCMLLAGILLKMGAYGLVRINMELLPHAHSIFSHWLKIVSTIKIIYAALKKHIKLILKKRIA',
                'strand': -1
            }
        ],
        'sequence': 'AGGCTATTCTTTTTTTTAAAATAAGCTTTATATGTTTTTTTAAAGCTGCATAGATTATTTTAATTGTGCTTACTATCTTCAACCAGTGAGAAAATATCGAATGAGCGTGGGGTAATAATTCCATATTGATCCGAACCAATCCATATGCTCCCATTTTTAATAAGATTCCGGCTAAAAGCATACAAGTACTGTAATGAGCCTCTCCTTGAGTGTCTGGTAACCATGTATGTAAGGGTATGATCGGTGATTTGACAGCAAAAGCAATAAGAAATCCAATATAGAATATTATTTCCAGTGCTACAGGATACGATTGATTAG'
    },
    {
        'index': 32,
        'orfs': [
            {
                'frame': 2,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    -3,
                    312
                ),
                'pro': 'EQCGCHLKMSSFDRIELSIDPGTWDPMNEDMVSLDPIEFHSEEEPYKNRIDSYQKNTGLTEAVQTGTGQLNGIPVAIGVMDFQFMGGSMGSVVGEKITRLAEYA',
                'strand': -1
            }
        ],
        'sequence': 'AGCATACTCGGCCAAACGTGTTATTTTTTCGCCCACTACAGATCCCATACTACCCCCCATAAACTGAAAATCCATAACTCCAATTGCTACGGGAATACCATTTAGTTGGCCTGTGCCTGTTTGAACGGCCTCAGTTAATCCTGTATTTTTTTGATAAGAATCAATACGATTTTTATAAGGTTCCTCCTCCGAATGAAATTCAATGGGATCCAGAGAGACCATGTCTTCGTTCATAGGATCCCAAGTACCGGGATCAATCGAAAGTTCGATTCTATCGAAACTACTCATTTTCAAATGACATCCACACTGTTCAC'
    },
    {
        'index': 33,
        'orfs': [
            {
                'frame': 0,
                'hits': [
                ],
                'index': 0,
                'pos': (
                    0,
                    305
                ),
                'pro': 'PYFVGATSTNSLMIKLQPKIYDHIMLTVRISFIPSVCSQVPVIVICLLELRGLSVETFTNNRRFLMVFPLLTAALSTPPDIWCQTVSCFLISLIIELSIFV',
                'strand': 1
            }
        ],
        'sequence': 'CCATACTTCGTGGGTGCAACATCAACAAATTCGCTCATGATCAAGTTACAACCTAAGATCTATGACCATATTATGTTAACTGTTCGTATTTCGTTCATTCCATCGGTATGCTCCCAGGTACCTGTAATTGTGATCTGTTTGCTAGAACTAAGGGGTCTTTCTGTGGAAACCTTCACGAACAATCGTCGTTTTTTGATGGTTTTTCCGCTTCTCACAGCTGCTCTTTCTACACCCCCGGATATCTGGTGCCAAACTGTCTCCTGTTTTCTTATTTCTTTGATAATAGAGTTGTCTATCTTTGTGGC'
    }
]
