name: pg

on:
  workflow_dispatch:

jobs:
  test-postgres:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:14.9
        env:
          POSTGRES_USER: virtool
          POSTGRES_PASSWORD: virtool
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        post-start:
          - psql -U virtool -c "CREATE DATABASE openfga;"
          - psql -U virtool -c "CREATE DATABASE virtool;"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start OpenFGA
        run: |
          sleep 5
          docker run --network ${{ job.services.postgres.network }} --rm openfga/openfga:v0.2.5 migrate --datastore-engine postgres --datastore-uri 'postgres://virtool:virtool@localhost:5432/openfga?sslmode=disable'

      - name: Do Nothing
        run: echo "Do nothing"