name: publish-4.0.0

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    if: github.repository_owner == 'Virtool'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  release:
    runs-on: ubuntu-20.04
    container:
      image: python:3.6-jessie
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Build Client
        run: |
          cd client
          npm i
          npx webpack --config webpack.production.config.babel.js
      - name: Build
        run: |
          mkdir gh_build
          apt-get update
          apt-get install -y libssl-dev zlib1g-dev python-dev
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
          python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); print(flags&os.O_NONBLOCK);'
          python setup.py build
          cp -rv build/exe.linux-x86_64-3.6 gh_build/virtool
          echo ${{ github.event.release.tag_name }} > gh_build/virtool/VERSION
          cd gh_build
          tar -czf virtool.tar.gz virtool
      - name: Publish Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: gh_build/virtool.tar.gz
          tag: ${{ github.event.release.tag_name }}
