name: publish

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  hooks:
    runs-on: ubuntu-22.04
    if: github.repository_owner == 'Virtool'
    steps:
      - name: Trigger Cloudflare
        run: curl -X POST ${{ secrets.CLOUDFLARE_HOOK }}
  ghcr:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    if: github.repository_owner == 'Virtool'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Write VERSION
        run: echo ${{ github.event.release.tag_name }} > VERSION
      - name: Update pyproject.toml version
        run: sed -i 's/0\.0\.0/${{ github.event.release.tag_name }}/' pyproject.toml
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/virtool/virtool
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}