apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-api
  labels:
    app.kubernetes.io/name: jobs-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: virtool
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jobs-api
      app.kubernetes.io/part-of: virtool
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jobs-api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: virtool
    spec:
      containers:
        - name: jobs-api
          image: ghcr.io/virtool/jobs-api:latest
          envFrom:
            - configMapRef:
                name: virtool-env
          ports:
            - containerPort: 9950
              protocol: TCP
          resources:
            limits:
              cpu: 600m
              memory: 800M
            requests:
              cpu: 400m
              memory: 400M
